### ISSUE TITLE
FunctionClauseError when Echo.Date given blank year arg

### ISSUE THREAD

**Issue by rgreenjr** [elixir-ecto/ecto#1520]
### Environment

* Elixir 1.3.0
* PostgreSQL 9.5.3
* Ecto  2.0.2
* Postgrex 0.11.2
* OS X El Capitan 1011.5

### Current behavior

A `FunctionClauseError` occurs when `Echo.Date` is given a blank `year` param.

For example:

```
defmodule Demo.Post do
  use Demo.Web, :model

  schema "posts" do
    field :title, :string
    field :publish_on, Ecto.Date

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :publish_on])
    |> validate_required([:title, :publish_on])
  end
end
```

```
iex> params = %{"publish_on" => %{"day" => "1", "month" => "1", "year" => ""}, "title" => "Test"}

iex> Demo.Post.changeset(%Demo.Post{}, params)
** (FunctionClauseError) no function clause matching in :calendar.valid_date/3
    (stdlib) calendar.erl:419: :calendar.valid_date(nil, 1, 1)
      (ecto) lib/ecto/date_time.ex:158: Ecto.Date.valid_date?/1
      (ecto) lib/ecto/type.ex:564: Ecto.Type.cast/2
      (ecto) lib/ecto/changeset.ex:429: Ecto.Changeset.cast_field/6
      (ecto) lib/ecto/changeset.ex:395: Ecto.Changeset.process_param/6
    (elixir) lib/enum.ex:1246: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1246: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
      (ecto) lib/ecto/changeset.ex:367: Ecto.Changeset.do_cast/6
      (demo) web/models/post.ex:16: Demo.Post.changeset/2
iex>
```

### Expected behavior

I believe the correct behavior should be to add an error to the associated field. That is the current behavior when a blank `month` or `day` param is given.

```
iex> params = %{"publish_on" => %{"day" => "1", "month" => "", "year" => "2000"}, "title" => "Test"}

iex> Demo.Post.changeset(%Demo.Post{}, params)
#Ecto.Changeset<action: nil, changes: %{title: "Test"},
 errors: [publish_on: {"is invalid", [type: Ecto.Date]}], data: #Demo.Post<>,
 valid?: false>
```

**Comment by michalmuskala** [comment]
Fixed in master

**Comment by rgreenjr** [comment]
Thanks Michał.
