### ISSUE TITLE
Manipulation of associations without persisting

### ISSUE THREAD

**Issue by jfrolich** [elixir-ecto/ecto#1621]
Tested on Ecto 2.0.2, will test on master later.

I would like to test manipulation of associations without persisting it in the database. If I insert `item` first, and then run the test, it does work, however as specified below it does error. I do not know if this is correct behaviour for some technical reason or it's a bug. Anyway the error message is very cryptic for me.

```elixir
defmodule EctoAssociationsManipulationTest do
  use ExUnit.Case, async: true

  defmodule User do
    use Ecto.Schema
    import Ecto.Changeset

    schema "users" do
    end

    def changeset(struct, params \\ %{}) do
     struct
     |> cast(params, [])
    end
  end

  defmodule ItemUser do
    use Ecto.Schema
    import Ecto.Changeset

    schema "item_users" do
      belongs_to :item, Item
      belongs_to :user, User
    end

    def changeset(struct, params \\ %{}) do
      struct
      |> cast(params, ["user_id"])
    end
  end

  defmodule Item do
    use Ecto.Schema
    import Ecto.Changeset

    schema "items" do
      has_many :item_users, ItemUser
    end

    def changeset(struct, params \\ %{}) do
      struct
      |> cast(params, [])
    end
  end

  test "put_assoc should work correctly" do
    working_item_user = %ItemUser{
      __meta__: %Ecto.Schema.Metadata{state: :loaded},
      user_id: 1
    }

    erroring_item_user = %ItemUser{
      user_id: 1
    }

    item_users =
      Item.changeset(%Item{item_users: [working_item_user]})
      |> Ecto.Changeset.put_assoc(:item_users, [%{user_id: 2}])
      |> Ecto.Changeset.get_field(:item_users)

    assert [%ItemUser{user_id: 2}] = item_users

    item_users =
      Item.changeset(%Item{item_users: [erroring_item_user]})
      |> Ecto.Changeset.put_assoc(:item_users, [%{user_id: 2}])
      |> Ecto.Changeset.get_field(:item_users)

    assert [%ItemUser{user_id: 2}] = item_users
  end
end
```

Yields:

```
  1) test put_assoc should work correctly (EctoAssociationsManipulationTest)
     test/models/ecto_associations_manipulation_test.exs:46
     ** (RuntimeError) cannot insert related %EctoAssociationsManipulationTest.ItemUser{__meta__: #Ecto.Schema.Metadata<:built, "item_users">, id: nil, item: #Ecto.Association.NotLoaded<association :item is not loaded>, item_id: nil, user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 1} because it is already associated to the given struct
     stacktrace:
       (ecto) lib/ecto/changeset/relation.ex:321: Ecto.Changeset.Relation.check_action!/2
       (ecto) lib/ecto/changeset/relation.ex:142: Ecto.Changeset.Relation.do_change/4
       (ecto) lib/ecto/changeset/relation.ex:285: Ecto.Changeset.Relation.map_changes/7
       (ecto) lib/ecto/changeset.ex:922: Ecto.Changeset.put_relation/5
       test/models/ecto_associations_manipulation_test.exs:65: (test)
```

**Comment by michalmuskala** [comment]
@jfrolich I tried reproducing on master, but failed. Could you try with master?

**Comment by jfrolich** [comment]
Yes, will do today.

**Comment by jfrolich** [comment]
Ok tested with master. Still same error. By the way I fixed a typo in my assert code but anyway it does not even reach the assert because of the error.
Did you test with the same code?

**Comment by jfrolich** [comment]
To be extra clear, it is this line that is causing the error:
```elixir
      |> Ecto.Changeset.put_assoc(:item_users, [%{user_id: 2}])
```
So changing an association that has not persisted before, errors. If we do persist first and then run `put_assoc` it works as expected. 

The use case for this to work is:
-  we might have a postprocessing on the associations
-  we might have a default state when creating a new item, that can be overridden by params in the changeset.

**Comment by jfrolich** [comment]
I improved the test case to show that with the metadata `:loaded` instead of `:built` the error occurs. When you first insert the item user the metadata will be `:loaded` instead of `:built` as the only difference.

**Comment by michalmuskala** [comment]
@jfrolich thank you. I will look at this again later today.

**Comment by jfrolich** [comment]
Any progress yet? Anywhere I can help out?
