### ISSUE TITLE
Share database with Rails - cannot load `"string"` as type :integer

### ISSUE THREAD

**Issue by overallduka** [elixir-ecto/ecto#1676]
Hello guys, im doing an phoenix app that should use and rails database, all my problem can be described and solved here: 
http://blog.isnorcreative.com/2015/08/29/rails-and-phoenix-ecto-sharing-a-datadatabase.html

Well i know that has an solution above, but does not have an simple solution without needed rename tables ? the exactly error im seeing right now is:
```
** (exit) an exception was raised:
2016-09-07T19:53:18.372704+00:00 app[web.1]:     ** (ArgumentError) cannot load `"782857111829844_785440714904817"` as type :integer
2016-09-07T19:53:18.372705+00:00 app[web.1]:         (ecto) lib/ecto/schema.ex:982: Ecto.Schema.load!/3
2016-09-07T19:53:18.372705+00:00 app[web.1]:         (ecto) lib/ecto/schema.ex:974: anonymous fn/3 in Ecto.Schema.do_load/4
2016-09-07T19:53:18.372706+00:00 app[web.1]:         (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
2016-09-07T19:53:18.372707+00:00 app[web.1]:         (ecto) lib/ecto/schema.ex:972: Ecto.Schema.do_load/4
2016-09-07T19:53:18.372707+00:00 app[web.1]:         (ecto) lib/ecto/schema.ex:957: Ecto.Schema.__load__/6
2016-09-07T19:53:18.372708+00:00 app[web.1]:         (ecto) lib/ecto/adapters/sql.ex:519: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
2016-09-07T19:53:18.372709+00:00 app[web.1]:         (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
2016-09-07T19:53:18.372709+00:00 app[web.1]:         (ecto) lib/ecto/adapters/sql.ex:513: Ecto.Adapters.SQL.process_row/3
```

There is anything that i can do just in phoenix/elixir side to solve this ?

Believe that phoenix using rails database is not an rare thing and this case will happen again with someone because this i open the issue.

Thanks.

**Comment by michalmuskala** [comment]
It looks like you're trying to run ecto migrations on a rails database. The migrations protocols are not compatible, you need to choose one side for doing migrations.
