### ISSUE TITLE
Does this issue occur for all users?

### ISSUE THREAD

**Issue by phpapi** [elixir-ecto/ecto#1707]
Just created the project, and follow the guide to run:
```
$ mix phoenix.gen.html User users name:string email:string bio:string number_of_pets:integer
* creating priv/repo/migrations/20150409213440_create_user.exs
* creating web/models/user.ex
* creating test/models/user_test.exs
* creating web/controllers/user_controller.ex
* creating web/templates/user/edit.html.eex
* creating web/templates/user/form.html.eex
* creating web/templates/user/index.html.eex
* creating web/templates/user/new.html.eex
* creating web/templates/user/show.html.eex
* creating web/views/user_view.ex
* creating test/controllers/user_controller_test.exs

Add the resource to your browser scope in web/router.ex:

    resources "/users", UserController

and then update your repository by running migrations:

    $ mix ecto.migrate
```
then run:
```
$ mix ecto.create
The database for repo HelloPhoenix.Repo has been created.
```
go on:

```
$ mix ecto.migrate
** (Postgrex.Error)   (syntax_error):   "NOT"  
    (ecto) lib/ecto/adapters/sql.ex:187: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:71: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:43: Ecto.Migrator.migrated_versions/2
    (ecto) lib/ecto/migrator.ex:142: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I was checked my database configure, nothing wrong, that's postgresql.

**Comment by shhavel** [comment]
@phpapi Can you please specify which versions of `PostgreSQL`, `phoenix`, `ecto` are used?
Please see [issue template](https://github.com/elixir-ecto/ecto/blob/master/ISSUE_TEMPLATE.md).
Also there is a strange migration time-stamp - **20150409** (but you said that project just created).
Thanks

**Comment by josevalim** [comment]
Please properly fill in all the issue template information when opening an issue. Also please include the contents of the generated migration file. Thank you.
