### ISSUE TITLE
Adding triggers to Ecto migration throws exception

### ISSUE THREAD

**Issue by bvjebin** [elixir-ecto/ecto#1740]
I am try to add a simple trigger to validate null constraint in two columns

The following is the ecto migration snippet I am trying.
```
defmodule AppServer.Repo.Migrations.AddEmailOrPhoneValidationTriggerToUsersTable do
  use Ecto.Migration

  def change do
    execute "CREATE TRIGGER InsertFieldemailPhoneNotNull BEFORE INSERT ON users
    FOR EACH ROW BEGIN
      IF (NEW.email IS NULL AND NEW.phone IS NULL) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Email and Phone cannot both be null';
      END IF;
    END;
    CREATE TRIGGER UpdateFieldemailPhoneNotNull BEFORE UPDATE ON users
      FOR EACH ROW BEGIN
        IF (NEW.email IS NULL AND NEW.phone IS NULL) THEN
          SIGNAL SQLSTATE '45000'
          SET MESSAGE_TEXT = 'Email and Phone cannot both be null';
        END IF;
      END;"
  end
end
```

On running the migration, it successfully creates the trigger in the database but throws exception which is causing the migration to fail registering itself in the schema_migrations table.

Following is the trace:
```
01:29:02.868 [info]  == Running AppServer.Repo.Migrations.AddEmailOrPhoneValidationTriggerToUsersTable.change/0 forward

01:29:02.869 [info]  execute "CREATE TRIGGER InsertFieldemailPhoneNotNull BEFORE INSERT ON users\n    FOR EACH ROW BEGIN\n      IF (NEW.email I
S NULL AND NEW.phone IS NULL) THEN\n        SIGNAL SQLSTATE '45000'\n        SET MESSAGE_TEXT = 'Email and Phone cannot both be null';\n      E
ND IF;\n    END;\n    CREATE TRIGGER UpdateFieldemailPhoneNotNull BEFORE UPDATE ON users\n      FOR EACH ROW BEGIN\n        IF (NEW.email IS NU
LL AND NEW.phone IS NULL) THEN\n          SIGNAL SQLSTATE '45000'\n          SET MESSAGE_TEXT = 'Email and Phone cannot both be null';\n
 END IF;\n      END;"

01:29:02.887 [info]  == Migrated in 0.1s
** (MatchError) no match of right hand side value: <<0, 0, 0, 2, 0, 0, 0>>
    (mariaex) lib/mariaex/messages.ex:150: Mariaex.Messages.decode_stmt_prepare_ok/1
    (mariaex) lib/mariaex/messages.ex:209: Mariaex.Messages.decode/2
    (mariaex) lib/mariaex/protocol.ex:610: Mariaex.Protocol.msg_recv/3
    (mariaex) lib/mariaex/protocol.ex:324: Mariaex.Protocol.prepare_recv/2
    (db_connection) lib/db_connection.ex:750: DBConnection.handle/4
    (db_connection) lib/db_connection.ex:847: anonymous fn/4 in DBConnection.run_prepare_execute/4
    (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:921: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
    (mariaex) lib/mariaex.ex:142: Mariaex.query/4
    (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:259: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6

    (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:487: Ecto.Adapters.SQL.model/6
    (ecto) lib/ecto/repo/schema.ex:297: Ecto.Repo.Schema.apply/5
    (ecto) lib/ecto/repo/schema.ex:81: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.Schema.insert!/4
    (ecto) lib/ecto/migrator.ex:226: anonymous fn/4 in Ecto.Migrator.migrate/4

01:29:02.931 [error] GenServer #PID<0.183.0> terminating
** (DBConnection.ConnectionError) client #PID<0.69.0> stopped: ** (MatchError) no match of right hand side value: <<0, 0, 0, 2, 0, 0, 0>>
    (mariaex) lib/mariaex/messages.ex:150: Mariaex.Messages.decode_stmt_prepare_ok/1
    (mariaex) lib/mariaex/messages.ex:209: Mariaex.Messages.decode/2
    (mariaex) lib/mariaex/protocol.ex:610: Mariaex.Protocol.msg_recv/3
    (mariaex) lib/mariaex/protocol.ex:324: Mariaex.Protocol.prepare_recv/2
    (db_connection) lib/db_connection.ex:750: DBConnection.handle/4
    (db_connection) lib/db_connection.ex:847: anonymous fn/4 in DBConnection.run_prepare_execute/4
    (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:921: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
    (mariaex) lib/mariaex.ex:142: Mariaex.query/4
    (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:259: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4

    (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6
    (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:487: Ecto.Adapters.SQL.model/6
    (ecto) lib/ecto/repo/schema.ex:297: Ecto.Repo.Schema.apply/5
    (ecto) lib/ecto/repo/schema.ex:81: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.Schema.insert!/4
(ecto) lib/ecto/migrator.ex:226: anonymous fn/4 in Ecto.Migrator.migrate/4

    (db_connection) lib/db_connection/connection.ex:243: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:stop, #Reference<0.0.4.2572>, %DBConnection.ConnectionError{message: "client #PID<0.69.0> stopped: ** (MatchErro
r) no match of right hand side value: <<0, 0, 0, 2, 0, 0, 0>>\n    (mariaex) lib/mariaex/messages.ex:150: Mariaex.Messages.decode_stmt_prepare_
ok/1\n    (mariaex) lib/mariaex/messages.ex:209: Mariaex.Messages.decode/2\n    (mariaex) lib/mariaex/protocol.ex:610: Mariaex.Protocol.msg_rec
v/3\n    (mariaex) lib/mariaex/protocol.ex:324: Mariaex.Protocol.prepare_recv/2\n    (db_connection) lib/db_connection.ex:750: DBConnection.han
dle/4\n    (db_connection) lib/db_connection.ex:847: anonymous fn/4 in DBConnection.run_prepare_execute/4\n    (db_connection) lib/db_connectio
n.ex:987: DBConnection.run_begin/3\n    (db_connection) lib/db_connection.ex:921: DBConnection.run_meter/3\n    (db_connection) lib/db_connecti
on.ex:463: DBConnection.prepare_execute/4\n    (mariaex) lib/mariaex.ex:142: Mariaex.query/4\n    (ecto) lib/ecto/adapters/mysql/connection.ex:
25: Ecto.Adapters.MySQL.Connection.query/4\n    (ecto) lib/ecto/adapters/sql.ex:259: Ecto.Adapters.SQL.query/7\n    (ecto) lib/ecto/pool.ex:159
: Ecto.Pool.do_run/4\n    (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6\n    (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapter
s.SQL.query/5\n    (ecto) lib/ecto/adapters/sql.ex:487: Ecto.Adapters.SQL.model/6\n    (ecto) lib/ecto/repo/schema.ex:297: Ecto.Repo.Schema.app

ly/5\n    (ecto) lib/ecto/repo/schema.ex:81: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4\n    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.
Schema.insert!/4\n    (ecto) lib/ecto/migrator.ex:226: anonymous fn/4 in Ecto.Migrator.migrate/4\n"}, %Mariaex.Protocol{binary_as: :field_type_
var_string, buffer: "", cache: 106534, catch_eof: false, connection_id: #PID<0.183.0>, connection_ref: #Reference<0.0.4.2272>, lru_cache: {100,
 110631}, opts: [socket_options: [], sock_type: :tcp, cache_size: 100, timeout: 5000, otp_app: :app_server, repo: AppServer.Repo, adapter: Ecto
.Adapters.MySQL, username: "root", password: "admin", database: "app_server_dev", hostname: "localhost", port: 3306], protocol57: false, rows:
[], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.5773>}, ssl_conn_state: :not_used, state: :running, state_data: {0, 0}, timeout: 5000}}}
State: {Mariaex.Protocol, %Mariaex.Protocol{binary_as: :field_type_var_string, buffer: "", cache: 106534, catch_eof: false, connection_id: #PID
<0.183.0>, connection_ref: #Reference<0.0.4.2272>, lru_cache: {100, 110631}, opts: [socket_options: [], sock_type: :tcp, cache_size: 100, timeo
ut: 5000, otp_app: :app_server, repo: AppServer.Repo, adapter: Ecto.Adapters.MySQL, username: "root", password: "admin", database: "app_server_
dev", hostname: "localhost", port: 3306], protocol57: false, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.5773>}, ssl_conn_state
: :not_used, state: :running, state_data: {0, 0}, timeout: 5000}}
```

What am I doing wrong?

### Environment

* Elixir version (elixir -v): Elixir 1.3.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): ```mysql  Ver 14.14 Distrib 5.6.22, for osx10.8 (x86_64) using  EditLine wrapper```
* Ecto version (mix deps): 
```
* ecto 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (ecto) a97d597d
* phoenix_ecto 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (phoenix_ecto) 1aff51d1
```
* Database adapter and version (mix deps): 
```
* mariaex 0.7.8 (Hex package) (mix)
  locked at 0.7.8 (mariaex) 77bcc9e8
```
* Operating system: Mac El Capitan

**Comment by ericmj** [comment]
Looks like you should open this issue on mariaex.

**Comment by bvjebin** [comment]
Thanks @ericmj. I will link this issue there. https://github.com/xerions/mariaex/issues/141
