### ISSUE TITLE
Ecto 2.1 broken migrations with :datetime

### ISSUE THREAD

**Issue by KernelMadness** [elixir-ecto/ecto#1870]
After upgrading to Ecto 2.1 old migrations with :datetime are broken.
As i can see in https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L80 :datetime is not deprecated, but wiped out from types

### Environment

- Elixir 1.3.4
- (PostgreSQL) 9.5.5
- ecto 2.1.0
- postgrex 0.13.0
- Ubuntu 16.04

### Current behavior

```
10:35:26.143 [info]  == Running Backoffice.Repo.Migrations.AddDeletedAtToPayment.change/0 forward
warning: the :datetime type in migrations is deprecated, please use :utc_datetime or :naive_datetime instead
 (ecto) lib/ecto/migration.ex:785: Ecto.Migration.validate_type!/1
 (ecto) lib/ecto/migration.ex:609: Ecto.Migration.add/3
 _build/dev/lib/backoffice/priv/repo/migrations/20161209110347_add_deleted_at_to_payment.exs:6: Backoffice.Repo.Migrations.AddDeletedAtToPayment.change/0
 (stdlib) timer.erl:197: :timer.tc/3
 (ecto) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6


10:35:26.148 [info]  alter table payments
** (Postgrex.Error) ERROR 42704 (undefined_object): type "datetime" does not exist
   (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
   (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
   (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
   (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
   (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
   (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
   (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
   (stdlib) timer.erl:181: :timer.tc/2
   (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
   (ecto) lib/ecto/migrator.ex:121: Ecto.Migrator.attempt/6
   (ecto) lib/ecto/migrator.ex:71: anonymous fn/4 in Ecto.Migrator.do_up/4
   (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
   (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
   (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
   (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
   (ecto) lib/ecto/migrator.ex:244: anonymous fn/4 in Ecto.Migrator.migrate/4
   (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
   (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
   (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
   (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
```

### Expected behavior

Migrations should run with deprecation warnings

**Comment by brunozrk** [comment]
For `modify` method in migration, it stills not working:

** (Postgrex.Error) ERROR 42704 (undefined_object): type "datetime" does not exist

**Comment by michalmuskala** [comment]
@brunozrk fixed in master.

**Comment by josevalim** [comment]
@michalmuskala I will backport it to 2.1 and do a new release, ok?

**Comment by michalmuskala** [comment]
Sounds great.

I'm sorry, @brunozrk. I didn't notice you offered to contribute until now - I skimmed the message too quickly 😢 .

**Comment by brunozrk** [comment]
thx @michalmuskala, no problem! :smile:

**Comment by brainlid** [comment]
For the benefit of others:

It is worth noting that the "backward compatible" choice is to use `:naive_datetime`. Since many would otherwise think it is `:utc_datetime`. 

See here...

https://github.com/elixir-ecto/ecto/commit/ef60906306e98d63ef21630ef67d1ff82d0d03ac#diff-dda93a2081b2f4ce69b1baf265611d8cR613

**Comment by josevalim** [comment]
@brainlid At the migration level they are equivalent for the supported databases.
