### ISSUE TITLE
Ecto.Query.API map/2 : error when association field is nil

### ISSUE THREAD

**Issue by Moxide** [elixir-ecto/ecto#1903]
Hello,
Following a discussion on IRC, I file an issue ;-)

### Environment

* Elixir version 1.4:
* Database PostgreSQL 9.5:
* Ecto version 2.1.2:

From the Ecto docs :
[https://hexdocs.pm/ecto/Ecto.Query.API.html#map/2](https://hexdocs.pm/ecto/Ecto.Query.API.html#map/2)

About the last example :
```
from(city in City, preload: :country,
     select: map(city, [:country_id, :name, country: [:id, :population]]))
```
If  ```country``` is an optional association, ```country_id``` may be nil.

### Current behavior in this case

 This error is thrown :
```
[error] an exception was raised:
    ** (BadMapError) expected a map, got: nil                                                                  
        (stdlib) :maps.find(:id, nil)                                                                          
        (elixir) lib/map.ex:234: Map.fetch!/2                                                                  
        (ecto) lib/ecto/repo/queryable.ex:306: anonymous fn/3 in Ecto.Repo.Queryable.to_map/2                  
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3                                         
        (ecto) lib/ecto/repo/queryable.ex:305: anonymous fn/3 in Ecto.Repo.Queryable.to_map/2                  
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3                                         
        (ecto) lib/ecto/repo/queryable.ex:243: Ecto.Repo.Queryable.transform_row/4                             
        (ecto) lib/ecto/repo/queryable.ex:238: Ecto.Repo.Queryable.postprocess/4                               
        (ecto) lib/ecto/repo/preloader.ex:28: Ecto.Repo.Preloader.unextract/3                                  
        (ecto) lib/ecto/repo/queryable.ex:136: Ecto.Repo.Queryable.execute/5                                   
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4  
```
### Expected behavior

I would expect a map with no ```country``` key or an empty ```country``` value.

Thanks ;-)

**Comment by michalmuskala** [comment]
We need to either return `nil`, as suggested (which would be consistent with structs) or raise a more helpful message.

**Comment by Moxide** [comment]
Just tried a fix that seems to give the expected behavior (well, expected by me, at least ;-))
If ```country_id``` is nil, we get :
```
%{country_id: nil, country: nil}
```
