### ISSUE TITLE
Improve error when loading schema_migrations table fails

### ISSUE THREAD

**Issue by ckruse** [elixir-ecto/ecto#1973]
### Environment

* Elixir version (elixir -v):
~~~
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
~~~
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
  PostgreSQL 9.6.2
* Ecto version (mix deps):
  ecto 2.1.3 (Hex package) (mix)
  locked at 2.1.3 (ecto) ffb24e15
* Database adapter and version (mix deps):
  postgrex 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (postgrex) ebf17b73
* Operating system:
  macOS 10.12.3

### Current behavior

When running `mix test` in my freshly generated Phoenix application I get the following stack trace:

~~~
** (ArgumentError) cannot load `"101"` as type :integer
    (ecto) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.load!/3
    (ecto) lib/ecto/adapters/sql.ex:584: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
    (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/adapters/sql.ex:577: Ecto.Adapters.SQL.process_row/3
    (postgrex) lib/postgrex/query.ex:77: DBConnection.Query.Postgrex.Query.decode_map/3
    (postgrex) lib/postgrex/query.ex:64: DBConnection.Query.Postgrex.Query.decode/3
    (db_connection) lib/db_connection.ex:1010: DBConnection.decode/6
    (ecto) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.prepare_execute/5
~~~

According to [this thread](https://github.com/phoenixframework/phoenix/issues/1556#issuecomment-283466689) it is a problem with the data type of an existing `schema_migrations` table: `version` should be integer but is a `character varying`.

### Expected behavior

While the solution is trivial it would really be nice to have a meaningful error message; at least the schema in question should be mentioned.

**Comment by ckruse** [comment]
Thanks a lot!
