### ISSUE TITLE
:ets.lookup_element failures

### ISSUE THREAD

**Issue by mspanc** [elixir-ecto/ecto#2042]
### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): 2.1.1
* Database adapter and version (mix deps): phoenix_ecto 3.2.1
* Operating system: ubuntu 14.04 a'la heroku container (dokku 0.8.0)

### Current behavior

Include code samples, errors and stacktraces if appropriate.

My app under high load tends to throw such errors in the logs. Unfortunately I haven't found a pattern yet

```
2017-04-25T12:29:58.762018187Z app[web.1]: 
2017-04-25T12:29:58.763663846Z app[web.1]: 12:29:58.763 request_id=p7hfpvi9k0eeufob8iq9253aako1guhv [warn]     (stdlib) :ets.lookup_element(684217, "ecto_903", 2)
2017-04-25T12:29:58.763682416Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:2185: Postgrex.Protocol.query_prepare/2
2017-04-25T12:29:58.763690852Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:991: Postgrex.Protocol.execute/2
2017-04-25T12:29:58.763697663Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:194: Postgrex.Protocol.handle_execute/4
2017-04-25T12:29:58.763703921Z app[web.1]:     (db_connection) lib/db_connection.ex:957: DBConnection.handle/4
2017-04-25T12:29:58.763709804Z app[web.1]:     (db_connection) lib/db_connection.ex:1099: anonymous fn/4 in DBConnection.run_execute/4
2017-04-25T12:29:58.763716021Z app[web.1]:     (db_connection) lib/db_connection.ex:1141: anonymous fn/4 in DBConnection.run_meter/5
2017-04-25T12:29:58.763723347Z app[web.1]:     (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
2017-04-25T12:29:58.763729816Z app[web.1]: 
2017-04-25T12:29:58.766168496Z app[web.1]: 12:29:58.765 request_id=p7hfpvi9k0eeufob8iq9253aako1guhv [warn]     (stdlib) :ets.lookup_element(684217, "ecto_903", 2)
2017-04-25T12:29:58.766189957Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:2185: Postgrex.Protocol.query_prepare/2
2017-04-25T12:29:58.766198697Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:991: Postgrex.Protocol.execute/2
2017-04-25T12:29:58.766205774Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:194: Postgrex.Protocol.handle_execute/4
2017-04-25T12:29:58.766218024Z app[web.1]:     (db_connection) lib/db_connection.ex:957: DBConnection.handle/4
2017-04-25T12:29:58.766226541Z app[web.1]:     (db_connection) lib/db_connection.ex:1099: anonymous fn/4 in DBConnection.run_execute/4
2017-04-25T12:29:58.766242078Z app[web.1]:     (db_connection) lib/db_connection.ex:1141: anonymous fn/4 in DBConnection.run_meter/5
2017-04-25T12:29:58.766249876Z app[web.1]:     (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
2017-04-25T12:29:58.766256990Z app[web.1]: 
2017-04-25T12:29:58.769585984Z app[web.1]: 12:29:58.769 request_id=p7hfpvi9k0eeufob8iq9253aako1guhv [warn]     (stdlib) :ets.lookup_element(684217, "ecto_903", 2)
2017-04-25T12:29:58.769655117Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:2185: Postgrex.Protocol.query_prepare/2
2017-04-25T12:29:58.769666455Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:991: Postgrex.Protocol.execute/2
2017-04-25T12:29:58.769674042Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:194: Postgrex.Protocol.handle_execute/4
2017-04-25T12:29:58.769680580Z app[web.1]:     (db_connection) lib/db_connection.ex:957: DBConnection.handle/4
2017-04-25T12:29:58.769687608Z app[web.1]:     (db_connection) lib/db_connection.ex:1099: anonymous fn/4 in DBConnection.run_execute/4
2017-04-25T12:29:58.769695181Z app[web.1]:     (db_connection) lib/db_connection.ex:1141: anonymous fn/4 in DBConnection.run_meter/5
2017-04-25T12:29:58.769702138Z app[web.1]:     (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
2017-04-25T12:29:58.769709117Z app[web.1]: 
2017-04-25T12:29:58.771524982Z app[web.1]: 12:29:58.771 request_id=p7hfpvi9k0eeufob8iq9253aako1guhv [warn]     (stdlib) :ets.lookup_element(684217, "ecto_903", 2)
2017-04-25T12:29:58.771555229Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:2185: Postgrex.Protocol.query_prepare/2
2017-04-25T12:29:58.771565805Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:991: Postgrex.Protocol.execute/2
2017-04-25T12:29:58.771574287Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:194: Postgrex.Protocol.handle_execute/4
2017-04-25T12:29:58.771581111Z app[web.1]:     (db_connection) lib/db_connection.ex:957: DBConnection.handle/4
2017-04-25T12:29:58.771587545Z app[web.1]:     (db_connection) lib/db_connection.ex:1099: anonymous fn/4 in DBConnection.run_execute/4
2017-04-25T12:29:58.771593638Z app[web.1]:     (db_connection) lib/db_connection.ex:1141: anonymous fn/4 in DBConnection.run_meter/5
2017-04-25T12:29:58.771599728Z app[web.1]:     (db_connection) lib/db_connection.ex:636: DBConnection.execute/4

```

### Expected behavior

No errors, no crashed queries.

**Comment by ericmj** [comment]
Only the stacktrace is included in the included logs, you don't happen to have the exception and message also?

**Comment by fishcakez** [comment]
This stacktrace points to a call that gets rescued, and generating an exception and rescuing to set the stacktrace is expected behaviour here. It seems like something is incorrectly picking up this stacktrace and logging it.

**Comment by mspanc** [comment]
I'll reply as soon as I will get more information.

**Comment by mspanc** [comment]
You were right, my fault.
