### ISSUE TITLE
update_all using `variable in "TABLE_NAME"` queryable does not use alias in SET

### ISSUE THREAD

**Issue by KronicDeth** [elixir-ecto/ecto#2119]
### Environment

* Elixir version (elixir -v): 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): `postgrex` `0.13.3`
* Operating system: macOS 10.12.5

### Current behavior

Updating a table using `variable in "TABLE_NAME"` as first argument to `Ecto.Query.from/2` aliases the table name in the `UPDATE`, but not in the `SET`:

```elixir
Ecto.Query.from(
      agency_invoices in "agency_invoices",
      update: [
        set: [
          reference_code: fragment(
            "'AI-' || ? || '-' || to_char(COALESCE(?, ?), 'YYYYMMDD')",
            agency_invoices.partner_short_identifier,
            agency_invoices.invoice_date,
            agency_invoices.created_at
          )
        ]
      ]
    )
    |> Lighthouse.Repo.update_all([])
```

```sql
UPDATE "agency_invoices" AS a0 SET "identifier" = to_char(agency_invoices.created_at, 'YYYYMMDD') || '-' || agency_invoices.partner_short_identifier || '-' || agency_invoices.id
```

```
** (Postgrex.Error) ERROR 42P01 (undefined_table): invalid reference to FROM-clause entry for table "agency_invoices"
    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_and_cache/7
    (stdlib) timer.erl:197: :timer.tc/3
    (ecto) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:127: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
```

### Expected behavior

Usage of `agency_invoices` in `fragment` arguments becomes `a0` when converted to SQL:

```sql
UPDATE "agency_invoices" AS a0 SET "identifier" = to_char(a0.created_at, 'YYYYMMDD') || '-' || a0.partner_short_identifier || '-' || a0.id
```

### Work-around

Use anticipated aliased name in `fragment` instead of `?` (and feel dirty about it):

```elixir
Ecto.Query.from(
      agency_invoices in "agency_invoices",
      update: [
        set: [
          reference_code: fragment(
            "'AI-' || a0.partner_short_identifier || '-' || to_char(COALESCE(a0.invoice_date, a0.created_at), 'YYYYMMDD')"
          )
        ]
      ]
    )
    |> Lighthouse.Repo.update_all([])
```

**Comment by alexanderadam** [comment]
Sooo, I'm running into this issue right now and I'd like to have this feature as well.

However, this ticket was closed. May I ask why? 🤔

**Comment by greg-rychlewski** [comment]
It should work...which version of Ecto are you using? If I run this test on the main branch:

```elixir
q = from p in Post, update: [set: [visits: fragment("?", p.counter)]]
TestRepo.update_all(q, [], log: :error)
```

I get the query

```sql
UPDATE "posts" AS p0 SET "visits" = p0."counter"
```

**Comment by alexanderadam** [comment]
Sorry, I missed to add this information: in my case this is about `many_to_many` relations:

```elixir
many_to_many(
  :bananas,
  Foo.Bar.Banana,
  join_through: Foo.Bar.Bananabasket,
  join_where: [foo_id: {:fragment, "? = bananabasket.foo_id"}],
  join_keys: [
    id: :bananabasket_id,
    banana_id: :banana_id
  ]
)
```
