### ISSUE TITLE
no match of right hand side value on Ecto.Changeset.put_relation

### ISSUE THREAD

**Issue by yordis** [elixir-ecto/ecto#2138]
### Environment

* Elixir version (elixir -v)
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir  #1.4.5
```

* Ecto version (mix deps):
```
ecto 2.1.4 (Hex package) (mix)
```
* Database adapter and version (mix deps):
```
postgrex 0.13.3 (Hex package) (mix)
```
* Operating system: Mac

#### Error
```
1) test add permission to role (StrawHatIAMTest.RoleTest)
     test/straw_hat_iam/role_test.exs:22
     ** (MatchError) no match of right hand side value: %StrawHat.IAM.Schema.RolePermission{__meta__: #Ecto.Schema.Metadata<:built, "role_permissions">, id: nil, permission: #Ecto.Association.NotLoaded<association :permission is not loaded>, permission_id: nil, role: #Ecto.Association.NotLoaded<association :role is not loaded>, role_id: nil}
     stacktrace:
       (ecto) lib/ecto/changeset.ex:1078: Ecto.Changeset.put_relation/5
       (straw_hat_iam) lib/straw_hat_iam/schema/role_permission.ex:13: StrawHat.IAM.Schema.RolePermission.changeset/3
       (straw_hat_iam) lib/straw_hat_iam/role.ex:30: StrawHat.IAM.Role.add_permission/2
       test/straw_hat_iam/role_test.exs:26: (test)
```
```elixir
  test "add permission to role" do
    permission = insert(:permission)
    role = insert(:role)

    assert {:ok, _permission_role} = Role.add_permission(role, permission)
  end

  def add_permission(%Role{} = role, %Permission{} = permission) do
    %RolePermission{}
    |> RolePermission.changeset(role, permission)
    |> Repo.insert()
  end

defmodule StrawHat.IAM.Schema.RolePermission do
  use Ecto.Schema
  import Ecto.Changeset
  alias StrawHat.IAM.Schema.{ Role, Permission }

  schema "role_permissions" do
    belongs_to(:role, Role)
    belongs_to(:permission, Permission)
  end

  def changeset(role_permission, role, permission) do
    role_permission
    |> put_assoc(:role, role) # <--- Followed the documentation
    |> put_assoc(:permission, permission)
  end
end

```

### Expected behavior

It should add the association to the schema without failing

**Comment by josevalim** [comment]
The first argument of put_assoc must be a changeset, you are passing a schema. I will make sure to have a clearer error message.

**Comment by yordis** [comment]
@josevalim so there is not need of validating after the `put_assoc` then, or I shouldn't be validating anything related to that.
