### ISSUE TITLE
Ecto.Changeset.traverse_errors/2 doesn't work with embeds if there is a constraint error

### ISSUE THREAD

**Issue by asd1o2487c** [elixir-ecto/ecto#2221]
### To reproduce

https://github.com/asd1o2487c/ecto_bug

run `EctoBug.bug` twice

### Environment

* Elixir version (elixir -v): 1.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): ~> 2.2
* Database adapter and version (mix deps): >= 0.0.0
* Operating system: macOS

### Current behavior

```elixir
# after running EctoBug.bug once to create an item with name "already_exists"

iex(2)> EctoBug.bug

[debug] QUERY OK db=0.3ms
begin []

[debug] QUERY OK db=1.9ms
INSERT INTO "users" ("data","username") VALUES ($1,$2) RETURNING "id" [%{city: "england", id: "d3c08dd0-e416-4124-a164-0ad06d1e425b"}, "something"]

[debug] QUERY ERROR db=6.1ms
INSERT INTO "items" ("name","user_id") VALUES ($1,$2) RETURNING "id" ["already_exists", 2]

[debug] QUERY OK db=0.3ms
rollback []
** (FunctionClauseError) no function clause matching in Ecto.Changeset.traverse_errors/2

    The following arguments were given to Ecto.Changeset.traverse_errors/2:

        # 1
        %EctoBug.User.Data{city: "england", id: "d3c08dd0-e416-4124-a164-0ad06d1e425b"}

        # 2
        #Function<0.31324691/1 in EctoBug.traverse_errors/1>

    Attempted function clauses (showing 1 out of 1):

        def traverse_errors(%Ecto.Changeset{errors: errors, changes: changes, types: types} = changeset, msg_func) when is_function(msg_func, 1) or is_function(msg_func, 3)

    (ecto) lib/ecto/changeset.ex:2321: Ecto.Changeset.traverse_errors/2
    (ecto) lib/ecto/changeset.ex:2365: anonymous fn/4 in Ecto.Changeset.merge_related_keys/4
    (stdlib) lists.erl:1263: :lists.foldl/3
```

### Expected behavior
Embeds stay wrapped in changeset structs, so that `traverse_errors` works on them too.

**Comment by asd1o2487c** [comment]
Changeset before `Repo.insert()`
```elixir
#Ecto.Changeset<action: nil,
 changes: %{data: #Ecto.Changeset<action: :insert, changes: %{city: "england"},
    errors: [], data: #EctoBug.User.Data<>, valid?: true>,
   items: [#Ecto.Changeset<action: :insert, changes: %{name: "already_exists"},
     errors: [], data: #EctoBug.Item<>, valid?: true>], username: "something"},
 errors: [], data: #EctoBug.User<>, valid?: true>
```
after
```elixir
#Ecto.Changeset<action: :insert,
  changes: %{data: %EctoBug.User.Data{city: "england",
     id: "7bd4ae4c-7d93-463e-adf8-f7ca8a995885"},
    items: [#Ecto.Changeset<action: :insert,
      changes: %{name: "already_exists", user_id: nil},
      errors: [name: {"has already been taken", []}], data: #EctoBug.Item<>,
      valid?: false>], username: "something"}, errors: [],
  data: #EctoBug.User<>, valid?: false>
```

**Comment by josevalim** [comment]
I believe the error is because you have two relationships and we are merging different "versions" of it, one that succeeded and another one that failed. More info soon.
