### ISSUE TITLE
ecto.setup / ecto.migrate fail attempting to use config.exs logger

### ISSUE THREAD

**Issue by kemper** [elixir-ecto/ecto#2225]
### Environment

* Elixir version: Elixir 1.4.1
* Database and version: mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64)
* Ecto version (mix deps): 2.2.1
* Database adapter and version: mariaex 0.8.3
* Operating system: Ubuntu 14.04 (running in Vagrant)

Since this is a migration related issue, it's worth noting that we migrate with MIX_ENV=prod

### Current behavior

Recently, we updated our version of ecto in one of our elixir apps from "2.1.4" to "2.2.1". The ecto.setup (or others, like ecto.migrate and ecto.rollback) began failing because they attempted to use the config.exs logger (a loggly logger in our case).

Example error:

```zsh
mix ecto.setup
The database for SomeApplication.Repo has already been created
[22m14:25:57.270 [info] == Running SomeApplication.Repo.Migrations.AddColumnsToTable.change/0 forward
[0m[22m14:25:57.270 [info] alter table some_table
[0m[31m14:25:57.343 [error] :gen_event handler {LoggerLogglyBackend, :loggly} installed at Logger
** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.239.0>, #Reference<0.0.1.3066>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_tcp, 'logs-01.loggly.com', 80, "logs-01.loggly.com", [connect_timeout: 5000], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, {0, {:dict, 0, 16, 16, 8, 80, 48, {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}, {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}}, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)

```
We have several test environments and observed slightly different results. 

Afterwards, the alter table statement may or may not have run against the database. If the alter statement did execute, the entry in the schema_migrations table won't get inserted, and the mix ecto.setup command will fail.

The error above will be generated several times. My guess is for each attempt at logging some piece of information.

### Expected behavior

The mix ecto.setup command will succeed, the alter statement will run against the database, and the entry will be written to the schema_migrations table.

### Reference

This appears to be related to issue #2038

**Comment by josevalim** [comment]
Thanks @kemper. Since we do not start the app and all of its dependencies, hackney is not started which causes logging to fail. You can fix this in your app for now by doing this:

```elixir
def project do
  [aliases: ["ecto.setup": [&start_loggly/1, "ecto.setup"]]
end

defp start_loggly(_) do
  Application.ensure_all_started(:name_of_the_dep_that_adds_loggly_to_logger)
end
```

I am not sure how to solve this in the long term though. One option would be to ask the handler to make sure its dependencies are started on init. It may make sense since the handler is typically added externally, via configuration files, and not as part of its parent app supervision tree.

**Comment by kemper** [comment]
Thanks for the fast reply! In the short term we specified the older version of ecto in our mixfile.

I mostly wanted to get this on your radar; from my interpretation of issue #2038 it seemed like you might know this was the tradeoff with the fix for that issue, but the behavior appears defective for anyone who uses a custom logging backend like I do.

I tried your suggestion, but I couldn't get it to work. I tried to load my own app. I also tried to load some of the dependencies directly using ensure_all_started (hackney, httpoison, etc), but got an error.

With this code:

```
defp aliases do
  ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
   "ecto.migrate": [&start_loggly/1, "ecto.migrate"],
   "ecto.rollback": [&start_loggly/1, "ecto.rollback"],
   "ecto.reset": ["ecto.drop", "ecto.setup"],
   "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
end

defp start_loggly(_) do
  {:ok, _} = Application.ensure_all_started(:my_application)
end
```
I get this result:

```
% mix ecto.rollback

** (MatchError) no match of right hand side value: {:error, {:hackney, {'no such file or directory', 'my_application.app'}}}
    mix.exs:77: MyApp.Mixfile.start_loggly/1
    (mix) lib/mix/task.ex:337: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:265: Mix.Task.run/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```
For contrast ensure_all_started works from iex:

```
% iex -S mix run --no-start

iex(3)> {:ok, _} = Application.ensure_all_started(:my_application)
{:ok, []}
```
After playing around a bit and not getting past this, I re-read issue #2038 and tried something mentioned there. I changed my aliases in the app to use "app.start" and then everything appears to work:

```
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.migrate": ["app.start", "ecto.migrate"],
     "ecto.rollback": ["app.start", "ecto.rollback"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
```

In the case of my application, I don't see a detriment to starting the full application since it's a fairly simple api application, though you didn't appear to like that as an option in #2038 . I can imagine in some applications it would have unexpected side effects.

There is something different about using ensure_all_started in the mix.exs aliases list that i don't understand.

If you have any more feedback, I'd appreciate it. I don't have any thoughts on how this could be solved; you certainly would know better than I would. Let me know if you'd like to me try anything else and I'll give it a shot!

**Comment by josevalim** [comment]
Try this implementation of start_loggly  please:

```elixir
defp start_loggly(args) do
  Mix.Project.compile(args)
  {:ok, _} = Application.ensure_all_started(:my_application)
end
```

**Comment by kemper** [comment]
Thanks! That helped. This is the minimal set of dependencies I found that results in a clean migration run:

```elixir
  defp start_loggly(args) do
    Mix.Project.compile(args)
    apps = [:phoenix_ecto, :logger_loggly_backend]
    Enum.each(apps, fn(app) -> {:ok, _} = Application.ensure_all_started(app) end)
  end
```
I don't see what the relationship is between phoenix_ecto and logger_loggly_backend are. Without phoenix_ecto I get:

```zsh
[error] :gen_event handler {LoggerLogglyBackend, :loggly} installed at Logger
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in LoggerLogglyBackend.handle_event/2
        (logger_loggly_backend) lib/logger_loggly_backend.ex:17: LoggerLogglyBackend.handle_event(:flush, %{format: [:time, " ", :metadata, "[", :level, "] ", :message, "\n"], level: :info, metadata: [:request_id], name: :loggly, tags: [nil], timeout: 5000, url: "http://logs-01.loggly.com/inputs//tag/"})
        (stdlib) gen_event.erl:533: :gen_event.server_update/4
```
I see that the logger_loggly_backend has a handle_event function but it also includes GenEvent which the docs say is deprecated, so perhaps the age of the logger_loggly_backend library is an issue there.

**Comment by josevalim** [comment]
This pull request should do it: https://github.com/joeyfeldberg/loggly_backend/pull/3 Let me know if it works!

**Comment by kemper** [comment]
I tried that change in the PR. It hangs when it gets to the ensure_all_started. I added a trace call for some extra output:

```elixir
  def init({__MODULE__, name}) do
    :sys.trace self(), true
    {:ok, _} = Application.ensure_all_started(:logger_loggly_backend)
    {:ok, configure(name, [])}
  end
```

Which results in 

```zsh
% iex -S mix

==> logger_loggly_backend                                                                                                                                                                                                     [64/9424]
Compiling 1 file (.ex)
*DBG* 'Elixir.Logger' got {#Ref<0.0.1.3265>,ok}
*DBG* 'Elixir.Logger' got {'EXIT',<0.378.0>,
                           {{case_clause,
                             {'EXIT',{timeout,{sys,trace,[<0.375.0>,true]}}}},
                            [{'Elixir.Logger.Watcher',do_init,3,
                              [{file,"lib/logger/watcher.ex"},{line,78}]},
                             {gen_server,init_it,6,
                              [{file,"gen_server.erl"},{line,328}]},
                             {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,247}]}]}}
*DBG* 'Elixir.Logger' got {'EXIT',<0.376.0>,shutdown}

=INFO REPORT==== 19-Sep-2017::14:46:48 ===
    application: logger
    exited: {{shutdown,
              {failed_to_start_child,'Elixir.Logger.Watcher',
               {'EXIT',
                {{badmatch,
                  {error,
                   {{{case_clause,
                      {'EXIT',{timeout,{sys,trace,[<0.375.0>,true]}}}},
                     [{'Elixir.Logger.Watcher',do_init,3,
                       [{file,"lib/logger/watcher.ex"},{line,78}]},
                      {gen_server,init_it,6,
                       [{file,"gen_server.erl"},{line,328}]},
                      {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]},
                    {child,undefined,
                     {'Elixir.Logger.Watcher',
                      {'Elixir.Logger',{'Elixir.LoggerLogglyBackend',loggly}}},
                     {'Elixir.Logger.Watcher',watcher,
                      ['Elixir.Logger',
                       {'Elixir.LoggerLogglyBackend',loggly},
                       {'Elixir.LoggerLogglyBackend',loggly}]},
                     transient,5000,worker,
                     ['Elixir.Logger.Watcher']}}}},
                 [{'Elixir.Logger.Watcher','-start_link/3-fun-0-',2,
                   [{file,"lib/logger/watcher.ex"},{line,16}]},
                  {'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,
                   [{file,"lib/enum.ex"},{line,1755}]},
                  {'Elixir.Logger.Watcher',start_link,3,
                   [{file,"lib/logger/watcher.ex"},{line,15}]},
                  {supervisor,do_start_child,2,
                   [{file,"supervisor.erl"},{line,365}]},
                  {supervisor,start_children,3,
                   [{file,"supervisor.erl"},{line,348}]},
                  {supervisor,init_children,2,
                   [{file,"supervisor.erl"},{line,314}]},
                  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
                  {proc_lib,init_p_do_apply,3,
                   [{file,"proc_lib.erl"},{line,247}]}]}}}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary

==> my_application
** (Mix) Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.Watcher
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {{{:case_clause, {:EXIT, {:timeout, {:sys, :trace, [#PID<0.375.0>, true]}}}}, [{Logger.Watcher, :do_init, 3, [file: 'lib/logger/watcher.ex', line: 78]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {:child, :undefined, {Logger.Watcher, {Logger, {LoggerLogglyBackend, :loggly}}}, {Logger.Watcher, :watcher, [Logger, {LoggerLogglyBackend, :loggly}, {LoggerLogglyBackend, :loggly}]}, :transient, 5000, :worker, [Logger.Watcher]}}}
            (logger) lib/logger/watcher.ex:16: anonymous fn/2 in Logger.Watcher.start_link/3
            (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
            (logger) lib/logger/watcher.ex:15: Logger.Watcher.start_link/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
@kemper since we add the backends when the application start we cannot call the application server, we are getting a deadlock. I will have to think a bit more about this issue.

**Comment by josevalim** [comment]
@kemper can you please try the v2.2 branch? I have pushed a potential fix.

**Comment by kemper** [comment]
Works great!

I updated my mix file. I cross checked my mix.lock against your most recent commit sha to be sure:

```
"ecto": {:git, "https://github.com/elixir-ecto/ecto.git", "6380dfd5d31d89c81e4a7526dd9d74ada790c01b", [branch: "v2.2"]}
```

I migrated from scratch and everything completed without error. Thanks!
