### ISSUE TITLE
Ecto unique uuid key constraint

### ISSUE THREAD

**Issue by mojidabckuu** [elixir-ecto/ecto#2337]
### Environment

* Elixir version (elixir -v): 1.5.1
* Database and version (PostgreSQL): 9.6.5
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps): 0.13.3
* Operating system: Mac os

### Current behavior
```
# Migration
create table(:posts, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :author_id, :integer, null: false
      add :text, :string
      add :readed_at, :datetime

      timestamps(updated_at: false)
end

# Model + UUID
defmodule  MediumClone.Post do
  use Ecto.Schema
  @primary_key {:id, Ecto.UUID, autogenerate: true}
  @derive {Phoenix.Param, key: :id}

  schema "posts" do
  ...
  end
end

# Changeset
struct
    |> cast(attributes, [:text, :id])
    |> validate_required(:text)
    |> validate_length(:text, min: 1)
    |> validate_length(:text, max: 1024)
    |> unique_constraint(:id, name: :posts_pkey)
```

Gives 

```
rollback []
** (DBConnection.ConnectionError) transaction rolling back
    (db_connection) lib/db_connection.ex:1523: DBConnection.fetch_info/1
    (db_connection) lib/db_connection.ex:738: DBConnection.run/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:98: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_or_reset/7
    (blog) lib/blog.ex:86: anonymous fn/3 in Blog.create_post/3
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (blog) lib/blog.ex:98: Blog.create_post/3
```

### Expected behavior

Receive Ecto errors.

**Comment by michalmuskala** [comment]
Could you show the code that tiggers the rollback? It's hard to tell what's going on without any code.

**Comment by mojidabckuu** [comment]
@michalmuskala I've located the issue. Was not obvious for me that the problem was in my code within `Multi`. On test using insert only works as expected. Please close the issue.

**Comment by mojidabckuu** [comment]
Hmmm
If I run multiple inserts inside `Multi` and the first one returns `:error` is it possible that then Ecto crashes? :)

**Comment by michalmuskala** [comment]
If some operation fails in a transaction, the only thing to do with the transaction is to roll it back - it's not limitation coming from ecto, but semantics of SQL transactions.
