### ISSUE TITLE
DBConnection.ConnectionError when running Ecto.Query from within Ecto.Multi

### ISSUE THREAD

**Issue by wfgilman** [elixir-ecto/ecto#2383]
### Environment

* Elixir version (elixir -v): 1.5.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.5.4
* Ecto version (mix deps): 2.2.8
* Database adapter and version (mix deps): 0.13.3
* Operating system: Mac Sierra

### Current behavior

I have a complex database transaction which creates an object supertype with two subtypes. Creating these records and respecting the database constraints requires two Ecto.Multi transactions. I'm getting a `** (DBConnection.ConnectionError) transaction rolling back` error when trying to run an Ecto.Query in the middle of the transaction. The workflow is as follows:

- Begin an Ecto.Multi to associate a User and Plan
- Create a Plan and corresponding subtype (Match or Fixed) in a separate Ecto.Multi
- If the Multi fails with an error identifying a unique constraint violation on the subtype, lookup the Plan in the database instead, otherwise create the Plan

The query that looks up an existing Plan generates the `** (DBConnection.ConnectionError) transaction rolling back` error. The Ecto.Query is valid, it is only when it is passed to `Repo.one/1` that it generates this error. The query runs on its own successfully, but fails when run within the Multi.

Below is how the operations are structured:
```
  params = %{"plan" => %{"frequency" => "monthly", "type" => "match", "limit" => 100}}

  @spec create(%{String.t => any}) :: {:ok, map} | {:error, atom, any, any}
  def create(%{"plan" => plan} = params) do
    Multi.new()
    |> Multi.run(:frequency, &get_frequency(&1, plan))
    |> Multi.run(:plan, &maybe_insert_plan(&1, plan))
    |> Multi.run(:user_sponsor_plan, &insert_user_sponsor_plan(&1, params["sponsorship_id"]))
    |> Multi.run(:user_sponsor_plan_schedule, &insert_user_sponsor_plan_schedule(&1, plan, params["schedule"]))
    |> Repo.transaction()
  end

  defp get_frequency(_multi, %{"frequency" => name}) do
    case Repo.get_by(Frequency, name: name) do
      nil ->
        {:error, add_error(%Ecto.Changeset{}, :frequency, "has an invalid value")}
      freq ->
        {:ok, freq}
    end
  end

  defp maybe_insert_plan(%{frequency: frequency}, params) do
    case insert_plan(params, frequency) do
      {:ok, %{plan: plan}} ->
        {:ok, plan}
      {:error, _, cs, _} ->
        # These two errors mean a plan already exists.
        if is_nil(cs.errors[:percentage_limit]) and is_nil(cs.errors[:uniq_amount]) do
          {:error, cs}
        else
          {:ok, lookup_plan(params)} # This is where the Multi fails with the DBConnection error.
        end
    end
  end

  defp insert_plan(params, frequency) do
    Multi.new()
    |> Multi.insert(:plan, %Plan{frequency: frequency})
    |> Multi.run(:match_plan, &maybe_insert_match_plan(&1, params))
    |> Multi.run(:fixed_plan, &maybe_insert_fixed_plan(&1, params))
    |> Repo.transaction()
  end

  # Fixed Plan
  defp maybe_insert_fixed_plan(_multi, %{"type" => "match"}), do: {:ok, nil}
  defp maybe_insert_fixed_plan(%{plan: plan}, %{"type" => "fixed"} = params) do
    %FixedPlan{}
    |> FixedPlan.changeset(plan, params)
    |> Repo.insert()
  end

  # Match plan
  defp maybe_insert_match_plan(_multi, %{"type" => "fixed"}), do: {:ok, nil}
  defp maybe_insert_match_plan(%{plan: plan}, %{"type" => "match"} = params) do
    %MatchPlan{}
    |> MatchPlan.changeset(plan, params)
    |> Repo.insert()
  end

  # This function returns correctly when run outside the Multi.
  defp lookup_plan(%{"type" => "fixed", "frequency" => freq, "amount" => amount}) do
    plan_query(freq)
    |> where([_p, _f, _mp, fp], fp.amount == type(^amount, :decimal))
    |> Repo.one()
  end
  defp lookup_plan(%{"type" => "match", "frequency" => freq, "limit" => limit}) do
    plan_query(freq)
    |> where([_p, _f, mp], mp.limit == type(^limit, :decimal))
    |> Repo.one()
  end

  defp plan_query(frequency) do
    from p in Plan,
      join: f in assoc(p, :frequency),
      left_join: mp in assoc(p, :match_plan),
      left_join: fp in assoc(p, :fixed_plan),
      where: f.name == ^frequency
  end

  # Remaining Multi functions excluded for brevity...
```

Stacktrace:
```
1) test sponsor_plan repo create/1 re-uses existing plan (Storage.Repo.Sponsor.PlanTest)
     test/lib/storage/repo/sponsor/plan_test.exs:50
     ** (DBConnection.ConnectionError) transaction rolling back
     code: assert {:ok, multi} = Plan.create(params)
     stacktrace:
       (db_connection) lib/db_connection.ex:1531: DBConnection.fetch_info/1
       (db_connection) lib/db_connection.ex:746: DBConnection.run/3
       (db_connection) lib/db_connection.ex:592: DBConnection.prepare_execute/4
       (ecto) lib/ecto/adapters/postgres/connection.ex:73: Ecto.Adapters.Postgres.Connection.prepare_execute/5
       (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
       (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
       (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
       (storage) lib/storage/repo/sponsor/plan.ex:41: Storage.Repo.Sponsor.Plan.maybe_insert_plan/2
       (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
       (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
       (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
       (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
       test/lib/storage/repo/sponsor/plan_test.exs:55: (test)
```

**Comment by josevalim** [comment]
The issue is that insert_plan is failing and that triggers the transaction to rollback. Any operation that you try to do after that, will fail, because the transaction is rolling back. In other words, consider that the transaction is in an invalid state.

There is nothing we can do here, you need to move the lookup for {:ok, plans} out of Multi in that case. Maybe return `{:ok, :lookup_plans}` and match on it after or return an anonymous function that is then invoked.

**Comment by wfgilman** [comment]
So the multi transaction will begin rolling back automatically if a child transaction fails? I thought I could pattern match on the result of the multi for `insert_plan` and take an alternative action within the `create` multi.

**Comment by josevalim** [comment]
It doesn't start rolling back just yet but once it fails the database will refuse further operations until it is rolled back.

**Comment by wfgilman** [comment]
Okay thanks for clarifying! 👍
