### ISSUE TITLE
Compiling ecto fails: (UndefinedFunctionError) function Ecto.Adapter.json_library/0 is undefined or private

### ISSUE THREAD

**Issue by jimekevin** [elixir-ecto/ecto#2384]
### Environment

* Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Elixir 1.5.3
* Dependencies:
  connection 1.0.4
  db_connection 1.1.3
  decimal 1.4.1
  ecto 2.2.8
  poolboy 1.5.1
  postgrex 0.13.3
* Operating system: Mac OSX 64-Bit, 10.13.1

### Current behavior

I download elixir with brew and tried to create a new project with mix. I then added Ecto to it and tried compiling the dependencies. Running `mix escript.build` (which includes `mix deps.compile ecto`) leads to the following error:

```
== Compilation error in file lib/ecto/adapters/postgres/connection.ex ==
** (UndefinedFunctionError) function Ecto.Adapter.json_library/0 is undefined or private
    Ecto.Adapter.json_library()
    lib/ecto/adapters/postgres/connection.ex:4: (file)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

There also are a lot of warnings:
```
Compiling 70 files (.ex)
warning: redefining module Ecto.Query.Builder.Lock (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.Builder.Lock.beam)
  lib/ecto/query/builder/lock.ex:3

warning: redefining module Mix.Tasks.Ecto.Drop (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Mix.Tasks.Ecto.Drop.beam)
  lib/mix/tasks/ecto.drop.ex:1

warning: redefining module Ecto.Repo (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Repo.beam)
  lib/ecto/repo.ex:1

warning: redefining module Ecto.Repo.Queryable (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Repo.Queryable.beam)
  lib/ecto/repo/queryable.ex:1

warning: redefining module Ecto.Query.Builder.Filter (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.Builder.Filter.beam)
  lib/ecto/query/builder/filter.ex:3

warning: redefining module Ecto.Repo.Preloader (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Repo.Preloader.beam)
  lib/ecto/repo/preloader.ex:1

warning: redefining module Inspect.Ecto.Query.DynamicExpr (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Inspect.Ecto.Query.DynamicExpr.beam)
  lib/ecto/query/inspect.ex:6

warning: redefining module Mix.Tasks.Ecto.Gen.Repo (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Mix.Tasks.Ecto.Gen.Repo.beam)
  lib/mix/tasks/ecto.gen.repo.ex:1

warning: redefining module Inspect.Ecto.Query (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Inspect.Ecto.Query.beam)
  lib/ecto/query/inspect.ex:19

warning: redefining module Ecto.Adapters.SQL.Stream (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Adapters.SQL.Stream.beam)
  lib/ecto/adapters/sql/stream.ex:1

warning: redefining module Ecto.Adapters.MySQL (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Adapters.MySQL.beam)
  lib/ecto/adapters/mysql.ex:1

warning: redefining module Enumerable.Ecto.Adapters.SQL.Stream (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Enumerable.Ecto.Adapters.SQL.Stream.beam)
  lib/ecto/adapters/sql/stream.ex:12

warning: redefining module Ecto.Schema (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Schema.beam)
  lib/ecto/schema.ex:1

warning: redefining module Collectable.Ecto.Adapters.SQL.Stream (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Collectable.Ecto.Adapters.SQL.Stream.beam)
  lib/ecto/adapters/sql/stream.ex:26

warning: redefining module Ecto.Query.API (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.API.beam)
  lib/ecto/query/api.ex:1

warning: redefining module Ecto.Adapter.Migration (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Adapter.Migration.beam)
  lib/ecto/adapter/migration.ex:1

warning: redefining module Ecto.Adapters.SQL.Sandbox (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Adapters.SQL.Sandbox.beam)
  lib/ecto/adapters/sql/sandbox.ex:1

warning: redefining module Ecto.Migration.Runner (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Migration.Runner.beam)
  lib/ecto/migration/runner.ex:1

warning: redefining module Ecto.Adapters.SQL.Sandbox.Connection (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Adapters.SQL.Sandbox.Connection.beam)
  lib/ecto/adapters/sql/sandbox.ex:296

warning: redefining module Ecto.Embedded (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Embedded.beam)
  lib/ecto/embedded.ex:1

warning: redefining module Ecto.Repo.Schema (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Repo.Schema.beam)
  lib/ecto/repo/schema.ex:1

warning: redefining module Ecto.Migration.SchemaMigration (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Migration.SchemaMigration.beam)
  lib/ecto/migration/schema_migration.ex:1

warning: redefining module Ecto.Adapters.SQL.Sandbox.Pool (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Adapters.SQL.Sandbox.Pool.beam)
  lib/ecto/adapters/sql/sandbox.ex:365

warning: redefining module Ecto.Schema.Metadata (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Schema.Metadata.beam)
  lib/ecto/schema.ex:285

warning: redefining module Ecto.Migration.Supervisor (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Migration.Supervisor.beam)
  lib/ecto/migration/supervisor.ex:1

warning: redefining module Inspect.Ecto.Schema.Metadata (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Inspect.Ecto.Schema.Metadata.beam)
  lib/ecto/schema.ex:300

warning: redefining module Ecto.Query.Builder.Preload (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.Builder.Preload.beam)
  lib/ecto/query/builder/preload.ex:3

warning: redefining module Mix.Ecto (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Mix.Ecto.beam)
  lib/mix/ecto.ex:1

warning: redefining module Ecto.Query.Builder.OrderBy (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.Builder.OrderBy.beam)
  lib/ecto/query/builder/order_by.ex:3

warning: redefining module Ecto.Repo.Assoc (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Repo.Assoc.beam)
  lib/ecto/repo/assoc.ex:1

warning: redefining module Ecto.Repo.Supervisor (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Repo.Supervisor.beam)
  lib/ecto/repo/supervisor.ex:1

warning: redefining module Ecto.Type (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Type.beam)
  lib/ecto/type.ex:1

warning: redefining module Ecto.UUID (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.UUID.beam)
  lib/ecto/uuid.ex:1

warning: redefining module Ecto.Application (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Application.beam)
  lib/ecto/application.ex:1

warning: redefining module Mix.Tasks.Ecto.Migrate (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Mix.Tasks.Ecto.Migrate.beam)
  lib/mix/tasks/ecto.migrate.ex:1

warning: redefining module Ecto.Query.CompileError (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.CompileError.beam)
  lib/ecto/exceptions.ex:1

warning: redefining module Ecto.Queryable (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Queryable.beam)
  lib/ecto/queryable.ex:1

warning: redefining module Ecto.Query.CastError (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.CastError.beam)
  lib/ecto/exceptions.ex:8

warning: redefining module Ecto.Association.NotLoaded (current version loaded from /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Association.NotLoaded.beam)
  lib/ecto/association.ex:3


== Compilation error in file lib/ecto/adapters/postgres/connection.ex ==
** (UndefinedFunctionError) function Ecto.Adapter.json_library/0 is undefined or private
    Ecto.Adapter.json_library()
    lib/ecto/adapters/postgres/connection.ex:4: (file)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

**Comment by josevalim** [comment]
There is something wrong happening in your project. The warnings say that Ecto files are coming from here:

    /Users/jimetsu/Projekte/anonymizer/_build/dev/lib/dep_from_git/ebin/Elixir.Ecto.Query.API.beam

But I don't think there is an application called `dep_from_git` and, even if there was one, it should not contain Ecto files.

So I am guessing what happened is that you at some point defined `{:dep_from_git, "...", github: "elixir-ecto/ecto"}` as well as `:ecto` and you didn't clean the former. Then files from one are conflicting with the other. You can try fixing the deps entry in your "mix.exs" and running `mix clean --deps` before running `mix deps.get` again.
