### ISSUE TITLE
BadMapError in select_merge/2

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#2436]
### Environment

* Elixir version (elixir -v): Elixir 1.7.0-dev (252974e) (compiled with OTP 20)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): 2.2.8
* Database adapter and version (mix deps): 0.13.5
* Operating system: macOS

### Current behavior

After updating from 2.2.7 we observe a regression bug for a query that uses `select_merge/2`:

```
** (BadMapError) expected a map, got: nil
 code: assert [%Draft{id: ^draft1_id}, %Draft{id: ^draft2_id}] = Loader.all_for_profile_id(owner.profile.id)
 stacktrace:
   (ecto) lib/ecto/repo/queryable.ex:276: anonymous fn/2 in Ecto.Repo.Queryable.process_update/6
   (elixir) lib/enum.ex:1905: Enum."-reduce/3-lists^foldl/2-0-"/3
   (ecto) lib/ecto/repo/queryable.ex:274: Ecto.Repo.Queryable.process_update/6
   (ecto) lib/ecto/repo/queryable.ex:194: Ecto.Repo.Queryable.process/5
   (ecto) lib/ecto/repo/queryable.ex:174: Ecto.Repo.Queryable.preprocess/5
   (postgrex) lib/postgrex/query.ex:77: DBConnection.Query.Postgrex.Query.decode_map/3
   (postgrex) lib/postgrex/query.ex:64: DBConnection.Query.Postgrex.Query.decode/3
   (db_connection) lib/db_connection.ex:1019: DBConnection.decode/6
   (ecto) lib/ecto/adapters/postgres/connection.ex:73: Ecto.Adapters.Postgres.Connection.prepare_execute/5
   (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
   (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
   (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
   (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
   (ecto) lib/ecto/repo/queryable.ex:78: Ecto.Repo.Queryable.one!/4
   (myapp_domain) lib/myapp_domain/draft/loader.ex:93: myapp.Domain.Draft.Loader.preload_latest_snapshot/2
   (elixir) lib/enum.ex:1298: Enum."-map/2-lists^map/1-0-"/2
   (myapp_domain) lib/myapp_domain/draft/loader.ex:46: myapp.Domain.Draft.Loader.all_for_profile_id/1
   test/myapp_domain/draft/loader_test.exs:217: (test)
```

Query:
```
#Ecto.Query<from s in Myapp.Domain.Draft.Snapshot,
 where: s.draft_id == ^"4e563acf-910e-4b64-9388-c71d3cc5bb53",
 order_by: [desc: s.inserted_at], limit: 1,
 select: merge(merge(struct(s, [:id, :title, :company_logo_url, :attachments, :parties]), %{struct(s, [:id, :title, :company_logo_url, :attachments, :parties]) | version: struct(s, [:id, :title, :company_logo_url, :attachments, :parties]).id}), struct(s, [:id, :title, :company_logo_url, :attachments, :parties]))>
```

By inspecting what happens inside Ecto, I can see that [here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/queryable.ex#L272) `data` can be `nil`.

**Comment by AndrewDryga** [comment]
[Here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/queryable.ex#L254) from is `nil`.
It's called from [here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/queryable.ex#L239).

**Comment by josevalim** [comment]
@AndrewDryga can you reproduce it with a test in our suite?

**Comment by AndrewDryga** [comment]
@josevalim it's done. I'm not sure the best way to handle it, trough.

**Comment by AndrewDryga** [comment]
Upd: I've solved it by adding `process/5` clause. See the PR.
