### ISSUE TITLE
Problem setting default value in a migration for :binary type

### ISSUE THREAD

**Issue by maxim** [elixir-ecto/ecto#2561]
### Environment

* Elixir version (elixir -v): 1.6.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.3
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: MacOS High Sierra 10.13.4

### Current behavior

Hi folks, thanks for amazing work. Not 100% sure if this is Ecto adapter or Postgrex issue.

Looks like migration `:default` parameter for a `:binary` doesn't allow using the `<<…>>` syntax. Given the following migration:

```elixir
defmodule MyApp.Repo.Migrations.CreateThings do
  use Ecto.Migration

  def change do
    create table(:things) do
      add(:data, :binary, default: <<0, 0>>)
    end
  end
end
```

When I try to run `mix ecto.migrate` I get the following error:

```
[info] == Running MyApp.Repo.Migrations.CreateThings.change/0 forward
[info] create table things
** (Postgrex.Error) ERROR 08P01 (protocol_violation): invalid message format
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:96: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:96: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:104: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:102: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:128: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:261: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:83: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
```

Yet in [the docs](https://hexdocs.pm/ecto/Ecto.Schema.html) it states that this syntax is acceptable:

<img width="622" alt="screen shot 2018-05-23 at 02 05 54" src="https://user-images.githubusercontent.com/7758/40406286-1cd4e774-5e2e-11e8-909b-da3a523c8114.png">

It does work however if I instead use the hex string as follows:

```elixir
add(:data, :binary, default: "\\x0000")
```

which took me a quite a bit of trial and error to figure out.

### Expected behavior

The `<<0, 0>>` default value should work in migration.

**Edit:** Just in case you're wondering, I tried different integers to the same effect, so it's not a problem with using zeroes in the binary.

**Comment by maxim** [comment]
I deleted my second edit at the bottom where I thought it was fixed on master. This is not fixed on master.

**Comment by maxim** [comment]
PR above for master, but thinking to backport to 2.2. Does this seem right, should I go ahead?
