### ISSUE TITLE
Custom types + "IN" queries fail

### ISSUE THREAD

**Issue by thecodeboss** [elixir-ecto/ecto#2587]
### Environment

* Elixir version (elixir -v): Elixir 1.6.5 (OTP 20)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): 2.2.8 (a4463c09)
* Database adapter and version (mix deps): N/A
* Operating system: MacOS

### Current behavior

I have a custom `Ecto.Type` defined that is basically an enum:

```elixir
defmodule MyEnumType do
  @behaviour Ecto.Type

  def type, do: :integer

  def cast(string) when is_binary(string), do: {:ok, String.to_atom(string)}
  def cast(atom) when is_atom(atom), do: {:ok, atom}
  def cast(_), do: :error

  def load(1), do: {:ok, :foo}
  def load(2), do: {:ok, :bar}
  def load(3), do: {:ok, :dog}

  def dump(:foo), do: {:ok, 1}
  def dump(:bar), do: {:ok, 2}
  def dump(:dog), do: {:ok, 3}
  def dump(_), do: :error
end
```
and a schema defined something like this:
```elixir
defmodule User do
  use Ecto.Schema

  schema "users" do
    field :type, MyEnumType
  end
end
```

I can write queries like the following and they execute properly:
```elixir
type = :foo
query = from u in User, where: u.type == ^type
Repo.all(query)
```

However, if I use a list like this:
```elixir
types = [:foo, :bar]
query = from u in User, where: u.type in ^types
Repo.all(query)
```
I get the following error:
```elixir
** (exit) an exception was raised:
    ** (Ecto.Query.CastError) /home/moliver/example/user.ex:136: value `[:foo, :bar]` cannot be dumped to type {:in, MyEnumType} in query:

from u in User,
  where: u.type in ^[:foo, :bar],
  select: u

        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
        (web) lib/web/controllers/page_controller.ex:54: Example.Web.PageController.logs/2
        (web) lib/web/controllers/page_controller.ex:1: Example.Web.PageController.action/2
        (web) lib/web/controllers/page_controller.ex:1: Example.Web.PageController.phoenix_controller_pipeline/2
        (web) lib/web/endpoint.ex:1: Example.Web.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
```

### Expected behavior

This query:
```elixir
types = [:foo, :bar]
query = from u in User, where: u.type in ^types
Repo.all(query)
```
should be able to properly cast the elements of `types` and return results.

**Comment by thecodeboss** [comment]
Actually scratch that. I wrote up this detailed explanation, but then found a typo in my list. The casting does, in fact, work for lists.
