### ISSUE TITLE
Incomprehensible compilation error on invalid binding expression

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-ecto/ecto#2613]
### Environment

* Ecto version (mix deps): 2.2.10

### Current behavior

Compiling a query with invalid binding expression results in incomprehensible compilation error

```
** (ArgumentError) argument error
     stacktrace:
       :erlang.element(5, {"p", "a0", "m", "a1"})
       (ecto) lib/ecto/query/inspect.ex:160: Inspect.Ecto.Query.expr_to_string/4
       (elixir) lib/macro.ex:819: Macro.unary_call/2
       (elixir) lib/macro.ex:678: Macro.to_string/2
       (elixir) lib/macro.ex:909: Macro.call_to_string/2
       (elixir) lib/macro.ex:917: Macro.call_to_string_with_args/3
       (elixir) lib/macro.ex:686: Macro.to_string/2
       (elixir) lib/enum.ex:1366: anonymous fn/4 in Enum.map_join/3
       (elixir) lib/enum.ex:1899: Enum."-map_join/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1899: Enum.map_join/3
       (elixir) lib/macro.ex:580: Macro.to_string/2
       (elixir) lib/enum.ex:1366: anonymous fn/4 in Enum.map_join/3
       (elixir) lib/enum.ex:1899: Enum."-map_join/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1899: Enum.map_join/3
       (elixir) lib/macro.ex:918: Macro.call_to_string_with_args/3
       (elixir) lib/macro.ex:686: Macro.to_string/2
       (elixir) lib/macro.ex:982: anonymous fn/2 in Macro.kw_list_to_string/2
       (elixir) lib/enum.ex:1366: anonymous fn/4 in Enum.map_join/3
       (elixir) lib/enum.ex:1899: Enum."-map_join/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1899: Enum.map_join/3
```

I can see that another branch of `Inspect.Ecto.Query.expr_to_string` catches this error and raises ArgumentError "unknown binding" which is not helpful either.

### Expected behavior

Error with line number of invalid binding or at least the exact invalid binding. Note that `{"p", "a0", "m", "a1"}` is not even close as the binding expression was `[u, c, r, mc, mr]`.

**Comment by josevalim** [comment]
Can you please provide a query that reproduces the error?

**Comment by lukaszsamson** [comment]
I guess it would not be helpful as the query is complicated and dynamic. I can include what inspect returns for this query (sanitized).
```
#Ecto.Query<from p in Model1,
 left_join: a0 in subquery(from a in Model2,
  where: a.some_id == ^23416,
  where: a.event_timestamp >= ^~N[2015-01-01 14:00:00] and a.event_timestamp <= ^~N[2015-01-01 15:30:07],
  group_by: [a.other_id],
  select: %{id: a.other_id, stat: sum(a.stat)}),
 on: p.id == a0.id,
 left_join: m in subquery(from m in Model3,
  where: m.some_id == ^23416,
  where: m.date >= ^~N[2015-01-01 14:00:00] and m.date <= ^~N[2015-01-01 15:30:07],
  group_by: [m.other_id],
  having: true and true,
  select: %{id: m.other_id, stat: fragment("coalesce(SUM(?), 0)::integer", m.count)}),
 on: p.id == m.id,
 left_join: a1 in subquery(from a in Model4,
  where: a.some_id == ^23416,
  where: a.hour >= ^~N[2015-01-01 14:00:00] and a.hour <= ^~N[2015-01-01 15:30:07],
  group_by: [a.id],
  select: %{id: a.id, stat: sum(a.stat)}),
 on: p.id == a1.id, where: p.some_id == ^23416,
 where: true and true, where: true and true, where: true and true,
 where: true and true, order_by: [desc: p.id], limit: ^10, offset: ^0,
 select: %{model: p, stat1: fragment("coalesce(?, 0)", a0.stat), stat2: fragment("coalesce(?, 0)", stat), stat3: fragment("coalesce(?, 0)", a1.stat)}>
```
The query has 3 left joins to subqueries but the final select tried to bind 5 variables.
