### ISSUE TITLE
BadMapError compile error using Ecto.Query.join/5, as option and Ecto.Query.update/3

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto#2743]
I'm working for `Company` which is interested in `ecto` 3 and `phoenix` 1.4 new features which would help us a lot, so reporting possible issues have higher priority for me - we have even special branches for them on my local machine. :-)

I wanted to tried write one migration using latest API, but got `BadMapError`. It's not critical for me now, because I can solve same problem in old way, but I would like to use this feature in more important parts of our code soon. I have hidden our naming, so there is `ModelA`, `b_assoc` etc. Please let me know if you will need more information or code example.

### Environment

```elixir
$ asdf current
elixir         1.7.3-otp-21 (set by …)
erlang         21.1    (set by …)
postgres       10.5    (set by …)
…

$ mix deps.get
…
* ecto 3.0.0-dev (https://github.com/elixir-ecto/ecto.git) (mix)
  locked at 97a6350
  ok
…
* postgrex 0.14.0-rc.0 (Hex package) (mix)
  locked at 0.14.0-rc.0 (postgrex) 1529edba
  ok
…

$ epro
=== Enabled Profiles: ===

        arch: x86-64bit
       build: current
     subarch: intel64-ivybridge
      flavor: desktop
     mix-ins: kde-plasma-5
     mix-ins: no-systemd
$ uname -a
Linux funtoo 4.8.15-1 #3 SMP Sat Nov 11 23:20:19 CET 2017 x86_64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz GenuineIntel GNU/Linux
…
```

The distribution name is `Funtoo Linux` (`Gentoo`-based)

### Not working code

```elixir
ModelA
|> Query.from(as: :a)
|> Query.where([a: a], is_nil(a.field_name))
|> Query.join(:inner, [a: a], assoc(a, :b_assoc), as: :b)
|> Query.update([b: b], set: [field_name: value])
```

### Similar working code

```elixir
ModelA
|> Query.from(as: :a)
|> Query.where([a], is_nil(a.field_name))
|> Query.update([a: a], set: [field_name: value])
```

### Current behavior

I got such compilation error:

```elixir
[info] == Running $MyApp$.Repo.Migrations.$MigrationName$.change/0 forward
** (BadMapError) expected a map, got: {{:., [], [{:__aliases__, [alias: false], [:Ecto, :Query, :Builder, :Join]}, :apply_aliases]}, [], [{:%{}, [], [a: 0]}, :b, nil]}
    (stdlib) :maps.find(:b, {{:., [], [{:__aliases__, [alias: false], [:Ecto, :Query, :Builder, :Join]}, :apply_aliases]}, [], [{:%{}, [], [a: 0]}, :b, nil]})
    _build/dev/lib/$my_app$/priv/repo/migrations/$migration_number$_$migration_name$.exs:$line$: $MyApp$.Repo.Migrations.$MigrationName$.change/0
    (stdlib) timer.erl:197: :timer.tc/3
    (ecto_sql) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6
    (ecto_sql) lib/ecto/migrator.ex:197: Ecto.Migrator.attempt/6
    (ecto_sql) lib/ecto/migrator.ex:113: anonymous fn/3 in Ecto.Migrator.do_up/4                                                           
    (ecto_sql) lib/ecto/adapters/sql.ex:776: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4                                 
    (db_connection) lib/db_connection.ex:1341: DBConnection.run_transaction/4                                                              
    (ecto_sql) lib/ecto/migrator.ex:185: Ecto.Migrator.do_run_maybe_in_transaction/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Expected behavior

As far as I know both code examples (assuming that both models, relations etc. are valid) should compile and work without problem.

**Comment by josevalim** [comment]
I know why the error is happening but I can't reproduce it. Can you give us a bit more context on the query?

**Comment by Eiji7** [comment]
@josevalim sorry, what you mean by "more context"
Do you need example code for this?

**Comment by josevalim** [comment]
The snippet you sent is not enough to reproduce the error, so I need a bigger snippet. :) A bit more of exmaple code would be great then!

**Comment by Eiji7** [comment]
@josevalim Here is bigger snippet:

```elixir
mix_dep({:ecto, github: "elixir-ecto/ecto"})

alias Ecto.Query

require Query

defmodule ModelB do
  use Ecto.Schema

  schema "b" do
    field(:sample, :integer)
  end
end

defmodule ModelA do
  use Ecto.Schema

  schema "a" do
    has_one(:b, ModelB)
    field(:sample, :integer)
  end
end

ModelA
|> Query.from(as: :a)
|> Query.update([a: a], set: [sample: a.sample + 1])

ModelA
|> Query.from(as: :a)
|> Query.join(:inner, [a: a], assoc(a, :b), as: :b)
|> Query.update([b: b], set: [sample: b.sample + 1])
```

You can compile and run it in one file using [mix_script](https://github.com/minhajuddin/mix_script) or add to any project. :smiley:
