### ISSUE TITLE
Error when inserted_at/updated_at are timestamptz

### ISSUE THREAD

**Issue by samphilipd** [elixir-ecto/ecto#2796]
(Ecto 3.0)

We have some timestamps in `timestamptz` format.

My definition looks like:

`timestamps(inserted_at: :created_at, type: :utc_datetime)`

But it seems the Ecto is inserting it as a NaiveDateTime, because I get this error:

```
** (DBConnection.EncodeError) Postgrex expected %DateTime{}, got ~N[2018-11-07 11:26:56]. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
```

**Comment by josevalim** [comment]
@samphilipd this has tripped enough people at this point that we think we should go ahead and change it, although we will have to wait a bit as it requires a new mariaex version.

**Comment by josevalim** [comment]
Please see #2798. We can only merge and ship it though once there is a new mariaex version out.

**Comment by samphilipd** [comment]
@josevalim So was this a bug, or an overly strict feature in the end?

**Comment by josevalim** [comment]
@samphilipd I think it was a bug.

**Comment by samphilipd** [comment]
@josevalim unfortunately this is still an error even with Ecto 3.0.3 and Ecto_sql 3.0.2:

```
[info] == Migrated 20181123105737 in 0.0s
[error] Could not update schema migrations. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :nest_db, NestDB.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (DBConnection.EncodeError) Postgrex expected %DateTime{}, got ~N[2018-11-27 12:07:10]. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    /Users/sam/code/work/nested/local-stack/elixir-umbrella/deps/postgrex/lib/postgrex/type_module.ex:713: NestDB.PostgrexTypes.encode_params/3
    (postgrex) lib/postgrex/query.ex:62: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:1074: DBConnection.encode/5
    (db_connection) lib/db_connection.ex:1172: DBConnection.run_prepare_execute/5
    (db_connection) lib/db_connection.ex:480: DBConnection.parsed_prepare_execute/5
    (db_connection) lib/db_connection.ex:473: DBConnection.prepare_execute/4
    (postgrex) lib/postgrex.ex:161: Postgrex.query/4
    (ecto_sql) lib/ecto/adapters/sql.ex:632: Ecto.Adapters.SQL.struct/10
```

**Comment by samphilipd** [comment]
Worked around it by manually running the following SQL on our production database:

```SQL
ALTER TABLE ecto_schema_migrations
ALTER COLUMN inserted_at TYPE timestamp without time zone;
```

**Comment by benschenker** [comment]
Resolved this issue for us by adding `@timestamps_opts [type: :utc_datetime]` to the schema that had the timestamp fields
