### ISSUE TITLE
`ecto.migrate` cannot migrate on RDS database

### ISSUE THREAD

**Issue by tmattio** [elixir-ecto/ecto#2868]
I am currently deploying a Phoenix app in production and encounter some issue while running Ecto's migrations.

Locally, the migrations work perfectly, however, when changing the parameters in `config.ex` to point to the production database, I have the following error:

```
[error] Could not retrieve migrated versions. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :sapiens, Sapiens.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name): no schema has been selected to create in
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:96: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:96: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:44: anonymous fn/2 in Ecto.Migrator.migrated_versions/2
    (ecto) lib/ecto/migrator.ex:300: Ecto.Migrator.verbose_schema_migration/3
    (ecto) lib/ecto/migrator.ex:157: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:83: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

The commands `mix ecto.drop` and `mix ecto.create` work as expected, but impossible to run the migrations.

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

```
PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit
```

* Ecto version (mix deps):

```
ecto 2.2.11 (Hex package) (mix)
locked at 2.2.11 (ecto) 4bb8f117
ok
```

* Database adapter and version (mix deps):

```
* postgrex 0.13.5 (Hex package) (mix)
  locked at 0.13.5 (postgrex) 3d931aba
  ok
```

* Operating system:

```
uname -a
Darwin Thibauts-MacBook-Pro-2.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by josevalim** [comment]
I believe it is a permission issue: https://dba.stackexchange.com/questions/106057/error-no-schema-has-been-selected-to-create-in

Is this a fresh RDS instance? IF you can't have those permissions, then you may need to use the after_connect callback to change the default schema for each connection.
