### ISSUE TITLE
upgrading from 3.0.1 -> 3.0.7 breaks DateTime in query

### ISSUE THREAD

**Issue by atomkirk** [elixir-ecto/ecto#2925]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.7.24
* Ecto version (mix deps): 3.0.7
* Database adapter and version (mix deps): mariaex 0.9.0
* Operating system: macOS 10.14.3

### Current behavior

After bumping ecto from 3.0.1 to 3.0.7 we now get this error on tests that previously passed:

```
  1) test update user identity (ZB.Controllers.Identity.UpdateTest)
     lib/zipbooks_web/controllers/accounts/identity_controller/update_test.exs:7
     ** (ArgumentError) query has invalid parameter #DateTime<2019-02-25 17:03:19Z>
     stacktrace:
       (mariaex) lib/mariaex/query.ex:169: DBConnection.Query.Mariaex.Query.encode_param/2
       (mariaex) lib/mariaex/query.ex:76: DBConnection.Query.Mariaex.Query.encode_params/3
       (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
       (mariaex) lib/mariaex/query.ex:70: DBConnection.Query.Mariaex.Query.parameters_to_binary/2
       (db_connection) lib/db_connection.ex:1074: DBConnection.encode/5
       (db_connection) lib/db_connection.ex:1172: DBConnection.run_prepare_execute/5
       (db_connection) lib/db_connection.ex:480: DBConnection.parsed_prepare_execute/5
       (db_connection) lib/db_connection.ex:473: DBConnection.prepare_execute/4
       (mariaex) lib/mariaex.ex:456: Mariaex.run_query/5
       (ecto_sql) lib/ecto/adapters/mysql.ex:210: Ecto.Adapters.MySQL.insert/6
       (ecto) lib/ecto/repo/schema.ex:651: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:264: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
       (ecto) lib/ecto/association.ex:922: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto) lib/ecto/association.ex:408: Ecto.Association.on_repo_change/7
       (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/association.ex:387: Ecto.Association.on_repo_change/4
       (ecto) lib/ecto/repo/schema.ex:804: Ecto.Repo.Schema.process_parents/4
       (ecto) lib/ecto/repo/schema.ex:244: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
       (ecto) lib/ecto/repo/schema.ex:917: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql) lib/ecto/adapters/sql.ex:784: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
```

Seems like an inappropriate change for a point bug fix release. If this is not a bug, my apologies

**Comment by josevalim** [comment]
Have you tried updating mariaex too? I think it is a bug fix that requires
an update on both Ecto and Mariaex. You need 0.9.1.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by atomkirk** [comment]
That did it! Thanks! Sorry for the distraction
