### ISSUE TITLE
Cannot set type for result of the window function

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#2973]
### Environment
I've created a project for reproducing, here is a test with queries
https://github.com/fuelen/ecto_issue_with_over/blob/master/test/ecto_ussue_with_over/main_test.exs

### Current behavior
I have the following query
```elixir
query =
      from(users in User,
        join: posts in assoc(users, :posts),
        select: %{
          user: users,
          post_ids: over(fragment("ARRAY_AGG(?)", posts.id), :post_ids)
        },
        distinct: users.id,
        windows: [post_ids: [partition_by: users.id]]
)
```
the result of execution is
```elixir
[%{
    post_ids: [
      <<114, 24, 89, 122, 170, 38, 73, 180, 175, 160, 202, 12, 70, 25, 79, 108>>,
      <<13, 144, 66, 132, 16, 28, 74, 241, 128, 22, 228, 13, 63, 105, 15, 107>>,
      <<35, 162, 41, 35, 227, 224, 79, 204, 161, 226, 63, 87, 50, 60, 48, 228>>
    ],
    user: %EctoIssueWithOver.User{
      __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
      id: "f6cc67ad-6cb9-4e0a-9eb3-da93a36c4496",
      name: "name2",
      posts: #Ecto.Association.NotLoaded<association :posts is not loaded>
    }
  }]
```
and I want to get an array of strings (id is UUID) not binaries.
I tried this

```elixir
     query =
       from(users in User,
         join: posts in assoc(users, :posts),
         select: %{user: users, post_ids: type(over(fragment("ARRAY_AGG(?)", posts.id), {:array, :binary_id}), :post_ids)},
         distinct: users.id,
         windows: [post_ids: [partition_by: users.id]]
   )
```
but got a compilation error
```
 == Compilation error in file test/ecto_ussue_with_over/main_test.exs ==
     ** (Ecto.Query.CompileError) `type(over(fragment("ARRAY_AGG(?)", posts.id()), {:array, :binary_id}), :post_ids)` is not a valid query expression.
    
     * If you intended to call a database function, please check the documentation
       for Ecto.Query to see the supported database expressions
    
     * If you intended to call an Elixir function or introduce a value,
 you need to explicitly interpolate it with ^
```

### Expected behavior
load the result of the `over` to custom types

**Comment by josevalim** [comment]
Can you please try `over(type(fragment(...), ...), ...)` instead? In any case, we need to improve the error message.

**Comment by fuelen** [comment]
```elixir
query =
      from(users in User,
        join: posts in assoc(users, :posts),
        select: %{
          user: users,
          post_ids: over(type(fragment("ARRAY_AGG(?)", posts.id), {:array, :binary_id}), :post_ids)
        },
        distinct: users.id,
        windows: [post_ids: [partition_by: users.id]]
      )
```


```
== Compilation error in file test/ecto_ussue_with_over/main_test.exs ==
** (Ecto.Query.CompileError) unknown window function type/2. See Ecto.Query.WindowAPI for all available functions
    (ecto) expanding macro: Ecto.Query.select/3
    test/ecto_ussue_with_over/main_test.exs:39: MainTest."test over"/1
    (ecto) expanding macro: Ecto.Query.distinct/3
    test/ecto_ussue_with_over/main_test.exs:39: MainTest."test over"/1
    (ecto) expanding macro: Ecto.Query.windows/3
    test/ecto_ussue_with_over/main_test.exs:39: MainTest."test over"/1
    (ecto) expanding macro: Ecto.Query.from/2
    test/ecto_ussue_with_over/main_test.exs:39: MainTest."test over"/1
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by josevalim** [comment]
Excellent. thank you :)

I think you can make the last one work by adding a new clause here that matches on type: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/builder.ex#L467

Something like:

    defp validate_window_function!({:type, _, [{:fragment, _, _}, _]} = expr), do: expr

It may make something else fail though.
