### ISSUE TITLE
documentation / error improvement around #2977 (migration_lock / concurrent index creation)

### ISSUE THREAD

**Issue by adamkittelson** [elixir-ecto/ecto#3006]
I ran into the issue opened in #2977 (concurrent index creation in 3.1 hanging, worked around by configuring migration_lock to nil in the Repo config) and wanted to open an issue around making that issue a bit more intuitive.

I see the note added to the changelog:

```
[Ecto.Migration] Migrations now lock the migrations table in order to avoid concurrent migrations in a cluster. The type of lock can be configured via the :migration_lock repository configuration and defaults to "FOR UPDATE" or disabled if set to nil
```

but it doesn't mention anything about it being incompatible with creating indexes concurrently which could be a worthwhile note to add. Also from what I can tell there's no mention of this configuration option anywhere in the Ecto docs.

If you'd like I could create a PR adding something like the following to the config section of https://hexdocs.pm/ecto/3.1.4/Ecto.Repo.html:

```
    * `: migration_lock ` - by default the migrations table is locked to avoid concurrent migrations in a cluster, however this will cause concurrent index creation to hang, may be disabled by setting to `nil`
```

Feel free to bikeshed the phrasing. I do think locking the table is a reasonable default, but if there's no way to make it work with concurrent indexes I wonder if it wouldn't be better to raise an error when concurrent index creation is requested. I encountered this issue in first via travis since I didn't drop and recreate my database locally immediately after upgrading, and in travis you don't see the migration log output so it wasn't obvious what was happening. The travis error just looked like the following:

```
20:53:00.201 [error] Postgrex.Protocol (#PID<0.6385.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.93.0> timed out because it owned the connection for longer than 60000ms (set via the :ownership_timeout option)
20:53:00.207 [error] Could not update schema migrations. This error usually happens due to the following:
  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
To fix the first issue, run "mix ecto.create".
To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:
    config :pipeline, Pipeline.Repo,
      migration_source: "some_other_table_for_schema_migrations"
The full error report is shown below.
** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
    (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto_sql) lib/ecto/migrator.ex:558: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql) lib/ecto/migrator.ex:227: Ecto.Migrator.async_migrate_maybe_in_transaction/6
    (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
    (ecto_sql) lib/ecto/adapters/sql.ex:721: Ecto.Adapters.SQL.lock_for_migrations/5
    (ecto_sql) lib/ecto/migrator.ex:419: Ecto.Migrator.lock_for_migrations/3
    (ecto_sql) lib/ecto/migrator.ex:536: anonymous fn/5 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migrator.ex:535: Ecto.Migrator.migrate/4
    (ecto_sql) lib/ecto/adapters/sql/sandbox.ex:479: Ecto.Adapters.SQL.Sandbox.unboxed_run/2
    (ecto_sql) lib/ecto/migrator.ex:83: Ecto.Migrator.with_repo/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:118: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:106: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
```

So maybe a note about concurrent migrations / the migration lock in "Could not update schema migrations." error would be helpful as well.

Thanks!

**Comment by josevalim** [comment]
Done here! https://github.com/elixir-ecto/ecto_sql/commit/c1010915be830cdb7d8fe9df52bd81e2e1d94c0a

**Comment by adamkittelson** [comment]
Awesome, thanks Jose!
