### ISSUE TITLE
Ecto load error. can not load `{xxx}` as type :map

### ISSUE THREAD

**Issue by liketemple** [elixir-ecto/ecto#3029]
### Environment

* Elixir version : 1.7
* Database and version : PostgreSQL 10.6,
* Ecto version (mix deps): 3.1.5
* Database adapter and version (mix deps): postgrex 0.14
* Operating system: macOS 10.14

### Current behavior

the schema is:
```
defmodule Schema.Appointment do
  use Ecto.Schema

  schema "appointment" do
    field :appoint_id, :string
    field :appoint_name, :string
    field :appoint_type, :string
    field :start, :naive_datetime
    field :duration, :integer
    field :space, :string
    field :company, :string
    field :phone, :integer
    field :create_time, :naive_datetime
  end
end
```
I have already insert some records into the database.
then I do the query:
```
{{y,m,d}, _erl_time} = :calendar.local_time()
{_, tomorrow} = NaiveDateTime.new( Date.from_erl!({y,m,d + 1}), Time.from_erl!({23,59,59}))
query = from a in Schema.Appointment,
      where: a.start < ^tomorrow,
      select: a

res = MyApp.Repo.all(query)
```
I got this:
```
** (exit) an exception was raised:
    ** (ArgumentError) cannot load `{1, "meet", nil, "room", ~N[2019-06-20 14:00:00.000000], 2, "qwe", "abc", 88888888, ~N[2019-06-18 18:12:26.000000]}` as type :map
        (ecto) lib/ecto/repo/queryable.ex:345: Ecto.Repo.Queryable.process/4
        (ecto) lib/ecto/repo/queryable.ex:207: anonymous fn/4 in Ecto.Repo.Queryable.preprocessor/3
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/repo/queryable.ex:158: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```
**It seems, ecto already got the right query result which is a tuple, but could not cast is as a map.**  
Since the error message is all about the ecto, I have no idea how to get the result correctly. 
Any infomation would be helpful, thanks!

**Comment by josevalim** [comment]
@liketemple can you please provide a small application that reproduces this?  I can't think of anything on top of my mind that would trigger this and the error says "type :map" and the shown schema doesn't have one, so maybe some details are missing to full reproduce this.

**Comment by liketemple** [comment]
I think just figure it out.

I tried Repo.get and got a more specific error log with the tip that Jason could not encode struct %Schema.Appointment{}. 

The Repo.get error log look like this:
```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Schema.Appointment{__meta__: #Ecto.Schema.Metadata<:loaded, "appointment">, appoint_id: "abc", appoint_name: "dsf", appoint_type: "room", company: "qwe", create_time: ~N[2019-06-18 18:12:26], duration: 2, id: 1, phone: 18611890835, space: "dfg", start: ~N[2019-06-20 14:00:00]}, Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)

```

so I add the Protocol.derive declare and except the field :__meta__ and :id in the schema module, 
the whole file schema_appointment.ex is:
```
defmodule Schema.Appointment do
  use Ecto.Schema

  schema "appointment" do
    field :appoint_id, :string
    field :appoint_name, :string
    field :appoint_type, :string
    field :start, :naive_datetime
    field :duration, :integer
    field :space, :string
    field :company, :string
    field :phone, :integer
    field :create_time, :naive_datetime
  end
end

require Protocol
Protocol.derive(Jason.Encoder, Schema.Appointment, except: [:id, :__meta__])
```
After I add the Protocol.derive declare, Then the Repo.get() works fine.
when turn back to Repo.all(), the issue is gone too.

Maybe the Repo.all could give a little more information and it would be greate helpful for debug.

**Comment by josevalim** [comment]
I would love to improve the error message but I still don't know how to trigger it, which makes it hard to fix this. :) Can you provide a minimal reproduction step? Thanks!

**Comment by liketemple** [comment]
I use ecto in the Phoenix framework.

1. build the schema, **uncomment the last two line to make sure it will trigger**.
schema_Appointment.ex
```
defmodule Schema.Appointment do
  use Ecto.Schema

  schema "appointment" do
    field :appoint_id, :string
    field :appoint_name, :string
    field :appoint_type, :string
    field :start, :naive_datetime
    field :duration, :integer
    field :space, :string
    field :company, :string
    field :phone, :integer
    field :create_time, :naive_datetime
  end
end

#require Protocol
#Protocol.derive(Jason.Encoder, Schema.Appointment, except: [:id, :__meta__])
```

2. the controller: api_v1.ex
```
defmodule Api.V1 do
  use ServiceWeb, :controller
  require Logger
  import Ecto.Query

  def appointments(conn, params) do
    Logger.debug("params: #{inspect(params)}")
    {{y,m,d}, _erl_time} = :calendar.local_time()
    {_, tomorrow} = NaiveDateTime.new( Date.from_erl!({y,m,d + 1}), Time.from_erl!({23,59,59}))

    query = from a in Schema.Appointment,
      where: a.start < ^tomorrow,
      select: a

    res =WebApp.Repo.all(query)
    # res = WebApp.Repo.get(query, 1)
    Logger.debug("res: #{inspect(res)}")

    json(conn, Jason.encode!(%{"appointments"=>res}))
  end

  def add_appointment(conn, params) do
    with {:ok, space} <- Map.fetch(params, "space"),
      {:ok, company} <- Map.fetch(params, "company"),
      {:ok, id} <- Map.fetch(params, "objectId"),
      {:ok, type} <- Map.fetch(params, "appointType"),
      {:ok, duration} <- Map.fetch(params, "duration"),
      {:ok, start_time} <- Map.fetch(params, "startTime"),
      {:ok, phone} <- Map.fetch(params, "phone"),
      {:ok, s} = NaiveDateTime.from_iso8601(start_time) do
        {erl_date, erl_time} = :calendar.local_time()
        {_, create_time} = NaiveDateTime.new( Date.from_erl!(erl_date), Time.from_erl!(erl_time))
        app = %Schema.Appointment{:space=>space,
            :company=>company, :duration=>String.to_integer(duration),
            :start=>s, :phone=>String.to_integer(phone),
            :appoint_type=>type, :appoint_id=>id,
            :create_time=>create_time
          }
        WebApp.Repo.insert(app)
        json(conn, Jason.encode!(%{"add_appointment"=>"success"}))
      else _ ->
        Logger.debug(" --- has wrong params")
        json(conn, Jason.encode!(%{"add_appointment"=>"false"}))
      end
  end
end
```

3. the router:  router.ex
```
defmodule ServiceWeb.Router do
  use ServiceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ServiceWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", Api do
    pipe_through :api

    scope "/v1" do
      get "/appointments", V1, :appointments
      post "/add_appointment", V1, :add_appointment
    end


  end
end
```

4. config.exs
```
use Mix.Config


# Configures the endpoint
config :web_service, ServiceWeb.Endpoint,
  url: [host: "127.0.0.1"],
  render_errors: [view: ServiceWeb.ErrorView, accepts: ~w(html json)],
  pubsub: [name: Service.PubSub, adapter: Phoenix.PubSub.PG2],
  http: [
    port: 4000,
    dispatch: [
      {:_,
       [
          {"/ws", ServiceWeb.WebsocketHandler, []},
          {:_, Phoenix.Endpoint.Cowboy2Handler, {ServiceWeb.Endpoint, []}}
       ]}
    ]
  ]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Repo configures
config :web_service, ecto_repos: [WebApp.Repo]

config :web_service, WebApp.Repo,
  database: "xxxx",
  username: "xxxx",
  password: "xxxx",
  hostname: "127.0.0.1"

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env()}.exs"
```
5. Repo: repo.ex
```
defmodule WebApp.Repo do
  use Ecto.Repo,
    otp_app: :web_service,
    adapter: Ecto.Adapters.Postgres
end
```

6. mix.exs
```
defmodule WebService.MixProject do
  use Mix.Project

  def project do
    [
      app: :web_service,
      version: "0.1.0",
      elixir: "~> 1.5",
      elixirc_paths: elixirc_paths(Mix.env()),
      compilers: [:phoenix, :gettext] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [
      mod: {WebService.Application, []},
      extra_applications: [:logger, :runtime_tools]
    ]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:phoenix, "~> 1.4.6"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:distillery, "~> 2.0"},
      {:amqp, "~> 1.2"},
      {:plug_cowboy, "~> 2.0"},
      {:ecto_sql, "~> 3.1.5"},
      {:postgrex, "~> 0.14.0"}
    ]
  end
end
```

**Comment by josevalim** [comment]
Thanks! Can you please put this in a minimal app on GitHub we can clone and
give it a try?

We have very limited time to maintain Ecto and address bugs, so a minimal
case is very important for us, so we can focus our time on fixing it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by liketemple** [comment]
I confrimed use this code could repeat the error.  
[as_map_debug](https://github.com/liketemple/as_map_debug)

**Comment by josevalim** [comment]
Thanks! So the issue happens because you are writing a schemaless query:

https://github.com/liketemple/as_map_debug/blob/master/lib/ygspace_service_web/api/api_v1.ex#L16-L18

Notice how you are doing `from a in "appointment"` instead of `from a in Appointment`, once I change it, everything works. All code samples you posted here though used the proper syntax, so maybe you have a similar error elsewhere. In any case, the error message has been improved! Thanks.

**Comment by liketemple** [comment]
Thanks， I will use the proper syntax.
