### ISSUE TITLE
Pool Timeout suddenly breaks 

### ISSUE THREAD

**Issue by JackSoby** [elixir-ecto/ecto#3042]
### Environment

* phoenix version (1.4):
* Database and version (PostgreSQL 9.4,):

### Current behavior

I am running an import of large data. It has been working for months but suddenly i started getting this error `warning: :pool_timeout option no longer has an effect and has been replaced with an improved queuing system.`
it is not working

### Expected behavior

The import has been running fine for months. it works locally but not live.

I tried adding a queue interval but that broke everything on live

**Comment by josevalim** [comment]
What  is your Ecto version? Have you upgraded versions meanwhile? What is
the full error? What have you tried?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by JackSoby** [comment]
Hi @josevalim Sorry for not being more clear, I was rushing around trying to solve things. 

Here are my versions 

`      {:ecto_sql, "~> 3.0"},
      {:phoenix_ecto, "~> 4.0"}
`
And no I have not upgraded anything

This was my original code that was breaking on production

```config :beswick, Beswick.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "${DB_HOST}",
  database: "${DB_NAME}",
  username: "${DB_USER}",
  password: "${DB_PASSWORD}",
  pool_size: 15,
 pool_timeout: 500_000,
  timeout: 500_000,
  ownership_timeout: 500_000,
  backoff_type: :stop
```

I removed the `pool_timeout` and added `queue_target` and `queue_interval`

```config :beswick, Beswick.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "${DB_HOST}",
  database: "${DB_NAME}",
  username: "${DB_USER}",
  password: "${DB_PASSWORD}",
  pool_size: 15,
  queue_target: 500_000,
  queue_interval: 500_000,
  timeout: 500_000,
  ownership_timeout: 500_000,
  backoff_type: :stop
```
When I made that change it broke the whole site so i changed it to

```config :beswick, Beswick.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "${DB_HOST}",
  database: "${DB_NAME}",
  username: "${DB_USER}",
  password: "${DB_PASSWORD}",
  pool_size: 15,
  timeout: 500_000,
  ownership_timeout: 500_000,
  backoff_type: :stop
```
It looks like all I had to do was remove the pool timeout to fix things.

here is the full stack trace 

```
 
E 2019-06-27T01:02:25.225962731Z warning: :pool_timeout option no longer has an effect and has been replaced with an improved queuing system.
 
E 2019-06-27T01:02:25.226038871Z See "Queue config" in DBConnection.start_link/2 documentation for more information.
 
E 2019-06-27T01:02:25.226043520Z 
 
E 2019-06-27T01:02:25.226046766Z   (ecto_sql) lib/ecto/adapters/sql.ex:459: Ecto.Adapters.SQL.adapter_config/1
 
E 2019-06-27T01:02:25.226050153Z   (ecto_sql) lib/ecto/adapters/sql.ex:446: Ecto.Adapters.SQL.init/3
 
E 2019-06-27T01:02:25.226053341Z   (ecto) lib/ecto/repo/supervisor.ex:162: Ecto.Repo.Supervisor.init/1
 
E 2019-06-27T01:02:25.226056552Z   (stdlib) supervisor.erl:295: :supervisor.init/1
 
E 2019-06-27T01:02:25.226060840Z   (stdlib) gen_server.erl:374: :gen_server.init_it/2
 
E 2019-06-27T01:02:25.226064159Z 
 
I 2019-06-27T01:02:25.285477253Z Running migrations for beswick
 
I 2019-06-27T01:02:25.568983715Z {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Ecto.MigrationError',message=><<77,105,103,114,97,116,105,111,110,115,32,102,97,105,108,101,100,32,116,111,32,114,117,110,32,98,101,99,97,117,115,101,32,116,104,101,32,99,111,110,110,101,99,116,105,111,110,32,112,111,111,108,32,115,105,122,101,32,105,115,32,108,101,115,115,32,116,104,97,110,32,50,46,10,10,69,99,116,111,32,114,101,113,117,105,114,101,115,32,97,32,112,111,111,108,32,115,105,122,101,32,111,102,32,97,116,32,108,101,97,115,116,32,50,32,116,111,32,115,117,112,112,111,114,116,32,99,111,110,99,117,114,114,101,110,116,32,109,105,103,114,97,116,111,114,115,46,10,87,104,101,110,32,109,105,103,114,97,116,105,111,110,115,32,114,117,110,44,32,69,99,116,111,32,117,115,101,115,32,111,110,101,32,99,111,110,110,101,99,116,105,111,110,32,116,111,32,109,97,105,110,116,97,105,110,32,97,32,108,111,99,107,32,97,110,100,10,97,110,111,116,104,101,114,32,116,111,32,114,117,110,32,109,105,103,114,97,116,105,111,110,115,46,10,10,73,102,32,121,111,117,32,97,114,101,32,114,117,110,110,105,110,103,32,109,105,103,114,97,116,105,111,110,115,32,119,105,116,104,32,77,105,120,44,32,121,111,117,32,99,97,110,32,105,110,99,114,101,97,115,101,32,116,104,101,32,110,117,109,98,101,114,10,111,102,32,99,111,110,110,101,99,116,105,111,110,115,32,118,105,97,32,116,104,101,32,112,111,111,108,32,115,105,122,101,32,111,112,116,105,111,110,58,10,10,32,32,32,32,109,105,120,32,101,99,116,111,46,109,105,103,114,97,116,101,32,45,45,112,111,111,108,45,115,105,122,101,32,50,10,10,73,102,32,121,111,117,32,97,114,101,32,114,117,110,110,105,110,103,32,116,104,101,32,69,99,116,111,46,77,105,103,114,97,116,111,114,32,112,114,111,103,114,97,109,109,97,116,105,99,97,108,108,121,44,32,121,111,117,32,99,97,110,32,99,111,110,102,105,103,117,114,101,10,116,104,101,32,112,111,111,108,32,115,105,122,101,32,118,105,97,32,121,111,117,114,32,97,112,112,108,105,99,97,116,105,111,110,32,99,111,110,102,105,103,58,10,10,32,32,32,32,99,111,110,102,105,103,32,58,109,121,95,97,112,112,44,32,82,101,112,111,44,10,32,32,32,32,32,32,46,46,46,44,10,32,32,32,32,32,32,112,111,111,108,95,115,105,122,101,58,32,50,32,35,32,97,116,32,108,101,97,115,116,10>>},[{'Elixir.Ecto.Adapters.SQL',raise_pool_size_error,0,[{file,"lib/ecto/adapters/sql.ex"},{line,719}]},{'Elixir.Ecto.Adapters.SQL',lock_for_migrations,5,[{file,"lib/ecto/adapters/sql.ex"},{line,704}]},{'Elixir.Ecto.Migrator',lock_for_migrations,3,[{file,"lib/ecto/migrator.ex"},{line,351}]},{'Elixir.Ecto.Migrator',run,4,[{file,"lib/ecto/migrator.ex"},{line,267}]},{'Elixir.Enum','-each/2-lists^foreach/1-0-',2,[{file,"lib/enum.ex"},{line,737}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,737}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
 
E 2019-06-27T01:02:25.574251322Z init terminating in do_boot ({,[{Elixir.Ecto.Adapters.SQL,raise_pool_size_error,0,[{_},{_}]},{Elixir.Ecto.Adapters.SQL,lock_for_migrations,5,[{_},{_}]},{Elixir.Ecto.Migrator,lock_for_migrations,3,[{_}
 
E 2019-06-27T01:02:25.576945052Z 
 
E 2019-06-27T01:02:25.707613449Z Crash dump is being written to: erl_crash.dump...done
 
I 2019-06-27T01:02:28.485735044Z 01:02:28.484 [info] GET /
 
I 2019-06-27T01:02:28.495018309Z 01:02:28.493 [info] Sent 200 in 9ms
 
I 2019-06-27T01:02:33.107032622Z 01:02:33.106 [info] GET /
 
I 2019-06-27T01:02:33.114532112Z 01:02:33.113 [info] Sent 200 in 6ms
 
I 2019-06-27T01:02:35.079340050Z 01:02:35.077 [info] [swarm on beswick@127.0.0.1] [tracker:init] started
 
E 2019-06-27T01:02:35.394466314Z warning: :pool_timeout option no longer has an effect and has been replaced with an improved queuing system.
 
E 2019-06-27T01:02:35.394527651Z See "Queue config" in DBConnection.start_link/2 documentation for more information.
 
E 2019-06-27T01:02:35.394533224Z 
 
E 2019-06-27T01:02:35.394536631Z   (ecto_sql) lib/ecto/adapters/sql.ex:459: Ecto.Adapters.SQL.adapter_config/1
 
E 2019-06-27T01:02:35.394540390Z   (ecto_sql) lib/ecto/adapters/sql.ex:446: Ecto.Adapters.SQL.init/3
 
E 2019-06-27T01:02:35.394543665Z   (ecto) lib/ecto/repo/supervisor.ex:162: Ecto.Repo.Supervisor.init/1
 
E 2019-06-27T01:02:35.394546780Z   (stdlib) supervisor.erl:295: :supervisor.init/1
 
E 2019-06-27T01:02:35.394550088Z   (stdlib) gen_server.erl:374: :gen_server.init_it/2
 
E 2019-06-27T01:02:35.394553207Z 
 
I 2019-06-27T01:02:35.399915601Z 01:02:35.398 [info] Running BeswickWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
 
I 2019-06-27T01:02:35.432168703Z 01:02:35.431 [info] Access BeswickWeb.Endpoint at http:
 
E 2019-06-27T01:02:36.711808Z Error while sending request to Stackdriver googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
W 2019-06-27T01:02:36.811614Z Error while fetching metric descriptors for kubelet: googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
I 2019-06-27T01:02:37.799999657Z 01:02:37.799 [info] CONNECT BeswickWeb.UserSocket
 
I 2019-06-27T01:02:37.800063791Z   Transport: :websocket
 
I 2019-06-27T01:02:37.800069680Z   Connect Info: %{}
 
I 2019-06-27T01:02:37.800073281Z   Parameters: %{"token" => "undefined", "vsn" => "2.0.0"}
 
I 2019-06-27T01:02:37.800539957Z 01:02:37.799 [info] Replied BeswickWeb.UserSocket :ok
 
E 2019-06-27T01:02:38.108971Z Error while sending request to Stackdriver googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
W 2019-06-27T01:02:38.204051Z Error while fetching metric descriptors for kubelet: googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
I 2019-06-27T01:02:38.484979952Z 01:02:38.484 [info] GET /
 
I 2019-06-27T01:02:38.490390184Z 01:02:38.489 [info] Sent 200 in 5ms
 
I 2019-06-27T01:02:40.080051510Z 01:02:40.079 [info] [swarm on beswick@127.0.0.1] [tracker:cluster_wait] joining cluster..
 
I 2019-06-27T01:02:40.080418176Z 01:02:40.079 [info] [swarm on beswick@127.0.0.1] [tracker:cluster_wait] no connected nodes, proceeding without sync
 
I 2019-06-27T01:02:40.096881324Z 01:02:40.096 [info] Already up
 
E 2019-06-27T01:02:40.824560Z Error while sending request to Stackdriver googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
I 2019-06-27T01:02:42.709119069Z 01:02:42.708 [info] JOIN "room:import" to BeswickWeb.ImportChannel
 
I 2019-06-27T01:02:42.709186505Z   Transport:  :websocket
 
I 2019-06-27T01:02:42.709190671Z   Serializer: Phoenix.Socket.V2.JSONSerializer
 
I 2019-06-27T01:02:42.709194296Z   Parameters: %{}
 
I 2019-06-27T01:02:42.709558879Z 01:02:42.709 [info] Replied room:import :ok
 
I 2019-06-27T01:02:43.107277328Z 01:02:43.106 [info] GET /
 
I 2019-06-27T01:02:43.112332858Z 01:02:43.111 [info] Sent 200 in 4ms
 
I 2019-06-27T01:02:48.485013378Z 01:02:48.484 [info] GET /
 
I 2019-06-27T01:02:48.488995282Z 01:02:48.488 [info] Sent 200 in 3ms
 
E 2019-06-27T01:02:49.406004Z Error while sending request to Stackdriver googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
E 2019-06-27T01:02:50.346103Z Error while sending request to Stackdriver googleapi: Error 403: Stackdriver Monitoring API has not been used in project 219123110372 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/monitoring.googleapis.com/overview?project=219123110372 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
I 2019-06-27T01:02:52.666284719Z 2019-06-27T01:02:52,665980795+00:00 limits.cpu needs updating. Is: '1', want: '1000m'.
 
I 2019-06-27T01:02:52.783902783Z 2019-06-27T01:02:52,783580346+00:00 Running: kubectl set resources -n kube-system ds fluentd-gcp-v3.2.0 -c fluentd-gcp --requests=cpu=100m,memory=200Mi --limits=cpu=1000m,memory=500Mi
 
E 2019-06-27T01:02:52.904936829Z error: info: {extensions v1beta1 daemonsets} "fluentd-gcp-v3.2.0" was not changed
 
```

Do you have any idea why this may have suddenly stopped working? Thanks for your feeedback!

**Comment by josevalim** [comment]
Unfortunately the error message is garbled but this is what it says:

> Migrations failed to run because the connection pool size is less than 2.
>
> Ecto requires a pool size of at least 2 to support concurrent migrators.
> When migrations run, Ecto uses one connection to maintain a lock and
> another to run migrations.
>
> If you are running migrations with Mix, you can increase the number
> of connections via the pool size option:
>
>    mix ecto.migrate --pool-size 2
>
> If you are running the Ecto.Migrator programmatically, you can configure
> the pool size via your application config.

So how are you running migrations? Your issue does not seem to be related
to timeout. But rather, you may have potentially upgraded Ecto or changed 
something else, which is causing this.

**Comment by JackSoby** [comment]
@josevalim We run migrations when the app starts up. I am not sure why it started running migrations during the middle of a product import, and I am also not sure why running removing the pool timeout fixed it. The last update I made to this code was on June 19th and it had nothing to do with ecto.

**Comment by josevalim** [comment]
If you are running migrations on start up, it means the app could have restarted and then failed to run migrations for some reasons. If you look at the logs, you can see the log error is happening during boot (which is why it is garbled).

In any case, [the `:pool_timeout` warnings are in Ecto for 7 months](https://github.com/elixir-ecto/ecto_sql/commit/09e896b672f3ccfe0df2c40577b05d959113aab9) and they are always checked when your app starts, so I don't see how they could have been started to show up out of nowhere. How far back can you check your logs to see if it was printed during initialization or not?

**Comment by JackSoby** [comment]
It looks like the first time that warning came up was about a month ago. It seems to me that what happened was we started our import, and put a heavy load on the database connection. Then it looks like our app restarted and our migrations failed, causing the import to fail. Any idea why a heavy data import would cause an app to restart? and why removing the pool timeout would solve this?

**Comment by josevalim** [comment]
Without looking at your application code, I can't say why a heavy import would cause your application to restart. Maybe something else in your supervision tree failed constantly, causing the application to terminate. You have to look at the logs to find out.

Removing pool_timeout was not supposed to affect any of this behaviour either and the migrations are failing due to the pool_size configuration. So maybe `pool_size` was removed/changed?

Here are my suggestions:

1. Make sure migrations are working by setting the proper pool size
2. Enable the relevant logs, if they are not yet enabled, so when the issue happens again, the errors are logged and the app can successfully restart

In any case, I don't believe this is an issue with Ecto. If it is, then we need more information so we can effectively reproduce the issue. Thank you.
