### ISSUE TITLE
Error in query with aggregate and virtual field

### ISSUE THREAD

**Issue by gabrielpra1** [elixir-ecto/ecto#3154]
# Environment

* Elixir version (elixir -v): 1.9.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.5
* Ecto version (mix deps): 3.2.4
* Database adapter and version (mix deps): postgrex 0.15.1
* Operating system: macOS 10.15

### Current behavior

After updating to ecto 3.2.4, the following query, which returns a sum of decimals into a virtual field started failing:

```elixir

  def get_invests_not_redeemed(user_id, fund_id, tokens_redeemed) do
    Repo.all(
      from ft in subquery(get_invests_with_accumulated_tokens_query(user_id, fund_id)),
      where: ft.accumulated_tokens > ^tokens_redeemed,
      order_by: ft.inserted_at
    )
  end

  def get_invests_with_accumulated_tokens_query(user_id, fund_id) do
    from ft in subquery(from FundTransaction, where: [user_id: ^user_id, fund_id: ^fund_id, type: ^:invest]),
    select: %{ft | accumulated_tokens: ft.number_of_tokens |> sum() |> over(order_by: ft.inserted_at)}
  end
```

```elixir
  schema "fund_transactions" do
    field :number_of_tokens, :decimal
    field :accumulated_tokens, :decimal, virtual: true
  end
```

The error:

```elixir
     test/sppyns/accounts_test.exs:26
     ** (FunctionClauseError) no function clause matching in Ecto.Type.cast_fun/1

     The following arguments were given to Ecto.Type.cast_fun/1:

         # 1
         {:maybe, :decimal}

     Attempted function clauses (showing 10 out of 22):

         defp cast_fun(:integer)
         defp cast_fun(:float)
         defp cast_fun(:boolean)
         defp cast_fun(:map)
         defp cast_fun(:string)
         defp cast_fun(:binary)
         defp cast_fun(:id)
         defp cast_fun(:binary_id)
         defp cast_fun(:any)
         defp cast_fun(:decimal)

     stacktrace:
       (ecto) lib/ecto/type.ex:731: Ecto.Type.cast_fun/1
       (ecto) lib/ecto/type.ex:728: Ecto.Type.cast/2
       (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1440: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/queryable.ex:161: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```

### Expected behavior

I believe the query should work, as it does in version 3.2.3. It's likely that the bug was introduced in https://github.com/elixir-ecto/ecto/commit/f01b270de91569dd56ad1673b62143580ce0422b.

**Comment by josevalim** [comment]
Thank you @gabrielpra1 for the report. Can you please try the v3.2 branch out and let us know if it is fixed there? If so, I will release a new version shortly after.

**Comment by gabrielpra1** [comment]
Yeah, that fixed it. Thank you @josevalim!
