### ISSUE TITLE
Postgrex error with date values in fragment

### ISSUE THREAD

**Issue by ckruse** [elixir-ecto/ecto#3234]
I don't even know if this is the right place to report this bug… if not, I'm sorry.

### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]
  
  Elixir 1.10.1 (compiled with Erlang/OTP 22)
  ```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.2
* Ecto version (mix deps): Ecto 3.3.3, ecto_sql 3.3.4
* Database adapter and version (mix deps): 0.15.3
* Operating system: macOS catalina

### Current behavior

Given this fragment:

~~~elixir
   min = ~D[2020-02-17]
    max = ~D[2020-02-17]

    from([{rel, binding_pos}] in q,
      where:
        fragment(
          "daterange(LEAST(?, ?), GREATEST(?, ?), '[]') && daterange(?, ?, '[]')",
          field(rel, ^field1),
          field(rel, ^field2),
          field(rel, ^field1),
          field(rel, ^field2),
          type(^min, :date),
          type(^max, :date)
        )
    )
~~~

I get the following error:

~~~
[error] GenServer #PID<0.1949.0> terminating
** (DBConnection.ConnectionError) client #PID<0.2193.0> stopped: ** (ArgumentError) Postgrex can only decode dates with days between 0 and 3652424, got: 33609267
    (postgrex 0.15.3) lib/postgrex/extensions/date.ex:46: Postgrex.Extensions.Date.day_to_elixir/1
    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Date"/6
    (postgrex 0.15.3) lib/postgrex/protocol.ex:2869: Postgrex.Protocol.rows_recv/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:1898: Postgrex.Protocol.recv_execute/5
    (postgrex 0.15.3) lib/postgrex/protocol.ex:1772: Postgrex.Protocol.bind_execute/4
    (db_connection 2.2.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.2.1) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection 2.2.1) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection 2.2.1) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
    (db_connection 2.2.1) lib/db_connection.ex:532: DBConnection.prepare_execute/4
    (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute!/4
    (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute/5
    (ecto 3.3.3) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto 3.3.3) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (termitool 0.79.19) lib/termitool_web/graphql/resolvers/staff/vacation_requests_resolver.ex:16: anonymous fn/2 in TermitoolWeb.GraphQL.Resolvers.Staff.VacationRequestsResolver.list/3
    (appsignal 1.11.5) lib/appsignal/instrumentation/decorators.ex:97: Appsignal.Instrumentation.Decorators.in_transaction/3
    (absinthe 1.4.16) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6

    (db_connection 2.2.1) lib/db_connection/connection.ex:168: DBConnection.Connection.handle_cast/2
    (connection 1.0.4) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 3.11.2) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.11.2) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:259: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.631180705.3808821250.149170>, %DBConnection.ConnectionError{message: "client #PID<0.2193.0> stopped: ** (ArgumentError) Postgrex can only decode dates with days between 0 and 3652424, got: 33609267\n    (postgrex 0.15.3) lib/postgrex/extensions/date.ex:46: Postgrex.Extensions.Date.day_to_elixir/1\n    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.\"Elixir.Postgrex.Extensions.Date\"/6\n    (postgrex 0.15.3) lib/postgrex/protocol.ex:2869: Postgrex.Protocol.rows_recv/4\n    (postgrex 0.15.3) lib/postgrex/protocol.ex:1898: Postgrex.Protocol.recv_execute/5\n    (postgrex 0.15.3) lib/postgrex/protocol.ex:1772: Postgrex.Protocol.bind_execute/4\n    (db_connection 2.2.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4\n    (db_connection 2.2.1) lib/db_connection.ex:1255: DBConnection.run_execute/5\n    (db_connection 2.2.1) lib/db_connection.ex:1342: DBConnection.run/6\n    (db_connection 2.2.1) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.2.1) lib/db_connection.ex:532: DBConnection.prepare_execute/4\n    (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute!/4\n    (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute/5\n    (ecto 3.3.3) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4\n    (ecto 3.3.3) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3\n    (termitool 0.79.19) lib/termitool_web/graphql/resolvers/staff/vacation_requests_resolver.ex:16: anonymous fn/2 in TermitoolWeb.GraphQL.Resolvers.Staff.VacationRequestsResolver.list/3\n    (appsignal 1.11.5) lib/appsignal/instrumentation/decorators.ex:97: Appsignal.Instrumentation.Decorators.in_transaction/3\n    (absinthe 1.4.16) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2\n    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1\n    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4\n    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6\n", severity: :error}, %Postgrex.Protocol{buffer: "", connection_id: 29763, connection_key: 1306645890, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.631180705.3808690178.149168>, peer: {{127, 0, 0, 1}, 5432}, postgres: {:idle, #Reference<0.631180705.3808690182.136241>}, queries: #Reference<0.631180705.3808821250.149165>, sock: {:gen_tcp, #Port<0.20>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.631180705.3808821250.149104>}}}}
State: {Postgrex.Protocol, %Postgrex.Protocol{buffer: "", connection_id: 29763, connection_key: 1306645890, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.631180705.3808690178.149168>, peer: {{127, 0, 0, 1}, 5432}, postgres: {:idle, #Reference<0.631180705.3808690182.136241>}, queries: #Reference<0.631180705.3808821250.149165>, sock: {:gen_tcp, #Port<0.20>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.631180705.3808821250.149104>}}}
~~~

When I change `min` and `max` to different dates, the query succeeds. But which values work and which don't seems like random to me, e.g. setting `min` to `~D[2020-01-01]` works but `~D[2020-02-01]` doesn't. Setting `min` to `~D[2020-01-01]` and  max to `~D[2020-02-01]` works.

### Expected behavior

It should work w/o error for all valid date values.

**Comment by wojtekmach** [comment]
> e.g. setting min to ~D[2020-01-01] works but ~D[2020-02-01] doesn't. Setting min to ~D[2020-01-01] and max to ~D[2020-02-01] works.

You showed a min/max combination for which it succeeds, what’s a min/max combination for which it fails?

**Comment by wojtekmach** [comment]
Oh, you've shared these earlier, please ignore my last comment.

**Comment by wojtekmach** [comment]
> ** (DBConnection.ConnectionError) client #PID<0.2193.0> stopped: ** (ArgumentError) Postgrex can only decode dates with days between 0 and 3652424, got: 33609267

```
iex> :calendar.gregorian_days_to_date(33609267)
{92019, 1, 18}
```

this value seems suspicious. Any chance you somehow ended up with such value in your DB? To remove unimportant details could you try reproducing this just using Postgrex? E.g. by adjusting the snippet below:

```
iex> {:ok, pid} = Postgrex.start_link([database: "wojtek"]); Postgrex.query!(pid, "select daterange(LEAST($1::date, $2::date), GREATEST($1::date, $2::date), '[]')", [min, max]).rows
[
  [
    %Postgrex.Range{
      lower: ~D[2020-02-17],
      lower_inclusive: true,
      upper: ~D[2020-02-18],
      upper_inclusive: false
    }
  ]
]
```

**Comment by ckruse** [comment]
Oh. I indeed have a value `20018-03-02` and a value `0218-06-04` in my database. Damn you, users…

**Comment by wojtekmach** [comment]
Gotcha, thanks for letting us know. Unfortunately we cannot represent `20018-03-02` in `%Date{}` so there's nothing we can do about it.

**Comment by ckruse** [comment]
No, that's an error in my data. Sorry for the noise and thanks for the pointer.
