### ISSUE TITLE
Ecto.SubQuery is calling a select statement on a virtual field of a struct

### ISSUE THREAD

**Issue by wilkinson4** [elixir-ecto/ecto#3240]
Elixir Version: 1.9.4
Ecto Version 3.3.4
Database: PostreSQL

Here is the subquery I am running
```Elixir
    where_patient_id = &where(&1, patient_id: ^patient_id)

    from(
      event in subquery(
        Encounter.as_timeline_event()
        |> where_patient_id.()
        |> union(^calls_as_timeline_event(patient_id))
        |> union(^tasks_as_timeline_event(patient_id))
        |> union(^(Hospitalization.as_timeline_event() |> where_patient_id.()))
        |> union(^(LTC.as_timeline_event() |> where_patient_id.()))
        |> union(^(SNF.as_timeline_event() |> where_patient_id.()))
        |> union(^(ResearchCase.as_timeline_event() |> where_patient_id.()))
        |> union(^(Discharge.as_timeline_event() |> where_patient_id.()))
        |> union(^(DischargeRecommendation.as_timeline_event() |> where_patient_id.()))
        |> union(^(Note.as_timeline_event() |> where_patient_id.()))
        |> union(^(Order.as_timeline_event() |> where_patient_id.()))
      ),
      order_by: [desc: event.event_date, desc: event.id]
    )
```

Here is the struct
```Elixir
  @primary_key {:id, :integer, []}
  typed_embedded_schema enforce: true do
    field(:category)
    field(:created_at, :naive_datetime_usec)
    field(:created_by_id)
    field(:created_by_name)
    field(:created_by_role)
    field(:reference_id)
    field(:event_date, :date)
    field(:notes, {:array, :map})
    field(:details, :map)
    field(:interpret_as_timestamp, :boolean, virtual: true)
  end
```

And here is an example from calls_as_timeline_event() where I am trying to pass interpret_as_timestamp = true
```Elixir
      select: %TimelineEvent{
        id: c.id,
        ...
        details:
          fragment(
            ~s"""
            (SELECT json_build_object(
              'callDisposition', ?, 'callIntent', ?, 'inbound', ?, 'phoneNumber', ?
            )) :: JSONB
            """,
            d.disposition,
            ci.label,
            a.inbound,
            c.phone_number
          ),
        interpret_as_timestamp: true
      }
```
Here is the query Ecto is running which is causing the issue, because interpret_as_timestamp is not a column in the database:

** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.interpret_as_timestamp does not exist

query: SELECT s0."id", s0."category", s0."created_at", s0."created_by_id", s0."created_by_name", s0."created_by_role", s0."reference_id", s0."event_date", s0."notes", s0."details", s0."interpret_as_timestamp" FROM (SELECT e0."id" AS "id", 'encounter' AS "category", e0."created_at" AS "created_at", u1."sfid" AS "created_by_id", u1."name" AS "created_by_name", u1."role_name__c" AS "created_by_role", e0."id"::varchar AS "reference_id", coalesce(coalesce(v5."cancelled_at", c6."start_at"), e0."created_at") AS "event_date", json_build_array(json_build_object('note', coalesce(v5."notes", c6."notes"))) :: JSONB AS "notes

**Comment by wilkinson4** [comment]
What we ended up doing to work around this in the query was:
```Elixir
interpret_as_timestamp: fragment("true")
```
This is obviously not an ideal way to handle this...

**Comment by josevalim** [comment]
Hi @wilkinson4, I could not reproduce this with simple queries, so there is probably something more going on here. Can you provide a sample minimal query that reproduces the error? Your query above is large and it doesn't have all pieces, therefore I can't fully reproduce it. Thanks!

**Comment by wilkinson4** [comment]
Here is the sql to generate test tables for this issue:
```SQL
CREATE TABLE test2 (
  id int
  , name varchar(255)
  , PRIMARY KEY (Id)
);

CREATE TABLE test1 (
  id int
  , name varchar(255)
  , PRIMARY KEY (Id)
);

INSERT INTO test1 (Id
  , name)
  VALUES (1
    , 'Joe');

INSERT INTO test2 (Id
  , Name)
  VALUES (1
    , 'Bob');
```
Here is the test.ex file I created
```Elixir
defmodule Test1 do
  @moduledoc false


  use TypedEctoSchema

  import Ecto.Query

  alias TestWithBoolean

  typed_schema "test1" do
    field(:name, :string)
  end

  def get_with_boolean do
    from(test1 in __MODULE__,
      select: %TestWithBoolean{
        id: test1.id,
        name: test1.name,
        is_true: true
      }
    )
  end
end

defmodule Test2 do
  @moduledoc false


  use TypedEctoSchema

  import Ecto.Query

  alias TestWithBoolean

  typed_schema "test2" do
    field(:name, :string)
  end

  def get_with_boolean do
    from(test2 in __MODULE__,
      select: %TestWithBoolean{
        id: test2.id,
        name: test2.name,
        is_true: false
      }
    )
  end
end

defmodule TestWithBoolean do
  @moduledoc false

  use TypedEctoSchema

  @primary_key {:id, :integer, []}
  typed_embedded_schema enforce: true do
    field(:name, :string)
    field(:is_true, :boolean, virtual: true) #THIS SHOULDN'T QUERY THE DB FOR THIS FIELD?
  end

end

defmodule CallSubquery do
  @moduledoc false

  import Ecto.Query

  alias Test1
  alias Test2

  def tests do
    from(
      tests in subquery(
        Test1.get_with_boolean()
        |> union(^(Test2.get_with_boolean()))
      )
    )
  end
end
```

When I run ```CallSubquery.tests() |> Repo.all()``` in iex I get the following error message:

```
** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.is_true does not exist

    query: SELECT s0."id", s0."name", s0."is_true" FROM (SELECT t0."id" AS "id", t0."name" AS "name" FROM "test1" AS t0 UNION (SELECT t0."id", t0."name" FROM "test2" AS t0)) AS s0
    (ecto_sql 3.3.2) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.3.2) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto 3.3.2) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto 3.3.2) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```
