### ISSUE TITLE
Newly added :cache_statement breaks migration commands

### ISSUE THREAD

**Issue by sezaru** [elixir-ecto/ecto#3285]
### Environment

* Elixir version (elixir -v): 1.10.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.2
* Ecto version (mix deps): master
* Database adapter and version (mix deps): postgrex 0.15.1
* Operating system: Ubuntu 19.04

### Current behavior

After adding `cache_statement: :per_operation` to my repo config, `mix ecto.drop` raises with error:

```elixir
λ mix ecto.drop
Compiling 3 files (.ex)
Generated friends app

15:50:38.200 [error] Task #PID<0.94.0> started from #PID<0.247.0> terminating
** (ArgumentError) argument error
    :erlang.iolist_to_binary(:per_operation)
    (postgrex 0.15.3) lib/postgrex/query.ex:59: DBConnection.Query.Postgrex.Query.parse/2
    (db_connection 2.2.1) lib/db_connection.ex:1122: DBConnection.parse/3
    (db_connection 2.2.1) lib/db_connection.ex:531: DBConnection.prepare_execute/4
    (postgrex 0.15.3) lib/postgrex.ex:202: Postgrex.query/4
    (ecto_sql 3.4.3) lib/ecto/adapters/postgres.ex:267: anonymous fn/2 in Ecto.Adapters.Postgres.run_query/2
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<7.60197958/0 in Ecto.Adapters.Postgres.run_query/2>
    Args: []
** (Mix) The database for Friends.Repo couldn't be dropped: an exception was raised:
    ** (ArgumentError) argument error
        :erlang.iolist_to_binary(:per_operation)
        (postgrex 0.15.3) lib/postgrex/query.ex:59: DBConnection.Query.Postgrex.Query.parse/2
        (db_connection 2.2.1) lib/db_connection.ex:1122: DBConnection.parse/3
        (db_connection 2.2.1) lib/db_connection.ex:531: DBConnection.prepare_execute/4
        (postgrex 0.15.3) lib/postgrex.ex:202: Postgrex.query/4
        (ecto_sql 3.4.3) lib/ecto/adapters/postgres.ex:267: anonymous fn/2 in Ecto.Adapters.Postgres.run_query/2
        (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
```

The same occurs with `cache_statement: :per_schema`.

My test was done using the [Getting Started](https://hexdocs.pm/ecto/getting-started.html) tutorial only changing the config to:
```elixir
config :friends, Friends.Repo,
  database: "friends_repo",
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  cache_statement: :per_operation
```

**Comment by josevalim** [comment]
Thanks! I will take a look!

**Comment by josevalim** [comment]
Thanks, I have renamed the option to `cache_write_statements: :per_operation` to avoid conflicts. Please let us know how it goes!

**Comment by sezaru** [comment]
That fixed it! Thanks you so much for the quick response and fix!
