### ISSUE TITLE
id in ^subquery does not work

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#3361]
### Environment

* Elixir version (elixir -v): 1.10.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PG 11
* Ecto version (mix deps): 3.4.5
* Database adapter and version (mix deps): 3.4.5
* Operating system: Mac OS

### Current behavior

Fro the documentation I expected that Ecto is able to do `id in ^subquery` kind of queries but this does not seem to work:

```
** (Ecto.Query.CastError) query.ex:113: value `#Ecto.Query<from p0 in Domain.Mes
saging.Conversation.Topic.Participant, as: :participants, where: p0.assignment_id == ^"8876497c-4bf7-463b-b5a9-db3a250592dc", select: p0.
topic_id>` in `where` cannot be cast to type {:in, :binary_id} in query:

     from c0 in Domain.Messaging.Conversation,
       as: :conversation,
       left_join: t1 in Domain.Messaging.Conversation.Topic,
       on: t1.id == c0.topic_id,
       join: m2 in Domain.Messaging.Message,
       on: m2.id == c0.last_message_id,
       where: c0.type != "topic" or t1.is_public == true or t1.id in ^#Ecto.Query<from p0 in Domain.Messaging.Conversation.Topic
.Participant, as: :participants, where: p0.assignment_id == ^"8876497c-4bf7-463b-b5a9-db3a250592dc", select: p0.topic_id>,
       order_by: [desc: coalesce(m2.sent_at, m2.inserted_at)],
       order_by: [desc: c0.id],
       limit: ^51,
       select: c0,
       preload: [topic: t1, last_message: m2]

     code: assert {:ok, [], _cursor} = list_conversations_for_account(account, subject)
     stacktrace:
       (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir 1.10.2) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.10.2) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.4.5) lib/ecto/repo/queryable.ex:176: Ecto.Repo.Queryable.execute/4
       (ecto 3.4.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```

Both `p0.topic_id` and `t1.id` are UUID's. 

Documentation:

```
subset = from(p in subset, select: p.id)
Repo.update_all(
  from(p in Post, where: p.id in subquery(subset)),
  set: [sync_started_at: NaiveDateTime.utc_now()]
)
```

**Comment by josevalim** [comment]
What is your full query? It seems you are missing the subquery call:

    where: p.id in subquery(subset))
                   ^^^^^^^^

**Comment by AndrewDryga** [comment]
You are right, I was missing that part (error could be better though to give a hint for this). After adding subquery issue did not go away though:

```
  def only_where_subject_is_not_participant(queryable \\ conversation(), %Subject{} = subject) do
    queryable
    |> with_preloaded_topic_participants()
    |> where(
      [conversation: conversation, topic_participants: topic_participants],
      conversation.type == "topic" and
        conversation.topic_id not in ^subquery(topic_ids_where_subject_participates(subject))
    )
  end

  defp topic_ids_where_subject_participates(%Subject{assignment: %Assignment{} = assignment}) do
    from(Topic.Participant, as: :participants)
    |> where([participants: participants], participants.assignment_id == ^assignment.id)
    |> select([participants: participants], participants.topic_id)
  end
```

The error now is:
```
** (Ecto.Query.CastError) query.ex:113: value `%Ecto.SubQuery{cache: nil, params: nil, qu
ery: #Ecto.Query<from p0 in Domain.Messaging.Conversation.Topic.Participant, as: :participants, where: p0.assignment_id == ^"529
cfced-c3dc-4594-867b-0fa22d945857", select: p0.topic_id>, select: nil}` in `where` cannot be cast to type {:in, :binary_id} in query:

     from c0 in Domain.Messaging.Conversation,
       as: :conversation,
       left_join: t1 in Domain.Messaging.Conversation.Topic,
       on: t1.id == c0.topic_id,
       join: m2 in Domain.Messaging.Message,
       on: m2.id == c0.last_message_id,
       where: c0.type != "topic" or t1.is_public == true or t1.id in ^%Ecto.SubQuery{cache: nil, params: nil, query: #Ecto.Query<from p0
in Domain.Messaging.Conversation.Topic.Participant, as: :participants, where: p0.assignment_id == ^"529cfced-c3dc-4594-867b-0fa2
2d945857", select: p0.topic_id>, select: nil},
       order_by: [desc: coalesce(m2.sent_at, m2.inserted_at)],
       order_by: [desc: c0.id],
       limit: ^51,
       select: c0,
       preload: [topic: t1, last_message: m2]
```

**Comment by AndrewDryga** [comment]
You are right @josevalim, thank you ❤️. Maybe we can improve error message for cases where `subquery` is missing or it's used as `^subquery(...)` inside `where`?

**Comment by josevalim** [comment]
Improving the error message sounds good. :)
