### ISSUE TITLE
KeyError :type not found on Ecto 3.5.3

### ISSUE THREAD

**Issue by tomtaylor** [elixir-ecto/ecto#3457]
### Environment

* elixir: 1.11.1
* DB: PG 13.0
* ecto: 3.5.3
* ecto_sql: 3.5.1
* postgrex: 0.15.7
* OS: MacOS Catalina

### Current behavior

I'm running a complex query with window functions and a couple of CTEs over an `employers` table that contains `rating` and `name` columns to produce a ranked list.

```elixir
  def list_ranked_employers_around(ids, employer_id, count) when is_list(ids) do
    ranking_sq = joint_subquery(ids)

    # A CTE that returns the row number for the employer in question from the ranked list
    row_sq =
      from(r in subquery(ranking_sq),
        select: r.row_number,
        where: r.employer_id == ^employer_id
      )

    Employer
    |> with_cte("ranked_employers", as: ^ranking_sq)
    |> with_cte("target_rows", as: ^row_sq)
    |> join(:inner, [e], re in "ranked_employers", on: e.id == re.employer_id)
    |> join(:inner, [e, re], target_rows in "target_rows",
      on: fragment("abs(?)", re.row_number - target_rows.row_number) <= ^count - 1
    )
    |> order_by([e, re, tr], asc: re.ranking, asc: e.name)
    |> select([e, re, tr], %{employer: e, ranking: re.ranking, joint: re.joint})
    |> Repo.all()
    |> truncate_list_around_employer_id(employer_id, count)
  end

  # Extends the `ranking_subquery/1` to include the joint flag
  defp joint_subquery(ids) do
    sq = ranking_subquery(ids)

    from(e in subquery(sq),
      windows: [row_number: [order_by: e.row_number]],
      select: %{
        employer_id: e.employer_id,
        ranking: e.ranking,
        row_number: e.row_number,
        # Work out if this ranking is shared with any either side of it, making it a 'joint' position
        joint:
          coalesce(
            fragment(
              "? = ? OR ? = ?",
              e.ranking,
              over(lead(e.ranking), :row_number),
              e.ranking,
              over(lag(e.ranking), :row_number)
            ),
            false
          )
      }
    )
  end

  defp ranking_subquery(ids) do
    Employer
    |> order_by([e],
      # When employers share the same rating within our desired precision, sort alphabetical by name
      desc_nulls_last: fragment("round(?, ?)", e.rating, @rating_precision),
      asc: e.name
    )
    |> where([e], e.id in ^ids)
    |> windows([e],
      rating: [
        order_by: [desc_nulls_last: fragment("round(?, ?)", e.rating, @rating_precision)]
      ]
    )
    |> select(
      [e],
      %{
        employer_id: e.id,
        # Don't return a rank when the rating is null
        ranking:
          fragment(
            "CASE WHEN ? IS NULL THEN NULL ELSE ? END",
            e.rating,
            over(rank(), :rating)
          ),
        row_number: over(row_number(), :rating)
      }
    )
  end
```

This was working correctly in Ecto 3.5.2, but fails in Ecto 3.5.3 with the following error:

```
** (KeyError) key :type not found in: []
     code: employer_rankings = EmployerRankings.list_ranked_employers_around(ids, b.id, count)
     stacktrace:
       (elixir 1.11.1) lib/keyword.ex:420: Keyword.fetch!/2
       (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.5.3) lib/ecto/repo/queryable.ex:213: Ecto.Repo.Queryable.execute/4
       (ecto 3.5.3) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
       (poplar 0.0.1) lib/poplar/employer_rankings/employer_rankings.ex:104: Poplar.EmployerRankings.list_ranked_employers_around/3
```

### Expected behavior

I would expect this to return correctly.

**Comment by josevalim** [comment]
Fixed in master, GitHub will catch up and add a reference to the commit soon. :)

**Comment by tomtaylor** [comment]
Thanks! Sorry, I can't see which commit fixes it?

**Comment by josevalim** [comment]
f36e0285fe10
