### ISSUE TITLE
Ecto.QueryError when using parent_as/1 in select

### ISSUE THREAD

**Issue by yunmikun2** [elixir-ecto/ecto#3550]
## Environment

Elixir:

```
$ elixir --version
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 21)
```

PostgreSQL:

```sql
postgres=# select version();
                                   version                                    
------------------------------------------------------------------------------
 PostgreSQL 13.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.0, 64-bit
(1 row)
```

Deps:

ecto: v3.5.6
ecto_sql: v3.5.4
postgrex: 0.15.8

Operating System: Arch Linux

```
$ uname -a
Linux yunmikun2 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 x86_64 GNU/Linux
```

## Current behaviour

First, we build a subquery that uses `parent_as/1` under the `:select`
key in the `Ecto.Query.from/2` macro:

```elixir
iex(1)> sq = from percent in "percents", where: percent.id == parent_as(:value).id, select: %{value: parent_as(:value).value * percent.percent}
#Ecto.Query<from p0 in "percents", where: p0.id == parent_as(:value).id,
 select: %{value: parent_as(:value).value * p0.percent}>
```

Then we join this as a subquery with lateral join:

```elixir
iex(2)> q = from value in "values", as: :value, inner_lateral_join: computed in subquery(sq), select: %{id: value.id, computed: computed.value}
#Ecto.Query<from v0 in "values", as: :value,
 join_lateral: p1 in subquery(from p0 in "percents",
  where: p0.id == parent_as(:value).id,
  select: %{value: parent_as(:value).value * p0.percent}),
 on: true, select: %{id: v0.id, computed: p1.value}>
```

As far, everything goes normally, but when we try to execute such a
query (or simply translate it into a SQL string), we get an error:

```elixir
iex(3)> MyApp.Repo.to_sql(:all, q)
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (Ecto.QueryError) `parent_as(:value)` can only be used in subqueries in query:
     
    from p0 in "percents",
      where: p0.id == parent_as(:value).id,
      select: %{value: parent_as(:value).value * p0.percent}
    

The subquery originated from the following query:

from v0 in "values",
  as: :value,
  join_lateral: p1 in subquery(from p0 in "percents",
  where: p0.id == parent_as(:value).id,
  select: %{value: parent_as(:value).value * p0.percent}),
  on: true,
  select: %{id: v0.id, computed: p1.value}

    (ecto 3.5.6) lib/ecto/adapter/queryable.ex:110: Ecto.Adapter.Queryable.prepare_query/3
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.to_sql/3
```

## Expected behavior

Regardless of usefullness of this code in real life, one of the
following options should be chosen (I guess):
  1) consider this a bug as there is an equivalent SQL expression
     which is valid in SQL;
  2) we mark in the docs that usage of `parent_as/1` is dissallowed in
     select clause.

## Etc

Forementioned SQL expression that's valid:

```sql
SELECT v.id,
       c."value"
  FROM "values" v
         JOIN LATERAL (
           SELECT v."value" * p.percent AS "value"
             FROM percents p WHERE p.id = v.id
         ) c
         ON true;
```

Way to check and test it works if you're lazy:

```sql
create database test;
\c test;
create table values (id bigserial primary key, value integer);
create table percents (id bigserial primary key, percent integer);
insert into values (value) values (1), (2), (3);
insert into percents (percent) values (1), (2), (3);
```

**Comment by josevalim** [comment]
Correct. I have recently commit something that makes it clear this is not currently supported: https://github.com/elixir-ecto/ecto/commit/8d7625e257d6f7b05b6fe1fe6db05c2692e38e31 Thanks!

**Comment by josevalim** [comment]
However, it works if you are referring to *from* and not another join, if you are using master: https://github.com/elixir-ecto/ecto/commit/ce90e4eb160a668404bb6921724481367cff8f64

**Comment by yunmikun2** [comment]
>  it works if you are referring to `from`
Nice. Hope we'll get support for joins in the future too. Thanks!
