### ISSUE TITLE
Ecto.Enum does not work with module attributes

### ISSUE THREAD

**Issue by sheharyarn** [elixir-ecto/ecto#3556]
### Environment

* Elixir version: 1.11.2
* Erlang version: 23.1
* Database: Postgres 12.3
* Ecto version: 3.5.7
* Database adapter: ecto_sql 3.5.4
* Operating system: macOS Catalina 10.15.7

### Current behavior

With the following schema, the application fails to compile. It works with module attributes directly on the schema fields but not for embedded schema fields. It works as expected when the `values:` option is provided an atom list for `:auth_mode` inside the `Settings` embed:

```elixir
defmodule MyApp.User do
  use Ecto.Schema

  @user_types [:normal, :admin, :guest]
  @auth_mode [:password, :sso]

  schema "users" do
    field :name, :string
    field :email, :string
    field :type, Ecto.Enum, values: @user_types

    embeds_one(:settings, Settings) do
      field :language, :string
      field :auth_mode, Ecto.Enum, values: @auth_mode
    end
  end
end
```

This is the error I get:

```
== Compilation error in file lib/my_app/user.ex ==
** (ArgumentError) Ecto.Enum types must have a values option specified as a list of atoms. For example:

    field :my_field, Ecto.Enum, values: [:foo, :bar]

    (ecto 3.5.7) lib/ecto/enum.ex:50: Ecto.Enum.init/1
    (ecto 3.5.7) lib/ecto/schema.ex:2094: Ecto.Schema.check_field_type!/4
    (ecto 3.5.7) lib/ecto/schema.ex:1801: Ecto.Schema.__field__/4
    lib/my_app/user.ex:103: (module)
    (ecto 3.5.7) lib/ecto/schema.ex:1947: Ecto.Schema.__embeds_module__/4
    lib/my_app/user.ex:102: (module)
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
```

### Expected behavior

Should work with module attributes for fields inside embeds too.

**Comment by sheharyarn** [comment]
Happy to send in a PR that fixes this if someone can point me in the right direction.

**Comment by Eiji7** [comment]
For me it works:
```elixir
iex> Mix.install [:ecto_sql]
:ok
iex> defmodule MyApp.User do
...>   use Ecto.Schema
...> 
...>   @user_types [:normal, :admin, :guest]
...> 
...>   schema "users" do
...>     field :name, :string
...>     field :email, :string
...>     field :type, Ecto.Enum, values: @user_types
...>   end
...> end
{:module, MyApp.User,
 <<70, 79, 82, 49, 0, 0, 15, 92, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 195,
   0, 0, 0, 47, 17, 69, 108, 105, 120, 105, 114, 46, 77, 121, 65, 112, 112, 46,
   85, 115, 101, 114, 8, 95, 95, 105, 110, ...>>,
 [
   __schema__: 1,
   __schema__: 1,
   __schema__: 1,
   __schema__: 1,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2,
   __schema__: 2
 ]}
iex> MyApp.User.__schema__(:type, :type)
{:parameterized, Ecto.Enum,
 %{
   on_dump: %{admin: "admin", guest: "guest", normal: "normal"},
   on_load: %{"admin" => :admin, "guest" => :guest, "normal" => :normal},
   values: [:normal, :admin, :guest]
 }}
```
Could you please give more details?

**Comment by sheharyarn** [comment]
Sorry, I previously posted an incomplete example. Module attributes do not work when using them _inside_ embeds. Update the original issue to reflect that.

**Comment by Eiji7** [comment]
@sheharyarn Looks like everything works as expected.

Please look that `embeds_one` defines module inside that module, so accessing `@auth_modes` returns `warning` (in console) and `nil` (as result).

This code works:
```elixir
defmodule MyApp.User do
  use Ecto.Schema

  @user_types [:normal, :admin, :guest]

  schema "users" do
    field :name, :string
    field :email, :string
    field :type, Ecto.Enum, values: @user_types

    embeds_one(:settings, Settings) do
      @auth_mode [:password, :sso]
      field :language, :string
      field :auth_mode, Ecto.Enum, values: @auth_mode
    end
  end
end
```

What's more interesting variables are not accessible:
```elixir
defmodule MyApp.User do
  use Ecto.Schema

  auth_mode = [:password, :sso]
  @user_types [:normal, :admin, :guest]

  schema "users" do
    field :name, :string
    field :email, :string
    field :type, Ecto.Enum, values: @user_types

    embeds_one(:settings, Settings) do
      field :language, :string
      field :auth_mode, Ecto.Enum, values: auth_mode
    end
  end
end
```
produces:
```elixir
warning: variable "auth_mode" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:5: MyApp.User

warning: variable "auth_mode" does not exist and is being expanded to "auth_mode()", please use parentheses to remove the ambiguity or change the variable name
  iex:15: MyApp.User.Settings

** (CompileError) iex:15: undefined function auth_mode/0
    (stdlib 3.14) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.14) lists.erl:1359: :lists.mapfoldl/3
    (ecto 3.5.6) expanding macro: Ecto.Schema.field/3
```
however I have no idea how to fix it.

**Comment by wojtekmach** [comment]
As @Eiji7 said, inline `embeds_*` define a new module which means we can't access module attributes from the parent module using `@`.

We could however do this:

```elixir
Mix.install([
  :ecto
])

defmodule Post do
  use Ecto.Schema

  @colors [:red, :green, :blue]

  schema "posts" do
    field(:color, Ecto.Enum, values: @colors)

    embeds_many :tags, Tag do
      field(:color, Ecto.Enum, values: Module.get_attribute(Post, :colors))
                                     # ^^^
                                     # Module.get_attribute instead of @
    end
  end
end
```

I'm not sure if we can do anything to improve things so gonna close it.

**Comment by Eiji7** [comment]
@wojtekmach Could you please explain what happens with a variable in parent module as I found above?

```elixir
iex> Mix.install([:ecto_sql])
:ok
iex> defmodule Post do
iex>   use Ecto.Schema
iex> 
iex>   colors = [:red, :green, :blue]
iex> 
iex>   schema "posts" do
iex>     field :color, Ecto.Enum, values: colors
iex> 
iex>     embeds_many :tags, Tag do
iex>       field :color, Ecto.Enum, values: colors
iex>     end
iex>   end
iex> end

warning: variable "colors" does not exist and is being expanded to "colors()", please use parentheses to remove the ambiguity or change the variable name
  iex:12: Post.Tag

** (CompileError) iex:12: undefined function colors/0
    (stdlib 3.14) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.14) lists.erl:1359: :lists.mapfoldl/3
    (ecto 3.5.6) expanding macro: Ecto.Schema.field/3
```

**Comment by josevalim** [comment]
@Eiji7 Ecto is creating the module internally instead of emitting the AST that compiles a module, so the scope of the parent does not become available inside embeds_many. It could be fixed but I am not very sure if it is worth it.

**Comment by Eiji7** [comment]
@josevalim Ah, I see - I guessed that `Module.create/3` was just a nice API. Just checked its source and now it makes sense, thanks!

**Comment by sheharyarn** [comment]
Got it, thanks for the clarification!
