### ISSUE TITLE
Document that the shared option `timeout` needs to be an integer (or definitely not a float)?

### ISSUE THREAD

**Issue by kenny-evitt** [elixir-ecto/ecto#3580]
### Environment

* Elixir version (elixir -v):

```
$ elixir -v
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 21)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL (via `psql`):

```
# SELECT version();
                                                      version                                                       
--------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.3 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.17), 64-bit
(1 row)
```

* Ecto version (mix deps):
* Database adapter and version (mix deps):

```
...
* ecto 3.5.7 (Hex package) (mix)
  locked at 3.5.7 (ecto) 04c4e69d
  ok
* ecto_sql 3.5.4 (Hex package) (mix)
  locked at 3.5.4 (ecto_sql) 1fff1a28
  ok
...
```

* Operating system:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
```

### Current behavior

I observed some errors.

This code does NOT seem to be particularly relevant to the errors I observed, but I'm including it here as I *initially* suspected that there was a problem with it:

```elixir
defmodule MyApp.Time do

  @doc """
  Calls the given function and returns a tuple consisting of the function's return value and the
  number of microseconds of the call's duration
  """
  @spec call_with_timing( (-> any) ) :: {any, integer}
  def call_with_timing(f) do
    start = System.monotonic_time()
    return = f.()
    stop = System.monotonic_time()
    duration = System.convert_time_unit(stop - start, :native, :microsecond)
    {return, duration}
  end

end


defmodule MyApp.SomeModule do

  alias MyApp.Time

  def delete_old_items do
    old_items_q = old_items_query()

    query_timeout_ms =
      2
      |> Timex.Duration.from_hours()
      |> Timex.Duration.to_milliseconds()

    {_results, duration} =
      Time.call_with_timing(
        fn ->
          (
            from ci in MyApp.ChildItems,
            join: p in ^subquery( old_items_q ),
            on: [id: ci.item_id]
          )
          |> Repo.delete_all(timeout: query_timeout_ms)
        end
      )

    Logger.info "Deleted old child items in #{duration |> Time.format_timing_duration()}"

    ...

  end

end
```

I was seeing errors like this when calling `MyApp.SomeModule.delete_old_items/0:

```
** (ArgumentError) argument error
    :erlang.start_timer(-576453337409.0, #PID<0.1405.0>, {#Reference<0.2500094440.3088449537.4941>, #Reference<0.2500094440.3088449537.13627>, #PID<0.1743.0>, 7.2e6}, [abs: true])
    (db_connection 2.3.1) lib/db_connection/holder.ex:391: DBConnection.Holder.start_deadline/5
    (db_connection 2.3.1) lib/db_connection/holder.ex:255: DBConnection.Holder.checkout_call/5
    (db_connection 2.3.1) lib/db_connection/holder.ex:59: DBConnection.Holder.checkout/2
    (db_connection 2.3.1) lib/db_connection.ex:1046: DBConnection.checkout/3
    (db_connection 2.3.1) lib/db_connection.ex:1357: DBConnection.run/6
    (db_connection 2.3.1) lib/db_connection.ex:557: DBConnection.parsed_prepare_execute/5
    (db_connection 2.3.1) lib/db_connection.ex:550: DBConnection.prepare_execute/4
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:692: Ecto.Adapters.SQL.execute!/4
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
    (my_app 0.0.1) lib/my_app/time.ex:10: MyApp.Time.call_with_timing/1
    (my_app 0.0.1) lib/my_app/some_module.ex:12: MyApp.SomeModule.delete_old_items/0
```

### Expected behavior

I did not expect the code to throw an error!

I immediately suspected my own code, and perhaps some kind of problem with my timing code – perhaps it was interfering with Ecto's own timing?

It turned out that this chunk was the problem:

```elixir
    query_timeout_ms =
      2
      |> Timex.Duration.from_hours()
      |> Timex.Duration.to_milliseconds()
```

`Timex.Duration.to_milliseconds/1` returns a `float` value.

I added `|> trunc()` to the pipeline and that fixed it. (There's also `Timex.Duration.to_milliseconds/2`, which supports a `:truncate` option too.)

There's no spec for the "shared options" for the various `Ecto.Repo` functions/callbacks, but maybe we could just add a note in the docs for the `:timeout` option?

**Comment by josevalim** [comment]
Yes please, PR is welcome!
