### ISSUE TITLE
Repo parallel preloading fails in test environment when used within Repo.checkout/2

### ISSUE THREAD

**Issue by pedroassumpcao** [elixir-ecto/ecto#3584]
### Environment

* Elixir version (elixir -v): 1.11.3 (OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 12
* Ecto version (mix deps): 3.5.8
* Database adapter and version (mix deps): Postgrex 0.15.8
* Operating system: Mac OS Big Sur

### Current behavior

Repo parallel preloading fails in the Sandbox when running inside `Repo.checkout/2`. For context, in my case in particular, I am using `Repo.checkout/2` to run operations using PG advisory lock in a session and that is why I need a separated connection.

### How to reproduce

In any application that contains a schema with more than one association, if you add a test that runs `Repo.checkout/2`, fetch a record and preload more than one association, it will trigger parallel preloading, and it will fail something similar to:

```bash
09:29:38.913 [error] Task #PID<0.585.0> started from #PID<0.578.0> terminating
** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.578.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 10972ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto 3.5.8) lib/ecto/repo/preloader.ex:229: Ecto.Repo.Preloader.fetch_query/8
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<8.125872509/1 in Ecto.Repo.Preloader.maybe_pmap/3>, [#Function<18.125872509/1 in Ecto.Repo.Preloader.prepare_queries/6>]]
09:29:38.913 [error] Task #PID<0.584.0> started from #PID<0.578.0> terminating
** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.578.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 10972ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto 3.5.8) lib/ecto/repo/preloader.ex:229: Ecto.Repo.Preloader.fetch_query/8
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<8.125872509/1 in Ecto.Repo.Preloader.maybe_pmap/3>, [#Function<18.125872509/1 in Ecto.Repo.Preloader.prepare_queries/6>]]
09:29:38.920 [error] Postgrex.Protocol (#PID<0.507.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.578.0> exited

  1) test gets a post preloading the comments (EctoBug.PostTest)
     test/ecto_bug/post_test.exs:26
     ** (EXIT from #PID<0.578.0>) an exception was raised:
         ** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.578.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 10972ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
             (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
             (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
             (ecto 3.5.8) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
             (ecto 3.5.8) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
             (ecto 3.5.8) lib/ecto/repo/preloader.ex:229: Ecto.Repo.Preloader.fetch_query/8
             (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
             (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
             (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

These are the steps to create a brand new application for the mentioned scenario:

1. mix phx.new ecto_bug
2. cd ecto_bug
3. mix ecto.create
4. mix phx.gen.schema Blog.Post posts title
5. mix ecto.migrate
6. mix phx.gen.schema Blog.Comment comments content:text post_id:references:posts
7. mix ecto.migrate
8. mix phx.gen.schema Blog.Read reads read_at:datetime post_id:references:posts
9. mix ecto.migrate
10. add has_many(:comments, EctoBug.Blog.Comment) in Post
11. add has_many(:reads, EctoBug.Blog.Read) in Post
12. cast post_id in Comment changeset
13. cast post_id in Read changeset

Then, with a test like this the bug will be exposed (it does not matter if `async` is set or not):

```elixir
defmodule EctoBug.PostTest do
  use EctoBug.DataCase, async: true

  alias EctoBug.Blog.{Comment, Post, Read}
  alias EctoBug.Repo

  setup do
    {:ok, post} =
      %Post{}
      |> Post.changeset(%{title: "Blog Title"})
      |> Repo.insert()

    {:ok, comment} =
      %Comment{}
      |> Comment.changeset(%{post_id: post.id, content: "Just a comment."})
      |> Repo.insert()

    {:ok, read} =
      %Read{}
      |> Read.changeset(%{post_id: post.id, read_at: NaiveDateTime.utc_now()})
      |> Repo.insert()

    %{post: post, comment: comment, read: read}
  end

  test "gets a post preloading the comments", %{post: post, comment: comment, read: read} do
    post_with_preloads =
      Post
      |> Repo.get(post.id)
      |> Repo.preload([:comments, :reads])

    assert comment in post_with_preloads.comments
    assert read in post_with_preloads.reads

    post_with_preloads_checkout =
      Repo.checkout(fn ->
        Post
        |> Repo.get(post.id)
        |> Repo.preload([:comments, :reads])
      end)

    assert comment in post_with_preloads_checkout.comments
    assert read in post_with_preloads_checkout.reads
  end
end
```

### Temporary solution

If we turn off parallel preloading when running tests, everything works fine:

```elixir
defmodule EctoBug.Repo do
  use Ecto.Repo,
    otp_app: :ecto_bug,
    adapter: Ecto.Adapters.Postgres

  def default_options(operation) do
    case Mix.env() do
      :test -> super(operation) ++ [in_parallel: false]
      _env -> super(operation)
    end
  end
end
```

### Extra information

- there was no change in the test `DataCase` module, I am using the same one the generator creates;
- I did some attempts using `queue_target` and `queue_interval` in the Repo test config with no different results, as I saw other similar issues with dynamic repo and replicas;

### Expected behavior

Repo parallel preloading in `test` works exact the same as `dev` and `prod` environments, within `Repo.checkout/2` or not, without any need for overriding `Repo.preload/3`.

**Comment by v0idpwn** [comment]
Hello, @pedroassumpcao. Your instructions to reproduce the issue are very clear, but could you create a sample repository with this failing test? It would help me a lot in my attempt to understand and maybe fix this issue :)

**Comment by pedroassumpcao** [comment]
@v0idpwn yes, no problem. I pushed to https://github.com/pedroassumpcao/ecto_bug. The last commit has the override that fixes the issue and make the tests pass. If you revert to the last commit and run the tests you will see the tests failing.
