### ISSUE TITLE
Can't find named binding in CTE subquery with parent_as/1

### ISSUE THREAD

**Issue by joaopaulobdac** [elixir-ecto/ecto#3619]
### Environment

* Elixir version: 1.11.3
* Database and version: PostgreSQL 13
* Ecto version: 3.6.1
* Database adapter and version: postgrex 0.15.8
* Operating system: Arch Linux Kernel 5.11.15

### Current behavior

I'm trying to convert the following query from SQL to elixir:

```sql
SELECT g."name", breadcrumbs."names" AS "query_test" FROM "groups" AS g
LEFT JOIN LATERAL (
  -- breadcrumbs_query
  WITH RECURSIVE "breadcrumbs" AS (
    -- breadcrumbs_initial_query
    SELECT sg0."id", sg0."name", sg0."supergroup_id" FROM "groups" AS sg0
    WHERE sg0."id" = g."id"
    UNION ALL (
      -- breadcrumbs_recursion_query
      SELECT sg1."id", sg1."name", sg1."supergroup_id" FROM "groups" AS sg1
      INNER JOIN "breadcrumbs" AS b ON b."supergroup_id" = sg1."id"
    )
  )
  SELECT array_agg("name") AS "names" FROM "breadcrumbs"
) AS breadcrumbs ON TRUE;
```

Sample result:

```
+-----------------------+------------------------------------------------------------------------+
| name                  | query_test                                                             |
|-----------------------+------------------------------------------------------------------------|
| Supergroup            | ['Supergroup']                                                         |
| Subgroup 1            | ['Subgroup 1', 'Supergroup']                                           |
| Subgroup 1.1          | ['Subgroup 1.1', 'Subgroup 1', 'Supergroup']                           |
| Subgroup 1.1.1        | ['Subgroup 1.1.1', 'Subgroup 1.1', 'Subgroup 1', 'Supergroup']         |
| Subgroup 1.1.2        | ['Subgroup 1.1.2', 'Subgroup 1.1', 'Subgroup 1', 'Supergroup']         |
+-----------------------+------------------------------------------------------------------------+
```

And here's the query in elixir:

```elixir
def list_breadcrumbs do
  breadcrumbs_initial_query =
    Group
    |> where([g], g.id == parent_as(:group).id)

  breadcrumbs_recursion_query =
    Group
    |> join(:inner, [g], b in "breadcrumbs", on: b.supergroup_id == g.id)

  breadcrumbs_cte_query =
    breadcrumbs_initial_query
    |> union_all(^breadcrumbs_recursion_query)

  breadcrumbs_query =
    "breadcrumbs"
    |> recursive_ctes(true)
    |> with_cte("breadcrumbs", as: ^breadcrumbs_cte_query)
    |> select([b], %{names: fragment("array_agg(?)", b.name)})

  Repo.all from g in Group,
    as: :group,
    left_lateral_join: b in subquery(breadcrumbs_query),
    select: %{name: g.name, query_test: b.names}
end
```

But I can't access the `:group` binding:

```
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (Ecto.QueryError) `parent_as(:group)` can only be used in subqueries in query:
    
    from g0 in MyApp.Groups.Group,
      where: g0.id == parent_as(:group).id,
      union_all: (from g0 in MyApp.Groups.Group,
      join: b1 in "breadcrumbs",
      on: b1.supergroup_id == g0.id,
      select: g0),
      select: g0
    

The subquery originated from the following query:

from g0 in MyApp.Groups.Group,
  as: :group,
  left_join_lateral: b1 in subquery(from b0 in "breadcrumbs",
  select: %{names: fragment("array_agg(?)", b0.name)}),
  on: true,
  select: %{name: g0.name, query_test: b1.names}

    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:208: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

 I also tried using `as/1` but I get an error saying that the binding could not be found.

### Expected behavior

I expected the `:group` binding to be available.

**Comment by josevalim** [comment]
At the moment, parent_as only looks at the direct parent. By using subquery and CTE, you have two levels, so this is not currently supported. A PR that addresses this is welcome!

**Comment by joaopaulobdac** [comment]
Thank you, that makes sense.

I also tried using `as/1` but it can't find the named binding. I guess it's because it only looks at the current level?

As a workaround, I'm replacing the subquery with a fragment:

```elixir
Repo.all from g in Group,
  left_lateral_join: b in fragment(
    """
    (SELECT array_agg(b."name") AS "breadcrumbs"
    FROM get_group_breadcrumbs(?) AS b)
    """,
    g.id
  ),
  select: %{name: g.name, breadcrumbs: b.breadcrumbs}
```

**Comment by josevalim** [comment]
Yes, `as` is current level.

**Comment by joaopaulobdac** [comment]
I think a good solution would be the ability to "pass down" a named binding. I don't know if it's already possible.

Maybe something like this, but with a clearer API:

```elixir
query_level_2 =
  from u in User,
    where: u.some_field == parent_as(:posts).some_field,
    select: u.id

query_level_1 =
  from c in Comment,
    where:
      c.post_id == parent_as(:posts).id and
      c.user_id in subquery(query_level_2, bindings: [:posts]) ## pass down :posts to subquery

## level 0
from p in Post,
  as: :posts,
  inner_lateral_join: c in subquery(query_level_1)
```

In my case, I would pass the binding from the CTE's parent down to the CTE's subquery.

What's your opinion on this?

**Comment by josevalim** [comment]
I would perhaps just make sure the parent_as can look all the way up.

**Comment by v0idpwn** [comment]
Would the `parent_as` api stay the same? Looking forward to do an attempt at this issue

**Comment by v0idpwn** [comment]
@joaopaulobdac could you try with master? With this fix you should be able to do it

**Comment by joaopaulobdac** [comment]
Hi @v0idpwn thank you for looking into this. I just tried it but unfortunately it didn't work for my query. I got the "not found" error message this time:

```
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (Ecto.QueryError) could not find named binding `parent_as(:group)` in query:
    
    from g0 in MyApp.Groups.Group,
      where: g0.id == parent_as(:group).id,
      union_all: (from g0 in MyApp.Groups.Group,
      join: b1 in "breadcrumbs",
      on: b1.supergroup_id == g0.id,
      select: g0),
      select: g0
    

The subquery originated from the following query:

from g0 in MyApp.Groups.Group,
  as: :group,
  left_join_lateral: b1 in subquery(from b0 in "breadcrumbs",
  select: %{names: fragment("array_agg(?)", b0.name)}),
  on: true,
  select: %{name: g0.name, query_test: b1.names}

    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:208: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

I suspect it has something to do with the `as` from `with_cte`...

**Comment by joaopaulobdac** [comment]
I'm trying to figure it out... It seems that the reason your PR didn't work for me is because the CTE's parent is not being assigned here:

https://github.com/elixir-ecto/ecto/blob/1f096a030b311990edecbd31194108ccc437057b/lib/ecto/query/planner.ex#L872-L885

After fixing this, I'm no longer getting that error message from my comment above.

```elixir
cte_query
|> Map.put(:aliases, Map.put(cte_query.aliases, @parent_as, query))
|> attach_prefix(query)
|> plan(:all, adapter)
```

So it looks like it is finding the named binding, but now I'm getting a different error:

```
** (ArgumentError) argument error
    :erlang.element(1, nil)
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:1212: Ecto.Adapters.Postgres.Connection.quote_qualified_name/3
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:694: Ecto.Adapters.Postgres.Connection.expr/3
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:573: Ecto.Adapters.Postgres.Connection.paren_expr/3
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:553: Ecto.Adapters.Postgres.Connection.boolean/4
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:115: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:388: Ecto.Adapters.Postgres.Connection.cte_query/3
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:385: Ecto.Adapters.Postgres.Connection.cte_expr/3
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:1258: Ecto.Adapters.Postgres.Connection.intersperse_map/4
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:378: Ecto.Adapters.Postgres.Connection.cte/2
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:111: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:625: Ecto.Adapters.Postgres.Connection.expr/3
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:1208: Ecto.Adapters.Postgres.Connection.get_source/4
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:448: anonymous fn/3 in Ecto.Adapters.Postgres.Connection.join/2
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:1258: Ecto.Adapters.Postgres.Connection.intersperse_map/4
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:442: Ecto.Adapters.Postgres.Connection.join/2
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres/connection.ex:114: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.6.1) lib/ecto/adapters/postgres.ex:102: Ecto.Adapters.Postgres.prepare/2
    (ecto 3.6.1) lib/ecto/query/planner.ex:180: Ecto.Query.Planner.query_without_cache/4
    (ecto 3.6.1) lib/ecto/query/planner.ex:150: Ecto.Query.Planner.query_prepare/6
```

I don't know what is wrong yet, maybe someone can point me in the right direction and I'll try to look further into it tomorrow. This issue should be reopened for the time being. Thanks!

**Comment by v0idpwn** [comment]
Could you provide a standalone example of this? Then I can look further into it today. Seems like it behaves differently for subqueries and ctes.

**Comment by joaopaulobdac** [comment]
I've set it up here https://github.com/joaopaulobdac/parenting

There's a docker-compose file to start the database, then you can just run `mix setup`.

**Comment by joaopaulobdac** [comment]
Hey @josevalim can you reopen this issue?
