### ISSUE TITLE
json_extract_path for non ecto schema joins

### ISSUE THREAD

**Issue by jotaviobiondo** [elixir-ecto/ecto#3643]
### Environment

* Elixir version (elixir -v): **1.11.2**
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): **PostgreSQL 12**
* Ecto version (mix deps): **3.4.6**
* Database adapter and version (mix deps): **0.15.8**
* Operating system: **Ubuntu 20.04 (inside Windows 10 WSL2)**

### Current behavior
When joining with something that is not an Ecto schema, it's throwing the following error:

```
** (ArgumentError) you attempted to apply a function on []. Modules (the first argument of apply) must always be an atom
     stacktrace:
       :erlang.apply([], :__schema__, [:type, :value])
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
```

An example code: 

```elixir
json = [
  %{"id" => 1}
]
    
User
|> join(:inner, [], v in fragment(~s/SELECT unnest(?) "value"/, type(^json, {:array, :map})))
|> select([u, j], {u.id, j.value["id"]})
|> Repo.all()
```

Reading the stacktrace, I guess that Ecto is expecting an Ecto schema when using the `json_extract_path`.

### Expected behavior

Use the `json_extract_path` with any kind of join.

This is possible?

**Comment by jotaviobiondo** [comment]
Duh! I look at issues and changelogs for this but forgot to actually try on newer versions, sorry 😅

And thanks for the help!
