### ISSUE TITLE
build_assoc

### ISSUE THREAD

**Issue by Kapeusz** [elixir-ecto/ecto#3724]
### Environment

* Elixir 1.12.2 (compiled with Erlang/OTP 24)
* postgres (PostgreSQL) 13.3
* ecto 3.6.2 (Hex package) (mix)
* Database adapter and version (mix deps): postgrex 0.15.10 (Hex package) (mix)
* Operating system: macOS Big Sur 11.5.2

### Current behavior

Ecto.build_assoc can't build a relationship between user and given_points when running the phoenix application but in the terminal, it works fine.

My schemas:
```
  schema "users" do
    field :email, :string
    field :full_name, :string
    field :password_digest, :string
    belongs_to :role, EmployeeRewardApp.Role
    has_one :pool, EmployeeRewardApp.Points.Pool, on_delete: :delete_all
    has_many :given_points, EmployeeRewardApp.Points.GivenPoint, foreign_key: :user_id, on_delete: :delete_all
    timestamps()
    # Virtual Fields
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:full_name, :email, :password, :password_confirmation, :role_id])
    |> validate_required([:full_name, :email, :password, :password_confirmation, :role_id])
    |> cast_assoc(:pool)
    |> hash_password
  end 
```
```
  schema "given_points" do
    field :given_points, :integer
    field :given_to_user_id, :integer
    belongs_to :user, EmployeeRewardApp.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(given_point, attrs) do
    given_point
    |> cast(attrs, [:user_id, :given_points, :given_to_user_id])
    |> validate_required([:user_id, :given_points, :given_to_user_id])
  end
```
Controller:
```
  def add(conn, %{"given_points" => points_params}) do
    roles = Repo.all(Role)
    current_user = get_session(conn, :current_user)
    point = Ecto.build_assoc(current_user, :given_points)
    case Points.insert_points(point, points_params) do
      {:ok, _points} ->
        conn
        |> put_flash(:info, "Points added successfully.")
        |> redirect(to: Routes.page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "index.html", changeset: changeset, roles: roles)
    end
  end
```
Full error trace:
```
[info] Sent 500 in 52ms
[error] #PID<0.733.0> running EmployeeRewardAppWeb.Endpoint (connection #PID<0.732.0>, stream id 1) terminated
Server: localhost:4000 (http)

Request: POST /points
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Ecto.build_assoc/3
        (ecto 3.6.2) lib/ecto.ex:466: Ecto.build_assoc(%{email: "admin@admin.com", id: 4, role_id: 2}, :given_points, %{"given_points" => "1", "given_to_user_id" => "4"})
        (employee_reward_app 0.1.0) lib/employee_reward_app_web/controllers/points_controller.ex:11: EmployeeRewardAppWeb.PointsController.add/2
        (employee_reward_app 0.1.0) lib/employee_reward_app_web/controllers/points_controller.ex:1: EmployeeRewardAppWeb.PointsController.action/2
        (employee_reward_app 0.1.0) lib/employee_reward_app_web/controllers/points_controller.ex:1: EmployeeRewardAppWeb.PointsController.phoenix_controller_pipeline/2
        (phoenix 1.5.10) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (employee_reward_app 0.1.0) lib/employee_reward_app_web/endpoint.ex:1: EmployeeRewardAppWeb.Endpoint.plug_builder_call/2
        (employee_reward_app 0.1.0) lib/plug/debugger.ex:136: EmployeeRewardAppWeb.Endpoint."call (overridable 3)"/2
        (employee_reward_app 0.1.0) lib/employee_reward_app_web/endpoint.ex:1: EmployeeRewardAppWeb.Endpoint.call/2
        (phoenix 1.5.10) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /Users/kacpermuryn/Desktop/employee_reward_app.nosync/employee_reward_app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/kacpermuryn/Desktop/employee_reward_app.nosync/employee_reward_app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/kacpermuryn/Desktop/employee_reward_app.nosync/employee_reward_app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Line 11 in the points controller is: 
`point = Ecto.build_assoc(current_user, :given_points)`
### Expected behavior
Expected behavior like here, tested in the terminal.
```
iex(4)> u = Accounts.get_user!(4)       
[debug] QUERY OK source="users" db=7.7ms queue=0.5ms idle=1886.5ms
SELECT u0."id", u0."email", u0."full_name", u0."password_digest", u0."role_id", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = $1) [4]
[debug] QUERY OK source="pools" db=1.4ms queue=0.4ms idle=1918.0ms
SELECT p0."id", p0."starting_points", p0."used_points", p0."user_id", p0."inserted_at", p0."updated_at", p0."user_id" FROM "pools" AS p0 WHERE (p0."user_id" = $1) [4]
%EmployeeRewardApp.Accounts.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  email: "admin@admin.com",
  full_name: "Admin",
  given_points: #Ecto.Association.NotLoaded<association :given_points is not loaded>,
  id: 4,
  inserted_at: ~N[2021-08-10 17:53:51],
  password: nil,
  password_confirmation: nil,
  password_digest: "$2b$12$/w4dboQ1h8tFGnb8V4NBZu74QKCMeO3a0gIJjELqFW9YHD9nDGqd6",
  pool: %EmployeeRewardApp.Points.Pool{
    __meta__: #Ecto.Schema.Metadata<:loaded, "pools">,
    id: 1,
    inserted_at: ~N[2021-08-11 14:29:52],
    starting_points: 50,
    updated_at: ~N[2021-08-11 14:29:52],
    used_points: 0,
    user: #Ecto.Association.NotLoaded<association :user is not loaded>,
    user_id: 4
  },
  role: #Ecto.Association.NotLoaded<association :role is not loaded>,
  role_id: 2,
  updated_at: ~N[2021-08-10 17:53:51]
}
iex(5)> Ecto.build_assoc u, :given_points
%EmployeeRewardApp.Points.GivenPoint{
  __meta__: #Ecto.Schema.Metadata<:built, "given_points">,
  given_points: nil,
  given_to_user_id: nil,
  id: nil,
  inserted_at: nil,
  updated_at: nil,
  user: #Ecto.Association.NotLoaded<association :user is not loaded>,
  user_id: 4
}
```
I asked for help on the elixirforum and compared it with almost exactly the same code in the topic where I asked for help. Right now, I'm not sure if it's something with the code or Ecto, that's why I'm asking here. If it's not an appropriate place, please close the issue.

**Comment by josevalim** [comment]
The first argument has to be a struct. You can see in the stacktrace that the first argument is just a list of parameters and not the user struct:

     Ecto.build_assoc(%{email: "admin@admin.com", id: 4, role_id: 2}, :given_points, %{"given_points" => "1", "given_to_user_id" => "4"})
