### ISSUE TITLE
Changeset.cast/3 raises for a list of atom keys from module attribute

### ISSUE THREAD

**Issue by Nickforall** [elixir-ecto/ecto#3772]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.12.1 (compiled with Erlang/OTP 22)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8.0
* Ecto version (mix deps): `ecto 3.7.1 (Hex package) (mix) locked at 3.7.1 (ecto) d36e5b39`
* Database adapter and version (mix deps): `myxql 0.5.1 (Hex package) (mix) locked at 0.5.1 (myxql) 73c6b684`
* Operating system: MacOS 11.6

### Current behavior

The code sample below raises when casting a changeset:

<details>
<summary>Code Sample</summary>

```elixir
defmodule Quest.Table do
  use Ecto.Schema
  import Ecto.Changeset

  alias Quest.{
    Media,
    Episode,
    User
  }

  schema "table" do
    field :path, :string
    field :title, :string
    field :description, :string

    has_many :episodes, Episode

    belongs_to :media, Media
    belongs_to :user, User

    timestamps(inserted_at: :created_at, updated_at: :updated_at)
  end

  @changeset_fields [:path, :title, :description]

  def changeset(struct, attrs) do
    struct
    |> cast(attrs, @changeset_fields)
    |> validate_required(@changeset_fields)
    |> unique_constraint([:path])
  end
end
```

</details>

Calling `changeset/2` raises the error below. 

```
[error] #PID<0.1019.0> running QuestWeb.Endpoint (connection #PID<0.1018.0>, stream id 1) terminated
Server: localhost:8080 (http)
Request: POST /graphiql
** (exit) an exception was raised:
    ** (ArgumentError) cast/3 expects a list of atom keys, got: `[:path, :title, :description]`
        (ecto 3.7.1) lib/ecto/changeset.ex:568: Ecto.Changeset.cast_key/1
        (ecto 3.7.1) lib/ecto/changeset.ex:526: Ecto.Changeset.process_param/7
        (elixir 1.12.1) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto 3.7.1) lib/ecto/changeset.ex:513: Ecto.Changeset.cast/6
        (quest 0.1.0) lib/quest/table.ex:36: Quest.Table.changeset/2
        (quest 0.1.0) lib/quest/table/table.ex:78: Quest.Table.update/2
        (absinthe 1.6.6) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
        (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe 1.6.6) lib/absinthe/pipeline.ex:370: Absinthe.Pipeline.run_phase/3
        (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
        (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
        (quest 0.1.0) lib/quest_graphql/graphql_plug.ex:16: Quest.Graphql.GraphiqlPlug.plug_builder_call/2
        (phoenix 1.6.2) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.6.2) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (quest 0.1.0) lib/quest_web/endpoint.ex:1: QuestWeb.Endpoint.plug_builder_call/2
```

### Expected behavior

I'd expect getting this list from the module attribute to work. Maybe I'm overseeing something, but replacing `@changeset_fields` with `[:path, :title, :description]` fixes this error.

**Comment by josevalim** [comment]
The @changeset_fields is used internally by Ecto, which causes conflicts with your own attribute. We will rename our fields to avoid conflicts, but meanwhile I recommend you rewriting your module attribute to something else. Thanks!

**Comment by josevalim** [comment]
PS: Just don't rewrite it to `@struct_fields` :P
