### ISSUE TITLE
Ecto coalesce DateTime type casting enhancement?

### ISSUE THREAD

**Issue by wilkinson4** [elixir-ecto/ecto#3774]
### Environment

Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.12.3 (compiled with Erlang/OTP 24)

postgres (PostgreSQL) 13.4
Ecto version: 3.6.1
postgrex 0.15.9 (Hex package) (mix)
MacOS Monterey 12.0.1 2020 MacBook Pro M1

### Current behavior
I am running into issues with Ecto when trying to use a `DateTime` struct in a coalesce statement for a field that is defined as a `:utc_datetime`. I have the following fields defined in my Ecto Schemas
`Authorizations`
```elixir
    field(:expiration_date, :date)
```
`Appointments`
```elixir
    field(:start_at, :utc_datetime)
```
Here is a snippet from a query I'm working on:
```elixir
from(appt in Appointment, as: :appt,
      join: auth in Authorization, as: :auth,
      on:
        appt.authorization_id == auth.id and appt.start_at >= auth.effective_date and
          appt.start_at <= coalesce(auth.expiration_date, ^Timex.to_datetime({{2099, 12, 31}, {0, 0, 0}})) and
```
This fails with the following error:
```elixir
** (DBConnection.EncodeError) Postgrex expected %Date{}, got ~U[2099-12-31 00:00:00Z]. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (care_bridge 0.1.0) /Users/williamwilkinson/workspace/cb-payer-api/deps/postgrex/lib/postgrex/type_module.ex:897: CB.PostgresTypes.encode_params/3
    (postgrex 0.15.9) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.4.0) lib/db_connection.ex:1205: DBConnection.encode/5
    (db_connection 2.4.0) lib/db_connection.ex:1305: DBConnection.run_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:1409: DBConnection.run/6
    (db_connection 2.4.0) lib/db_connection.ex:574: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:566: DBConnection.prepare_execute/4
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:690: Ecto.Adapters.SQL.execute!/4
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute/5
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
iex(23)> [debug] QUERY ERROR source="appointments" db=3.7ms queue=1.9ms idle=1833.2ms
SELECT a0."start_at", p6."external_code", count(DISTINCT a0."appointment_guid"), count(DISTINCT a0."appointment_guid") FILTER (WHERE NOT (a2."id" IS NULL)), count(DISTINCT a0."appointment_guid") FILTER (WHERE a2."id" IS NULL), count(DISTINCT a0."appointment_guid") FILTER (WHERE NOT (a5."id" IS NULL)), count(DISTINCT a0."appointment_guid") FILTER (WHERE a5."
alert_status" != 'dismissed'), count(DISTINCT a0."appointment_guid") FILTER (WHERE a5."alert_status" = 'dismissed'), sum(coalesce(c3."total_charges", 0) + coalesce(c4."total_charges", 0)) FROM "appointments" AS a0 INNER JOIN "authorizations" AS a1 ON ((((a0."authorization_id" = a1."id") AND (a0."start_at" >= a1."effective_date")) AND (a0."start_at" <= coale
sce(a1."expiration_date", $1))) AND NOT (coalesce(a0."evv_checkin_at", a0."manual_checkin_at") IS NULL)) AND NOT (coalesce(a0."evv_checkin_at", a0."manual_checkout_at") IS NULL) LEFT OUTER JOIN "appointment_claim_requests" AS a2 ON a2."id" = a0."current_appointment_claim_request_id" LEFT OUTER JOIN "claims" AS c3 ON (a2."claim1_id" = c3."id") AND NOT (c3."s
tatus" IN ('deleted','prebilling_rejection')) LEFT OUTER JOIN "claims" AS c4 ON (a2."claim1_id" = c4."id") AND NOT (c4."status" IN ('deleted','prebilling_rejection')) LEFT OUTER JOIN "alerts" AS a5 ON (a5."entity_id" = a0."id") AND (a5."entity_type" = 'appointment') LEFT OUTER JOIN "payers" AS p6 ON p6."id" = a1."payer_id" WHERE (a0."status" LIKE 'complete'
) AND (p6."external_code" != 'CB_TP') AND (p6."payer_key" != 'test_payer') AND (a0."start_at" >= $2) AND (a0."start_at" <= $3) GROUP BY a0."start_at", p6."external_code" [~U[2099-12-31 00:00:00Z], ~U[2021-05-01 00:00:00Z], ~U[2021-10-31 00:00:00Z]]
```
So I tried giving it a date via `Timex.to_date` and I got this error:
```elixir
** (Ecto.Query.CastError) apps/care_bridge/lib/care_bridge/appointments/appointments.ex:334: value `~D[2099-12-31]` in `join` cannot be cast to type :utc_datetime in query:

from a0 in CB.Appointments.Appointment,
  as: :appt,
  join: a1 in CB.Authorizations.Authorization,
  as: :auth,
  on: a0.authorization_id == a1.id and a0.start_at >= a1.effective_date and a0.start_at <= coalesce(a1.expiration_date, ^~D[2099-12-31]) and not(is_nil(coalesce(a0.evv_checkin_at, a0.manual_checkin_at))) and not(is_nil(coalesce(a0.evv_checkin_at, a0.manual_checkout_at))),
  left_join: a2 in CB.Appointments.AppointmentClaimRequest,
  on: a2.id == a0.current_appointment_claim_request_id,
  left_join: c3 in CB.Claims.Claim,
  as: :clm1,
  on: a2.claim1_id == c3.id and c3.status not in ["deleted", "prebilling_rejection"],
  left_join: c4 in CB.Claims.Claim,
  as: :clm2,
  on: a2.claim1_id == c4.id and c4.status not in ["deleted", "prebilling_rejection"],
  left_join: a5 in CB.Validation.Alert,
  as: :alert,
  on: a5.entity_id == a0.id and a5.entity_type == "appointment",
  left_join: p6 in CB.Payers.Payer,
  on: p6.id == a1.payer_id,
  where: like(a0.status, "complete"),
  where: p6.external_code != "CB_TP",
  where: p6.payer_key != "test_payer",
  where: a0.start_at >= ^~N[2021-05-01 00:00:00.000000],
  where: a0.start_at <= ^~N[2021-10-31 00:00:00.000000],
  group_by: [a0.start_at, p6.external_code],
  select: %{month: a0.start_at, external_code: p6.external_code, visits: count(a0.appointment_guid, :distinct), visits_w_claim_req: filter(count(a0.appointment_guid, :distinct), not(is_nil(a2.id))), visits_wo_claim_req: filter(count(a0.appointment_guid, :distinct), is_nil(a2.id)), prebill_edit: filter(count(a0.appointment_guid, :distinct), not(is_nil(a5.id)
)), open_prebill: filter(count(a0.appointment_guid, :distinct), a5.alert_status != "dismissed"), resolved_prebill: filter(count(a0.appointment_guid, :distinct), a5.alert_status == "dismissed"), total_charges_claimed: sum(fragment("coalesce(?, 0) + coalesce(?, 0)", c3.total_charges, c4.total_charges))}

    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.12.3) lib/enum.ex:1704: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:208: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (stdlib 3.16.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (iex 1.12.3) lib/iex/evaluator.ex:298: IEx.Evaluator.handle_eval/3
    (iex 1.12.3) lib/iex/evaluator.ex:274: IEx.Evaluator.do_eval/3
```

However, using a fragment like so works `fragment("2031-12-32")`. Also, explicitly casting it via the `type` macro works to like so:
```elixir
type(^Timex.to_datetime({{2099, 12, 31}, {0, 0, 0}}), :utc_datetime)
```

### Expected behavior
Should Ecto handle this casting under the hood if I pass in the right type?

**Comment by josevalim** [comment]
We don’t do casts at the database level by design. For example, ignoring the time from DateTime could be the source of bugs in other occasions. So you either need to pass a date or explicitly cast. :)

**Comment by josevalim** [comment]
To be clear what I mean, the entity that is expecting a Date is PostgreSQL. It is likely assuming it due to the coalesce, and we never override or cast based on what PostgreSQL assigns.
