### ISSUE TITLE
Possible bug in combination of lateral joins, fragments and select_merge

### ISSUE THREAD

**Issue by olivermt** [elixir-ecto/ecto#3775]
### Environment

* Elixir version (elixir -v): 1.12.3 on OTP24
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql 14
* Ecto version (mix deps):
```
{:ecto, "~> 3.6"},
{:ecto_psql_extras, "~> 0.4"},
{:ecto_sql, "~> 3.6"},
```
* Database adapter and version (mix deps): from lock: "postgrex": {:hex, :postgrex, "0.15.12", "9
* Operating system: macos

### Current behavior

```
def batch_public_from_order_item(ctx, order_item_uids) do
    from(p in Product, as: :product)
    |> join(:inner, [product: p], o_i in OrderItem, on: o_i.product_id == p.id, as: :order_item)
    |> join(:inner, [product: p], s in Seller,
      on: s.uid == p.seller_uid and s.deleted_at == fragment("'epoch'"),
      as: :seller
    )
    |> join_lateral_product_count()
    |> where(
      [order_item: o_i],
      o_i.deleted_at == fragment("'epoch'") and
        o_i.uid in type(^order_item_uids, {:array, :binary_id})
    )
    |> select([order_item: o_i], %{order_item_uid: o_i.uid})
    |> public_product_select(ctx)
    |> Repo.all()
    |> Enum.reduce(%{}, fn %{order_item_uid: id, product: p}, acc ->
      Map.put(acc, id, p)
    end)
  end
```
```
defp join_lateral_product_count(query) do
    join(
      query,
      :left_lateral,
      [product: p],
      p_i in fragment(
        """
        (
          SELECT count(p_i_c.id) > 0 as visible
          FROM product_item p_i_c
          WHERE
            p_i_c.product_uid = ?
            AND
            p_i_c.deleted_at = 'epoch'
            and
            p_i_c.visible = true
        )
        """,
        p.uid
      ),
      as: :product_item_count
    )
  end
```

```
 defp public_product_select(ctx, query) do
    select_merge(query, [product: p, seller: s, product_item_count: p_i_c], %{
      product: %{
        id: p.id,
        uid: p.uid,
        slug: p.slug,
        url_id: p.url_id,
        info_sections: p.info_sections,
        description:
          fragment(
            "coalesce((? ->> ? ::text), ? ->> 'en')",
            p.description,
            ^ctx.locale,
            p.description
          ),
        images: p.images,
        assets: p.assets,
        name:
          fragment(
            "coalesce((? ->> ? ::text), ? ->> 'en')",
            p.name,
            ^ctx.locale,
            p.name
          ),
        visible:
          fragment(
            """
            CASE
            WHEN (? AND ? AND ?) THEN true
            ELSE false
            END
            """,
            p.visible,
            s.visible,
            p_i_c.visible
          ),
        seller: %{
          uid: s.uid,
          name: s.name,
          images: s.images,
          assets: s.assets,
          url_id: s.url_id,
          slug: s.slug,
          region_uid: s.region_uid,
          description: s.description,
          email: s.email
        }
      }
    })
  end
```
Console error:
```
dev_server@luftbolle 3614baca1 2021-11-14 9:29:18.460 [error]   #PID<0.18997.0> running CoruscantWeb.Endpoint (connection #PID<0.18996.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /endpoints/ecommerce/v1/graphiql
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Ecto.Queryable not implemented for %Coruscant.Ctx{command_name: nil, command_uid: nil, domain_data: %DomainData[SUMMARY]{%{}}, gql_schema: "ecommerce", impersonator: nil, initiator: "NzM0Njk3OWItZWYxOC00ZGI2LThkNDEtOGZkZDVmZTBkNDBh", locale: "nb", meta: %{}, repo: nil, session_id: "NzM0Njk3OWItZWYxOC00ZGI2LThkNDEtOGZkZDVmZTBkNDBh", user: nil} of type Coruscant.Ctx (a struct)
        (ecto 3.7.1) lib/ecto/queryable.ex:1: Ecto.Queryable.impl_for!/1
        (ecto 3.7.1) lib/ecto/queryable.ex:9: Ecto.Queryable.to_query/1
        (coruscant 0.1.0) lib/coruscant_api/products/product_service.ex:111: Coruscant.Products.ProductService.public_product_select/2
        (coruscant 0.1.0) lib/coruscant_api/products/product_service.ex:79: Coruscant.Products.ProductService.batch_public_from_order_item/2
        (coruscant 0.1.0) lib/coruscant_api/orders/order_item_service.ex:46: Coruscant.Orders.OrderItemService.load_cart_items/2
        (coruscant_web 0.1.0) lib/coruscant_web/graphql/resolvers/cart_resolver.ex:40: CoruscantWeb.GraphQL.Resolvers.CartResolver.cart_items/3
        (absinthe 1.6.5) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:280: Absinthe.Phase.Document.Execution.Resolution.build_result/3
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe 1.6.5) lib/absinthe/pipeline.ex:370: Absinthe.Pipeline.run_phase/3
        (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
        (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
        (phoenix 1.5.12) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
 
```

### Expected behavior

That the query should just work.
If I move everything into a big select (repeated across the four functions that need to load the product public data, so not very DRY) it works.

The error seems to vary a bit, but it always happens if I have all three of lateral, fragments and a select merge. Remove one of the three and it works again. 

This error is on the ^ctx.locale thing, and will just change to saying something like `cant use :locale` if I pull ctx.locale into a locale binding "locale". So it's not related to the Ctx struct in itself

**Comment by josevalim** [comment]
Looking at the code, I don't see how it can work, you do:

```elixir
    |> select([order_item: o_i], %{order_item_uid: o_i.uid})
    |> public_product_select(ctx)
```

where the query is given as first argument, and then:

```elixir
defp public_product_select(ctx, query) do
```

The query is the second argument, which means the error is correct in saying `ctx` is not a query. So if this is indeed an issue, could you please provide a minimal set of schemas and queries that reproduce it in isolation? It doesn't look like I am getting enough context to investigate it. :) Thanks.

**Comment by olivermt** [comment]
You have got to be kidding me, I have been staring at this for an added sum of four hours.
Can we delete this issue instead of closing it and both pretend it never happened? 

This is probably the biggest code brainfart I have had in years, I spent SO much time trying all permutations before I gave up and made this issue :(
