### ISSUE TITLE
Many_to_many association put_assoc fails with `no function clause` error.

### ISSUE THREAD

**Issue by wking-io** [elixir-ecto/ecto#3780]
### Environment

* Elixir version (elixir -v): 1.12
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgresSQL 13.2
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps): ecto-sql 3.7.0
* Operating system: MacOS

### Current behavior

I have the following associations and put_assoc call based off of the docs in put_assoc.

```
  schema "members" do
    field :email, :string
    field :password, :string, virtual: true, redact: true
    field :hashed_password, :string, redact: true
    field :confirmed_at, :naive_datetime
    field :first_name, :string
    field :last_name, :string
    field :accepted_terms_at, :naive_datetime
    field :accepted_privacy_at, :naive_datetime

    has_many :account_members, WithoutCeasing.Identity.AccountMember, on_delete: :delete_all
    has_many :accounts, through: [:account_members, :accounts]
    has_many :resources, WithoutCeasing.Content.Resource
    has_many :notes, WithoutCeasing.Content.Note

    many_to_many :highlights, WithoutCeasing.Bible.Verse,
      join_through: "highlights",
      on_replace: :delete

    timestamps()
  end
```

```
  schema "verses" do
    field :book, :string
    field :chapter, :integer
    field :verse, :integer

    has_many :verse_revisions, WithoutCeasing.Bible.VerseRevision

    many_to_many :members, WithoutCeasing.Identity.Member,
      join_through: "highlights",
      on_replace: :delete
  end
```

Note here that verses are the same struct as highlights as seen in the Verse schema above.
```
  def highlight_verses(verse_ids, member) do
    verses = get_verses(verse_ids)

    loaded =
      member
      |> Repo.preload(:highlights)

    loaded
    |> Changeset.change()
    |> Changeset.put_assoc(:highlights, [verses | loaded.highlights])
    |> Repo.update()
  end
```

I get this error:

```
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Ecto.Changeset.get_changed/6
    (ecto 3.7.1) lib/ecto/changeset.ex:406: anonymous fn(%WithoutCeasing.Bible.Verse{__meta__: #Ecto.Schema.Metadata<:loaded, "verses">, book: "john", chapter: 12, id: 43012001, members: #Ecto.Association.NotLoaded<association :members is not loaded>, notes: #Ecto.Association.NotLoaded<association :notes is not loaded>, resources: #Ecto.Association.NotLoaded<association :resources is not loaded>, verse: 1, verse_revisions: #Ecto.Association.NotLoaded<association :verse_revisions is not loaded>}, {%{}, [], true}) in Ecto.Changeset.get_changed/6
    (elixir 1.12.0) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.1) lib/ecto/changeset.ex:400: Ecto.Changeset.change/2
    (ecto 3.7.1) lib/ecto/changeset/relation.ex:202: Ecto.Changeset.Relation.do_change/4
    (ecto 3.7.1) lib/ecto/changeset/relation.ex:351: Ecto.Changeset.Relation.map_changes/9
    (ecto 3.7.1) lib/ecto/changeset/relation.ex:165: Ecto.Changeset.Relation.change/3
    (ecto 3.7.1) lib/ecto/changeset.ex:1222: Ecto.Changeset.put_change/7
    (ecto 3.7.1) lib/ecto/changeset.ex:1432: Ecto.Changeset.put_relation/5
    (without_ceasing 0.1.0) lib/without_ceasing/bible.ex:51: WithoutCeasing.Bible.highlight_verses/2
```

I have done some digging and the anonymous function is expecting a value that matches the shape `{key, value}` and what is being sent in is just `value` and blowing up. I assumed the array of verses being saved as the association would be transformed to be given a tuple shape as expected, but I couldn't find any code that was doing that.

### Expected behavior

It should update the Member with the array of verses as the new highlights association.

**Comment by josevalim** [comment]
If `get_verses` returns a list, then you should do:

```elixir
|> Changeset.put_assoc(:highlights, verses ++ loaded.highlights)
```

Otherwise you are passing a list of lists of verses, which is not what you want.

**Comment by wking-io** [comment]
🤦‍♂️ Thank you José sorry for missing that.
