### ISSUE TITLE
Atom to string conversion fails in `3.8`

### ISSUE THREAD

**Issue by pierot** [elixir-ecto/ecto#3888]
### Environment

    Elixir version (elixir -v): 1.13.3
    Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8.0.23
    Ecto version (mix deps): 3.8.1
    Database adapter and version (mix deps): myxql 0.6.2
    Operating system: Mac OS 12.3

### Current behavior

Steps schema:

```elixir
schema "steps" do
  ...
  field(:remark_type, :string, virtual: true)
  ...
end
```

Query build up:

```elixir
a_query =
  from(step in Step,
    inner_join: case in assoc(step, :case),
    as: :case,
    inner_join: remarks in assoc(step, :remarks),
    as: :remarks,
    select_merge: %{ remark_type: remarks.type },
    distinct: true
  )

b_query =
  from(step in Step,
    inner_join: case in assoc(step, :case),
    as: :case,
    inner_join: remarks in assoc(step, :remarks),
    as: :remarks,
    select_merge: %{ remark_type: remarks.type },
    distinct: true
  )

query = a_query |> union_all(^b_query)

from(u in subquery(query),
  join: kase in assoc(u, :case),
  as: :case,
  preload: [:remarks]
)
|> build_inbox_filters([:notification])
|> Repo.all()

defp build_inbox_filters(query, types), do: where(query, [s], s.remark_type in ^types)
```

Calling this in `3.8.1` results in:

```elixir
query has invalid parameter :notification
```

### Expected behavior

In pre `3.8` the query succeeded.

We can fix this by converting the atoms in `build_inbox_filters` to strings:

```elixir
...
where(query, [s], s.remark_type in ^Enum.map(remark_types, &Atom.to_string/1))
...
```

**Comment by josevalim** [comment]
> Calling this in 3.8.1 results in:

Can you provide the full error message and stacktrace?

**Comment by pierot** [comment]
```elixir
** (exit) an exception was raised:
    ** (ArgumentError) query has invalid parameter :notification
        (myxql 0.6.2) lib/myxql/protocol/values.ex:265: MyXQL.Protocol.Values.encode_binary_value/1
        (myxql 0.6.2) lib/myxql/protocol.ex:415: anonymous fn/2 in MyXQL.Protocol.encode_params/1
        (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (myxql 0.6.2) lib/myxql/protocol.ex:407: MyXQL.Protocol.encode_params/1
        (db_connection 2.4.2) lib/db_connection.ex:1255: DBConnection.encode/5
        (db_connection 2.4.2) lib/db_connection.ex:1355: DBConnection.run_prepare_execute/5
        (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6
        (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
        (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
        (myxql 0.6.2) lib/myxql.ex:346: MyXQL.do_query/4
        (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:892: Ecto.Adapters.SQL.execute!/5
        (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
        (ecto 3.8.1) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
        (ecto 3.8.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

**Comment by josevalim** [comment]
Oh, this is expected. I am surprised it worked before. An atom is not a valid parameter to send down to the database. Casting to strings is correct. :)
