### ISSUE TITLE
ecto unique constraint not being handled by ecto in some cases

### ISSUE THREAD

**Issue by sescobb27** [elixir-ecto/ecto#3923]
### Elixir version

1.13.3

### Database and Version

PostgreSQL 11

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16

### Current behavior

this is the code to reproduce the behavior, i think its a bug because i'm explicitly handling the unique_constraint exception but it is still raising it
https://github.com/sescobb27/ecto_repro_bug

context: Disallow modifying unique index attributes in an upsert operation

steps:

```elixir
id = Ecto.UUID.generate()

# insert
ReproEctoBug.EventLabels.upsert("12345", %{"name" => "event1", "id" => id})

{:ok,
 %ReproEctoBug.EventLabel{
   __meta__: #Ecto.Schema.Metadata<:loaded, "event_labels">,
   account_id: "12345",
   id: "c6e20968-41c6-4ef7-b6d3-7e9b83aa63c1",
   inserted_at: ~U[2022-06-06 19:23:33.345351Z],
   name: "event1",
   updated_at: ~U[2022-06-06 19:23:33.345351Z]
 }}

# upsert changing the name which is not supported and should return ecto changeset error not unique instead of raising
ReproEctoBug.EventLabels.upsert("12345", %{"name" => "event2", "id" => id})

14:23:47.820 [debug] QUERY ERROR db=9.9ms queue=6.0ms idle=1600.8ms
INSERT INTO "event_labels" ("account_id","id","name","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("account_id","name") DO UPDATE SET "inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "updated_at","inserted_at","name","account_id","id" ["12345", "c6e20968-41c6-4ef7-b6d3-7e9b83aa63c1", "event2", ~U[2022-06-06 19:23:47.803951Z], ~U[2022-06-06 19:23:47.803951Z]]
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * event_labels_pkey (unique_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset defined the following constraints:

    * event_labels_account_id_name_index (unique_constraint)

    (ecto 3.8.4) lib/ecto/repo/schema.ex:783: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.13.3) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.8.4) lib/ecto/repo/schema.ex:768: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.8.4) lib/ecto/repo/schema.ex:749: Ecto.Repo.Schema.apply/4
    (ecto 3.8.4) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
```

### Expected behavior

it should not raise, but instead return an ecto changeset with errors

**Comment by josevalim** [comment]
Hi @sescobb27! 👋 

You are handling the `:event_labels_account_id_name_index` unique constraint, but the database is raising an error on this constraint: `:event_labels_pkey`. So the behaviour looks correct to me. What am I missing?

**Comment by sescobb27** [comment]
upppsssss 🤦 my bad!!!!!!! i was only focusing on the `event_labels_account_id_name_index (unique_constraint)` on though the error was it, sorry for the confusion.

```
The changeset defined the following constraints:
    * event_labels_account_id_name_index (unique_constraint)
```

**Comment by wojtekmach** [comment]
I tried running the code that you mentioned and it worked, no error, but I ended up with two records:

```elixir
    IO.inspect(ReproEctoBug.EventLabels.upsert("12345", %{"name" => "event1", "id" => id}))
    IO.inspect(ReproEctoBug.EventLabels.upsert("12345", %{"name" => "event2", "id" => id}))
    IO.inspect(ReproEctoBug.Repo.all(ReproEctoBug.EventLabel))
```

```elixir
[
  %ReproEctoBug.EventLabel{
    __meta__: #Ecto.Schema.Metadata<:loaded, "event_labels">,
    account_id: "12345",
    id: "8260ff5f-f83d-4a92-b449-49be6c4df740",
    inserted_at: ~U[2022-06-06 19:45:52.647664Z],
    name: "event1",
    updated_at: ~U[2022-06-06 19:45:52.647664Z]
  },
  %ReproEctoBug.EventLabel{
    __meta__: #Ecto.Schema.Metadata<:loaded, "event_labels">,
    account_id: "12345",
    id: "0cebcefe-c2fd-4573-938d-391acc153a60",
    inserted_at: ~U[2022-06-06 19:45:52.655504Z],
    name: "event2",
    updated_at: ~U[2022-06-06 19:45:52.655504Z]
  }
]
```

Btw, in the future consider giving us a "Mix install script" like this one: https://github.com/wojtekmach/mix_install_examples/blob/main/ecto_sql.exs. Everything is in one file so super easy to inspect and reproduce. Thanks for putting work into sample app though, very appreciated.

**Comment by sescobb27** [comment]
@wojtekmach hmmm but you should not get 2 records, as i'm using `{:replace_all_except, [:id, :name, :account_id, :created_by]}` and i'm passing the same `id` to update the record instead of adding another one 🤔

**Comment by sescobb27** [comment]
even adding a unique constraint on PKEY is still raising 🤔 

```elixir
  def changeset(event_label \\ %__MODULE__{}, attrs) do
    event_label
    |> cast(attrs, @fields)
    |> validate_required(@required_fields)
    |> unique_constraint([:account_id, :name])
    |> unique_constraint([:id])
  end
```

```elixir
id = Ecto.UUID.generate()
"048583d6-ceb7-46d2-b8c4-489cb0a46e86"
iex(4)> ReproEctoBug.EventLabels.upsert("54321", %{"name" => "event1", "id" => id})

14:55:41.425 [debug] QUERY OK db=5.5ms queue=3.2ms idle=998.0ms
INSERT INTO "event_labels" ("account_id","id","name","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("account_id","name") DO UPDATE SET "inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "updated_at","inserted_at","name","account_id","id" ["54321", "048583d6-ceb7-46d2-b8c4-489cb0a46e86", "event1", ~U[2022-06-06 19:55:41.416547Z], ~U[2022-06-06 19:55:41.416547Z]]
{:ok,
 %ReproEctoBug.EventLabel{
   __meta__: #Ecto.Schema.Metadata<:loaded, "event_labels">,
   account_id: "54321",
   id: "048583d6-ceb7-46d2-b8c4-489cb0a46e86",
   inserted_at: ~U[2022-06-06 19:55:41.416547Z],
   name: "event1",
   updated_at: ~U[2022-06-06 19:55:41.416547Z]
 }}
iex(5)> ReproEctoBug.EventLabels.upsert("54321", %{"name" => "event2", "id" => id})

14:55:46.805 [debug] QUERY ERROR db=13.0ms queue=0.1ms idle=1375.7ms
INSERT INTO "event_labels" ("account_id","id","name","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("account_id","name") DO UPDATE SET "inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "updated_at","inserted_at","name","account_id","id" ["54321", "048583d6-ceb7-46d2-b8c4-489cb0a46e86", "event2", ~U[2022-06-06 19:55:46.791790Z], ~U[2022-06-06 19:55:46.791790Z]]
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * event_labels_pkey (unique_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset defined the following constraints:

    * event_labels_id_index (unique_constraint)
    * event_labels_account_id_name_index (unique_constraint)

    (ecto 3.8.4) lib/ecto/repo/schema.ex:783: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.13.3) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.8.4) lib/ecto/repo/schema.ex:768: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.8.4) lib/ecto/repo/schema.ex:749: Ecto.Repo.Schema.apply/4
    (ecto 3.8.4) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
```
