### ISSUE TITLE
selected_as suppoert within select_merge

### ISSUE THREAD

**Issue by revati** [elixir-ecto/ecto#4011]
### Elixir version

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]  Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Database and Version

N/A

### Ecto Versions

3.9.0

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

```elixir
query
|> select_merge([txn: t], %{
  time:
    selected_as(fragment(
      "DATE_TRUNC('day', ? AT TIME ZONE 'utc' AT TIME ZONE 'Europe/Riga')::date",
      t.inserted_at
    ), :time)
})
|> group_by(selected_as(:time))
```
throws error: `invalid alias: ":time". Use "selected_as/2" to define aliases in the outer most "select" expression.`

### Expected behavior

Allow to use `selected_as/2` within `select_merge/2`

**Comment by revati** [comment]
It's probably improvement or something like that, not bug per se.

**Comment by greg-rychlewski** [comment]
@revati Thanks for the report. It's a bug :). I see what's wrong and will push a fix soon.

**Comment by greg-rychlewski** [comment]
Fixed in master. Please give it a try when you have time :).

**Comment by revati** [comment]
It works 👍🏼

**Comment by SteffenDE** [comment]
Using Ecto 3.9.1, this does not work for me (just to make sure I used basically the exact same code as above):
```elixir
import Ecto.Query

query = from(s in Schema, as: :txn)

query
|> select_merge([txn: t], %{
  time:
    selected_as(
      fragment(
        "DATE_TRUNC('day', ? AT TIME ZONE 'utc' AT TIME ZONE 'Europe/Riga')::date",
        t.inserted_at
      ),
      :time
    )
})
|> group_by(selected_as(:time))
|> Repo.all(skip_org_id: true)
```

```
** (Ecto.QueryError) unsupported expression: :time in query:

from b0 in Schema,
  as: :txn,
  group_by: [selected_as(:time)],
  select: merge(b0, %{
  time:
    selected_as(
      fragment(
        "DATE_TRUNC('day', ? AT TIME ZONE 'utc' AT TIME ZONE 'Europe/Riga')::date",
        b0.inserted_at
      ),
      :time
    )
})

    (ecto_sql 3.9.0) lib/ecto/adapters/postgres/connection.ex:1405: Ecto.Adapters.Postgres.Connection.error!/2
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres/connection.ex:1339: Ecto.Adapters.Postgres.Connection.intersperse_map/4
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres/connection.ex:745: Ecto.Adapters.Postgres.Connection.expr/3
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres/connection.ex:1339: Ecto.Adapters.Postgres.Connection.intersperse_map/4
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres/connection.ex:360: Ecto.Adapters.Postgres.Connection.select/3
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres/connection.ex:135: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres.ex:127: Ecto.Adapters.Postgres.prepare/2
    (ecto 3.9.1) lib/ecto/query/planner.ex:182: Ecto.Query.Planner.query_without_cache/4
    (ecto 3.9.1) lib/ecto/query/planner.ex:152: Ecto.Query.Planner.query_prepare/6
    (ecto 3.9.1) lib/ecto/query/planner.ex:127: Ecto.Query.Planner.query_with_cache/8
    (ecto 3.9.1) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    #cell:ie4vf2zjaocmhszfr4746ve3e633gsqt:17: (file)
```

Any idea why it fails?

Should not matter as the changelog says it's released in 3.9.1, but I tried to use ecto from master
```
{:ecto, github: "elixir-ecto/ecto", tag: "master", override: true},
```
but that doesn't work because of other reasons:
```
** (Mix) The lock is missing for package ecto. This could be because another package has configured the application name for the dependency incorrectly. Verify with the maintainer of the parent application
```

**Comment by greg-rychlewski** [comment]
Thanks @SteffenDE, I see the problem and will work on a fix

**Comment by greg-rychlewski** [comment]
It's fixed in master now @SteffenDE, but I'm not sure why you were getting that error when trying to that branch. Are you using an umbrella application by any chance?

**Comment by greg-rychlewski** [comment]
Normally I use "branch" instead of "tag" btw. Not sure there is a tag for "master".

**Comment by SteffenDE** [comment]
Thank you for the quick fix! Yes, it's indeed an umbrella. I found out that it works when adding the ecto dependency to the root of the umbrella project.
