### ISSUE TITLE
Many To Many relationship using through produces unexpected join conditions

### ISSUE THREAD

**Issue by Costa-Silva** [elixir-ecto/ecto#4082]
### Elixir version

Elixir 1.14.3 (compiled with Erlang/OTP 25

### Database and Version

PostgreSQL 13.6 on arm-apple-darwin21.3.0, compiled by Apple clang version 13.0.0 (clang-1300.0.29.30), 64-bit

### Ecto Versions

ecto 3.9.4;

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Schemas for context

1.
```elixir
schema "benefit_plans" do
...
  has_many(:benefit_tier_plans, BenefitTierPlan)
  has_many(:benefits, through: [:benefit_tier_plans, :benefits])
...
end
```
2.
```elixir
schema "benefit_tier_plans" do
...
    belongs_to :benefit_plan, BenefitPlan
    has_many :benefits, Benefit
...
end
```
3.

```elixir
schema "benefits" do
...
 belongs_to(:benefit_tier_plan, BenefitTierPlan)
...
end
```

The following query

```elixir
iex>  query = from(benefit_plans in BenefitPlan,  left_join: benefits in assoc(benefit_plans, :benefits))
#Ecto.Query<from b0 in App.Benefits.BenefitPlan,
 left_join: b1 in assoc(b0, :benefits)>

# Calling planner so we can expand the associations

iex> {expanded_query, _meta, _ast} = Ecto.Query.Planner.plan(query, :all, Ecto.Adapters.Postgres)
 #Ecto.Query<from b0 in App.Benefits.BenefitPlan,
  left_join: b2 in App.Benefits.BenefitTierPlan,
  on: b0.id == b2.benefit_plan_id, left_join: b1 in App.Benefits.Benefit,
  on: b2.id == b1.benefit_tier_plan_id>

# Looking at the join conditions everything looks fine until now, let's look into detail on the joins (pasting everything to make sure I give every bit of info but the focus is the `:on` and `ix`

iex> expanded_query.joins
[
  %Ecto.Query.JoinExpr{
    qual: :left,
    source: {"benefit_tier_plans", App.Benefits.BenefitTierPlan},
    on: %Ecto.Query.QueryExpr{
      expr: {:==, [],
       [
         {{:., [], [{:&, [], [0]}, :id]}, [], []},
         {{:., [], [{:&, [], [2]}, :benefit_plan_id]}, [], []}
       ]},
      file: "path/app/deps/ecto/lib/ecto/association.ex",
      line: 239,
      params: []
    },
    file: "path/app/deps/ecto/lib/ecto/association.ex",
    line: 239,
    assoc: nil,
    as: nil,
    ix: 2,
    prefix: nil,
    params: [],
    hints: []
  },
  %Ecto.Query.JoinExpr{
    qual: :left,
    source: {"benefits", App.Benefits.Benefit},
    on: %Ecto.Query.QueryExpr{
      expr: {:==, [],
       [
         {{:., [], [{:&, [], [2]}, :id]}, [], []},
         {{:., [], [{:&, [], [1]}, :benefit_tier_plan_id]}, [], []}
       ]},
      file: "path/app/deps/ecto/lib/ecto/association.ex",
      line: 239,
      params: []
    },
    file: "path/app/deps/ecto/lib/ecto/association.ex",
    line: 239,
    assoc: nil,
    as: nil,
    ix: 1,
    prefix: nil,
    params: [],
    hints: []
  }
]
```

It looks like the join between benefit_plans (from clause) and benefit_tier_plans still appears first in the list of joins but has `ix` set to 2 and then the join with benefits has `ix` set to 1. 

I need to convert both joins to a subquery each I do something similar to:

```elixir
    subquery_source = from(element in App.Benefits.BenefitTierPlan>)
    new_scope = %Ecto.SubQuery{query: subquery_source}
    join = Map.put(join,  :source, new_scope)
    joins = List.replace_at(query.joins, join_index, join)
    Map.put(query, :joins, joins)

# which produces

%Ecto.Query.JoinExpr{
  qual: :left,
  source: %Ecto.SubQuery{
    query: #Ecto.Query<from b0 in App.Benefits.BenefitTierPlan>,
    params: nil,
    select: nil,
    cache: nil
  },
  on: %Ecto.Query.QueryExpr{
    expr: {:==, [],
     [
       {{:., [], [{:&, [], [0]}, :id]}, [], []},
       {{:., [], [{:&, [], [2]}, :benefit_plan_id]}, [], []}
     ]},
    file: "path/app/deps/ecto/lib/ecto/association.ex",
    line: 239,
    params: []
  },
  file: "path/app/deps/ecto/lib/ecto/association.ex",
  line: 239,
  assoc: nil,
  as: nil,
  ix: 2,
  prefix: nil,
  params: [],
  hints: []
}


# New query shows the join conditions are correct since we actually didn't touch on those and neither on `ix`:

#Ecto.Query<from b0 in App.Benefits.BenefitPlan,
 left_join: b2 in subquery(from b0 in App.Benefits.BenefitTierPlan),
  on: b0.id == b2.benefit_plan_id,
 left_join: b1 in subquery(from b0 in App.Benefits.Benefit),
  on: b2.id == b1.benefit_tier_plan_id>


iex> Repo.all(new_query)

** (Postgrex.Error) ERROR 42P01 (undefined_table) missing FROM-clause entry for table "s2"

    query: 
    SELECT ...
    FROM
	"benefit_plans" AS b0
	LEFT OUTER JOIN (
	SELECT
		sb0. "id" AS "id",
		sb0. "benefit_plan_id" AS "benefit_plan_id"
	FROM
		"benefit_tier_plans" AS sb0) AS s1 ON b0. "id" = s2. "benefit_plan_id"
	LEFT OUTER JOIN (
		SELECT
			sb0. "id" AS "id",
			sb0. "benefit_tier_plan_id" AS "benefit_tier_plan_id"
		FROM
			"benefits" AS sb0) AS s2 ON s2. "id" = s1. "benefit_tier_plan_id"
    
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

As you can see in the raw SQL query s2 is being used before being defined and thus the error

### Expected behavior

I investigated a lot and tried different things, the only way to make it work just for the sake of it was when I hardcoded the `on` clause and `ix` to be what I expected from running Ecto.Query.Planner.plan(query, :all, Ecto.Adapters.Postgres):

```elixir
iex> query.joins
[
%Ecto.Query.JoinExpr{
  ...
  on: %Ecto.Query.QueryExpr{
            expr: {:==, [],
             [
               {{:., [], [{:&, [], [0]}, :id]}, [], []},
               {{:., [], [{:&, [], [1]}, :benefit_plan_id]}, [], []}
             ]},
            file: "path/app/deps/ecto/lib/ecto/association.ex",
            line: 239,
            params: []
          },
  ix: 1,
  ...
},
%Ecto.Query.JoinExpr{
  ...
  on: %Ecto.Query.QueryExpr{
          expr: {:==, [],
           [
             {{:., [], [{:&, [], [1]}, :id]}, [], []},
             {{:., [], [{:&, [], [2]}, :benefit_tier_plan_id]}, [], []}
           ]},
          file: "path/app/deps/ecto/lib/ecto/association.ex",
          line: 239,
          params: []
        }
  ix: 2,
  ...
},
]
```

Sorry for the long description of the problem and thank you in advance!

**Comment by greg-rychlewski** [comment]
Hi,

Thanks for reporting. I started looking at this but am having a bit of a hard time understanding the issue. Could you maybe present an Ecto query that you are using that is producing wrong results? No AST or manipulations or anything. Just `from something, join: something else, join: another something else`.

From your description it's hard for me to tell if the problem is because of manipulating the query internals  manuallylike this

```elixir
subquery_source = from(element in App.Benefits.BenefitTierPlan>)
    new_scope = %Ecto.SubQuery{query: subquery_source}
    join = Map.put(join,  :source, new_scope)
    joins = List.replace_at(query.joins, join_index, join)
    Map.put(query, :joins, joins)
```

**Comment by josevalim** [comment]
You are not supposed to manipulate the query fields directly and there is no guarantee the query you emit is correct if you do so.

**Comment by greg-rychlewski** [comment]
I think for learning internals it is probably better to use Elixir Forum. You might find someone willing to study the code with you or a maintainer might reach out if they have the time to help.

But for this issue board, please keep in mind we are all receiving e-mail alerts and trying to understand if there is a bug in the codebase based on the issue description. And in this case it is more a request to teach than an issue with Ecto.
