### ISSUE TITLE
Issue with Ecto.Changeset.validate_format/4

### ISSUE THREAD

**Issue by smahi** [elixir-ecto/ecto#4119]
### Elixir version

1.14.3

### Database and Version

Postgres 15.3.3

### Ecto Versions

3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.5

### Current behavior

```elixir
# task.ex schema

def tracked_task_changeset(task, attrs) do
    required_fields = [:longitude, :latitude, :speed]
    optional_fields = []

    task
    |> cast(attrs, required_fields ++ optional_fields)
    |> validate_required(required_fields)
    |> validate_longitude()
    |> validate_latitude()
    |> validate_speed()
    |> append_point_to_coordinates()
    |> update_approx_distance()
    |> update_approx_speed()
  end

  defp validate_longitude(changeset) do
    changeset
    |> validate_format(:longitude, ~r/([0-9.-]+).+?([0-9.-]+)/, message: "Invalid longitude value")
  end
```

```elixir
# tasks_test.exs

    test "update_tracked_task/2" do
      task = started_task_fixture()
      [point | rest] = @line_string_coords

      # point |> dbg
      # point #=> %{"latitude" => 5.53829364169647, "longitude" => 22.782575003607832}
      assert {:ok, %Task{} = task} = Tasks.update_tracked_task(task, point)
    end
```

The Above code throw the following error

```
     ** (FunctionClauseError) no function clause matching in Kernel.=~/2

     The following arguments were given to Kernel.=~/2:
     
         # 1
         22.782575003607832
     
         # 2
         ~r/([0-9.-]+).+?([0-9.-]+)/
     
     Attempted function clauses (showing 3 out of 3):
     
         def =~(left, "") when is_binary(left)
         def =~(left, right) when is_binary(left) and is_binary(right)
         def =~(left, right) when is_binary(left)
     
     code: assert {:ok, %Task{} = task} = Tasks.update_tracked_task(task, point)
     stacktrace:
       (elixir 1.14.3) lib/kernel.ex:2179: Kernel.=~/2
       (ecto 3.9.2) lib/ecto/changeset.ex:2048: anonymous fn/5 in Ecto.Changeset.validate_format/4
       (ecto 3.9.2) lib/ecto/changeset.ex:1735: Ecto.Changeset.validate_change/3
       (wsim 0.1.0) lib/wsim/tasks/task.ex:73: Wsim.Tasks.Task.tracked_task_changeset/2
       (wsim 0.1.0) lib/wsim/tasks.ex:458: Wsim.Tasks.update_tracked_task/2
       test/wsim/tasks_test.exs:389: (test)
```

### Expected behavior

To validate the data properly

**Comment by josevalim** [comment]
`validate_format` works on string columns and you are running it against a float. You should probably use other validations for numbers because a regex is not a very efficient way of validating a number.

Although we should check if the value is not a binary and raise a better error message.

**Comment by smahi** [comment]
@josevalim thank you so much for your help and detailed reply.
