### ISSUE TITLE
cast_assoc won't persist updated sort order as specified in the docs

### ISSUE THREAD

**Issue by dfalling** [elixir-ecto/ecto#4175]
### Elixir version

1.14.4

### Database and Version

PostgreSQL 15.2 with PostGIS 3.3.2

### Ecto Versions

3.10.0

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

1. call Changeset.cast_asoc with `sort_param` and `drop_param`.
2. call a custom function to update the sort, ending with a Changeset.put_change

```elixir

has_many(:addresses, Address,
  on_replace: :delete
)

changeset
|> cast_assoc(changeset, :addresses,
  sort_param: :addresses_sort,
  drop_param: :addresses_drop)
|> copy_children_positions()

defp copy_children_positions(changeset) do
  if children = Ecto.Changeset.get_change(changeset, :children) do
    children
    |> Enum.with_index(fn child, index ->
      Ecto.Changeset.put_change(child, :position, index)
    end)
    |> then(&Ecto.Changeset.put_change(changeset, :children, &1))
  else
    changeset
  end
end
```

### Expected behavior

The changeset should successfully change with the updated addresses. However it fails with:
```
** (RuntimeError) cannot replace related %Address{__meta__: #Ecto.Schema.Metadata<:loaded, "address">,
...
This typically happens when you are calling put_assoc/put_embed with the results of a previous 
put_assoc/put_embed/cast_assoc/cast_embed operation, which is not supported. You must call 
such operations only once per embed/assoc, in order for Ecto to track changes efficiently
    (ecto 3.10.0) lib/ecto/changeset/relation.ex:430: Ecto.Changeset.Relation.check_action!/2
    (ecto 3.10.0) lib/ecto/changeset/relation.ex:180: Ecto.Changeset.Relation.do_change/4
    (ecto 3.10.0) lib/ecto/changeset/relation.ex:347: Ecto.Changeset.Relation.map_changes/9
    (ecto 3.10.0) lib/ecto/changeset/relation.ex:156: Ecto.Changeset.Relation.change/3
    (ecto 3.10.0) lib/ecto/changeset.ex:1729: Ecto.Changeset.put_change/7
    (ecto 3.10.0) lib/ecto/changeset.ex:1720: Ecto.Changeset.put_change/3
```

**Comment by josevalim** [comment]
Thank you. We definitely need to fix the docs to not mention this. I also think we should support `:with` to receive 3 arguments. In such cases, the third argument is going to be the index in the collection, so we can store it in the database without an additional pass.

**Comment by dfalling** [comment]
Streamlining the update into the single `cast_assoc` call would be a great enhancement.

**Comment by LostKobrakai** [comment]
@josevalim Is there any more detail around of why this limitation is in place? It would be nice if this specific usecase can be solved, but on the other hand that means only this specific usecase is covered.

**Comment by josevalim** [comment]
@LostKobrakai because it can be complex, because we had the original data, the modified data (cast_assoc), and now new data (put_assoc) and it can be complex and ambiguous to what the new data applies to. For example, what happens if the new data is missing some changesets, how can we even generate the proper "patch" to delete it from the database.

The only case it is easy is if we assume the new data are all changesets which precisely match the changesets we had before. So I would prefer to allow the index to be given to `:with` and avoid another pass. :)

**Comment by v0idpwn** [comment]
+1 for adding the index on `:with`, but how, exactly? Do we decide the implementation based on the arity? I can write a PR.

**Comment by josevalim** [comment]
Exactly. Just check the arity. I already deprecated the MFA version in main. :)

**Comment by al2o3cr** [comment]
```
  if children = Ecto.Changeset.get_change(changeset, :children) do
    children
    |> Enum.with_index(fn child, index ->
```

One issue I see with this is that `children` will include _replaced_ rows (with `action: :replace`) so there may be gaps in the resulting `index` sequence. Those rows are also what makes `put_change` complain:

https://github.com/elixir-ecto/ecto/blob/f3311eeb1d49b7dad129fe5a84d290b196403b76/lib/ecto/changeset/relation.ex#L429-L434

Would something like [`skip_replaced` from `phoenix-ecto`](https://github.com/phoenixframework/phoenix_ecto/blob/v4.4.0/lib/phoenix_ecto/html.ex#L173-L178) help with this?

**Comment by dfalling** [comment]
Yeah, I noticed that gap too while troubleshooting this. Ideally the indexes passed to a new `:with` would exclude the items that are queued for delete.
