### ISSUE TITLE
Ecto.Enum doesn't work with module attributes in Ecto.Query

### ISSUE THREAD

**Issue by cjbottaro** [elixir-ecto/ecto#4321]
### Elixir version

1.15.7

### Database and Version

PostgreSQL 15.3

### Ecto Versions

3.11.0

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.3

### Current behavior

```elixir
defmodule Thing do
  use Ecto.Schema

  schema "things" do
    field :type, Ecto.Enum, values: [foo: "Type::Foo", bar: "Type::Bar"]
  end

  @types [:foo, :bar]

  def test do
    require Ecto.Query

    Ecto.Query.from(t in Thing, where: t.type in @types)
    |> Repo.all()
  end
end

```
Calling `Thing.test/0` results in this error:
```
** (Ecto.QueryError) unsupported expression: :foo in query:

from t0 in Thing,
  where: t0.type in [:foo, :bar],
  select: t0

    (ecto_sql 3.11.0) lib/ecto/adapters/postgres/connection.ex:1870: Ecto.Adapters.Postgres.Connection.error!/2
    (elixir 1.15.7) lib/enum.ex:4372: Enum.map_intersperse_list/3
    (ecto_sql 3.11.0) lib/ecto/adapters/postgres/connection.ex:855: Ecto.Adapters.Postgres.Connection.expr/3
    (ecto_sql 3.11.0) lib/ecto/adapters/postgres/connection.ex:828: Ecto.Adapters.Postgres.Connection.paren_expr/3
    (ecto_sql 3.11.0) lib/ecto/adapters/postgres/connection.ex:805: Ecto.Adapters.Postgres.Connection.boolean/4
    (ecto_sql 3.11.0) lib/ecto/adapters/postgres/connection.ex:168: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.11.0) lib/ecto/adapters/postgres.ex:132: Ecto.Adapters.Postgres.prepare/2
```

Note that if you change `Thing.test/0` to:
```elixir
  def test do
    require Ecto.Query

    Ecto.Query.from(t in Thing, where: t.type in [:foo, :bar])
    |> Repo.all()
  end
```

Then everything works fine.

### Expected behavior

To be able to use module attributes in the query.

**Comment by wojtekmach** [comment]
In the meantime this should work:

```elixir
where: t.type in ^@types
```
