### ISSUE TITLE
Unable to set keys dynamically using select_merge

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#4326]
### Elixir version

1.15.5

### Database and Version

PostgreSQL 14.1

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.3

### Current behavior

This code works fine:
```elixir
iex> "users" |> select([u], %{}) |> select_merge([u], %{:test => "1"}) |> limit(1) |> Repo.one 
[debug] QUERY OK source="users" db=0.8ms
SELECT TRUE FROM "users" AS u0 LIMIT 1
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:376
%{test: "1"}
```
```elixir
"users" |> select([u], %{}) |> select_merge([u], %{^"test" => "1"}) |> limit(1) |> Repo.one
[debug] QUERY OK source="users" db=0.8ms
SELECT 'test' FROM "users" AS u0 LIMIT 1
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:376
%{"test" => "1"}
```

but this doesn't:
```elixir
iex(3)> "users" |> select([u], %{}) |> select_merge([u], %{^:test => "1"}) |> limit(1) |> Repo.one
[debug] QUERY ERROR source="users" db=1.8ms
SELECT 'test' FROM "users" AS u0 LIMIT 1
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:376
** (DBConnection.EncodeError) Postgrex expected a binary, got :test. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (postgrex 0.17.3) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.encode_params/3
    (postgrex 0.17.3) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.6.0) lib/db_connection.ex:1403: DBConnection.encode/5
    (db_connection 2.6.0) lib/db_connection.ex:1503: DBConnection.run_prepare_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
    (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:735: DBConnection.prepare_execute/4
    (ecto_sql 3.10.2) lib/ecto/adapters/postgres/connection.ex:70: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:953: Ecto.Adapters.SQL.execute!/5
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
    iex:3: (file)
```

### Expected behavior

Support setting non-binary keys dynamically

**Comment by josevalim** [comment]
As per the error message, interpolated values are sent to the database. We can’t send an atom to the database and we wouldn’t be able to fetch it back as an atom either, so you need to pass strings and if you really want an atom back, you can convert it after the fact.

**Comment by gorkunov** [comment]
it make code a bit clunky when we operate with with the list of atoms and doing multiple `select_merge` on a query iterate on this list. So we need to converts atoms to strings during this iteration and then when we receive results convert result to atoms backs.

**Comment by josevalim** [comment]
I would select a single field with the Enum and the denornalize it later or keep them as strings. My point though is that even if we allowed atoms, you wouldn’t get atoms back anyway because interpolated values are always sent to the database.

**Comment by josevalim** [comment]
Ecto v3.11 introduces a literal(^foo) construct and maybe we can allow that in map fields (or anywhere in a select). A PR is welcome.
