### ISSUE TITLE
Wrong query casting through simple custom types

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#4444]
### Elixir version

Elixir 1.17.0, OTP 27

### Database and Version

PostgreSQL 16

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

Given the following code:
```elixir
defmodule CustomDate do
  use Ecto.Type
  def type, do: :utc_datetime

  def cast(input) when is_binary(input) do
    case DateTime.from_iso8601(input) do
      {:ok, result} ->
        result

      _ ->
        {:error, [message: "is not a valid ISO8601 datetime"]}
    end
  end
  def cast(%DateTime{} = input), do: input

  def load(datetime), do: datetime
  def dump(datetime), do: datetime
end

defmodule Notice do
  use Ecto.Schema

  schema "notices" do
    field :valid_until, CustomDate
  end
end

defmodule Notices do
  import Ecto.Query
  
  def active_notices do
    now = DateTime.utc_now(:second)

    Notice
    |> where([n], n.valid_until > ^now)
    |> Repo.all()
  end
end
```

After calling `Notices.active_notices`, an `Ecto.Query.CastError` is raised:
```
value `~U[2024-07-09 14:40:13Z]` in `where` cannot be cast to type CustomDate in query:

from n0 in Notice,
  where: n0.valid_until > ~U[2024-07-09 14:40:13Z]

    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.17.0) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:214: Ecto.Repo.Queryable.execute/4
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

However, if the code is changed to explicitly cast the type as follows, then everything works:
```elixir
  def active_notices do
    now = DateTime.utc_now(:second)

    Notice
    |> where([n], n.valid_until > type(^now, :utc_datetime))
    |> Repo.all()
  end
```

### Expected behavior

Because CustomDate supports casting from a DateTime value, the original query should work. Alternatively, Ecto should automatically try to cast the query value to the underlying type used by the simple custom type.

**Comment by josevalim** [comment]
You should return `{:ok, ...}` tuples from `cast`. Could that be the root cause? If it is, we should probably change the code to raise a better message.

**Comment by liamwhite** [comment]
Oops, yes -- that did fix this specific casting error, however, I get another one:
```
[error] ** (FunctionClauseError) no function clause matching in Ecto.Type.process_dumpers/3
    (ecto 3.11.2) lib/ecto/type.ex:945: Ecto.Type.process_dumpers([], ~U[2024-07-09 15:13:00Z], Ecto.Adapters.Postgres)
    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.17.0) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:214: Ecto.Repo.Queryable.execute/4
```

**Comment by v0idpwn** [comment]
It's also returning the wrong value. See https://hexdocs.pm/ecto/Ecto.Type.html#callbacks for the expected typespecs

**Comment by liamwhite** [comment]
Never mind - those needed to be fixed as well. All seems to be working as intended after that. Sorry for the trouble.
