### ISSUE TITLE
Translation keys can't be specified for default validation functions

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#4455]
### Elixir version

1.17.0

### Database and Version

PostgreSQL 16.3

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.18.0

### Current behavior

Specifying a message with translation keys does not work with the built-in validation functions (anything that calls `validate_change` and accepts a `message` option). E.g. attempting to use this:
```ex
  changeset
  |> put_change(:mime, mime)
  |> validate_inclusion(:mime, ~W(image/jpeg image/png),  message: {"(%{value}) is invalid", value: mime})
```
raises an error:
```
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Ecto.Changeset.validate_change/3
    (ecto 3.11.2) lib/ecto/changeset.ex:2430: anonymous fn({:mime, {{"%{value} is not allowed", [value: "application/pdf"]}, [validation: :inclusion, enum: ["image/jpeg", "image/png"]]}}) in Ecto.Changeset.validate_change/3
    (elixir 1.17.0) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto 3.11.2) lib/ecto/changeset.ex:2430: Ecto.Changeset.validate_change/3
```

### Expected behavior

Built-in validation functions should allow messages to include translation keys, similarly to `add_error/4`.

**Comment by josevalim** [comment]
Good call. A PR is welcome!

**Comment by liamwhite** [comment]
I gave it a go - https://github.com/liamwhite/ecto/commit/f151cd39c7058ed4142ea48b9d4b7eec998689f6

While this is possible without any special considerations for the `validate_*` family of functions, it does not appear to be possible for constraints without breaking the public API - constraints would need to be changed from `String.t()` to `String.t() | {String.t(), Keyword.t()}`, and Repo.Schema would need to be updated to convert the constraint message format list.

**Comment by josevalim** [comment]
Please do send a PR, we can review constraints later!
