### ISSUE TITLE
Can't preload associations using custom primary keys

### ISSUE THREAD

**Issue by raiomarco** [elixir-ecto/ecto#4475]
### Elixir version

1.17.2

### Database and Version

PostgreSQL 15.5

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.18.0

### Current behavior

i have 2 entities on a already working database, so i can't change the primary key to the default id on the cliente

```elixir
defmodule ExCraw.Cliente do
  use Ecto.Schema

  @primary_key {:id_cliente, :integer, []}
  schema "clientes" do
    field(:name, :string)
    has_many(:words, ExCraw.Word, foreign_key: :id_cliente)
  end
end
```

```elixir
defmodule ExCraw.Word do
  use Ecto.Schema

  @primary_key {:id, :integer, []}
  schema "words" do
    belongs_to(:cliente, ExCraw.Cliente, foreign_key: :id_cliente)
    field(:word, :string)
  end
end
```

then when trying to query like this:
```elixir
words =
      ExCraw.Word
      |> ExCraw.Repo.all()
      |> ExCraw.Repo.preload(:cliente)
      |> Enum.map(fn x ->
        %{
          word: x.word,
          id_cliente: x.id_cliente,
          cliente: x.cliente.name
        }
      end)
```

i get this error:
```
19:00:09.492 [error] GenServer #PID<0.492.0> terminating
** (Ecto.QueryError) deps/ecto/lib/ecto/association.ex:1226: field `id` in `where` does not exist in schema ExCraw.Cliente in query:

from c0 in ExCraw.Cliente,
  where: c0.id in ^[
  5,
  51,
  17,
  29,
  4,
  20,
  13,
  41,
  49,
  50,
  7,
  8,
  48,
  42,
  3,
  1,
  47,
  46,
  12,
  45,
  43,
  39,
  40,
  32,
  28,
  27,
  30,
  25,
  44,
  15,
  2,
  19,
  31,
  38,
  16,
  21,
  37,
  35,
  36,
  34,
  33,
  26,
  23,
  9,
  24,
  22,
  18,
  14,
  11,
  10,
  6
],
  select: {c0.id, c0}

    (elixir 1.17.2) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.17.2) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Last message: {:continue, {:startup, [crawl_id: "13fa812e-5376-11ef-8f9a-be46a4acf2ac"]}}
State: %{name: ExCraw.StackExchange, workers: [ok: #PID<0.495.0>, ok: #PID<0.496.0>, ok: #PID<0.497.0>, ok: #PID<0.498.0>, ok: #PID<0.499.0>, ok: #PID<0.500.0>, ok: #PID<0.501.0>, ok: #PID<0.502.0>], itemcount_limit: 100, crawl_id: "13fa812e-5376-11ef-8f9a-be46a4acf2ac", tref: #Reference<0.843542996.2263089155.215353>, prev_scraped_cnt: 0, closespider_timeout_limit: 10}
```

when querying individually for the **Cliente**, then it works:
```elixir
words =
      ExCraw.Word
      |> ExCraw.Repo.all()
      |> Enum.map(fn x ->
        %{
          word: x.word,
          id_cliente: x.id_cliente,
          cliente: ExCraw.Cliente |> ExCraw.Repo.get!(x.id_cliente)
        }
      end)
```
(output example)
```
19:09:09.393 [debug] QUERY OK source="clientes" db=67.9ms idle=618.2ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [40]

19:09:09.462 [debug] QUERY OK source="clientes" db=68.9ms queue=0.1ms idle=617.9ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [40]

19:09:09.530 [debug] QUERY OK source="clientes" db=67.7ms idle=615.9ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:09.598 [debug] QUERY OK source="clientes" db=67.8ms idle=616.4ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:09.668 [debug] QUERY OK source="clientes" db=69.9ms idle=615.4ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:09.736 [debug] QUERY OK source="clientes" db=67.4ms queue=0.1ms idle=618.1ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:09.804 [debug] QUERY OK source="clientes" db=67.3ms idle=617.1ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:09.874 [debug] QUERY OK source="clientes" db=70.4ms idle=617.3ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:09.943 [debug] QUERY OK source="clientes" db=68.4ms idle=618.5ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.012 [debug] QUERY OK source="clientes" db=68.4ms idle=618.9ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.083 [debug] QUERY OK source="clientes" db=70.6ms idle=619.3ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.151 [debug] QUERY OK source="clientes" db=68.0ms idle=620.9ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.219 [debug] QUERY OK source="clientes" db=67.5ms idle=621.3ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.289 [debug] QUERY OK source="clientes" db=69.3ms idle=621.1ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.358 [debug] QUERY OK source="clientes" db=69.2ms idle=620.4ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.427 [debug] QUERY OK source="clientes" db=68.9ms idle=622.0ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.495 [debug] QUERY OK source="clientes" db=67.6ms idle=623.9ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.564 [debug] QUERY OK source="clientes" db=67.5ms idle=621.4ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.635 [debug] QUERY OK source="clientes" db=71.3ms queue=0.1ms idle=620.9ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.705 [debug] QUERY OK source="clientes" db=68.8ms queue=0.1ms idle=624.1ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.774 [debug] QUERY OK source="clientes" db=68.8ms queue=0.1ms idle=622.6ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.842 [debug] QUERY OK source="clientes" db=67.3ms queue=0.1ms idle=623.7ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]

19:09:10.909 [debug] QUERY OK source="clientes" db=67.1ms idle=623.4ms
SELECT c0."id_cliente", c0."client_name" FROM "clientes" AS c0 WHERE (c0."id_cliente" = $1) [19]
```
but as you would expect, with SEVERE performance degradation

so, this looks like a bug, or just a edge case for a *not so common* situation :')

### Expected behavior

I think it should had preloaded the association using the custom primary key instead of the default `:id` one :')

**Comment by greg-rychlewski** [comment]
Hi @raiomarco ,

`:foreign_key` means the name of the field on the current schema while `:references` means the name of the field on the associated schema. `:references` defaults to `:id`. If you put `references: :id_clientle` in `ExCraw.Word` it should work.

**Comment by josevalim** [comment]
To be more precise, the foreign key is always the foreign key in the database. The references points to the primary key. So you need to swap them accordingly on each schema.

**Comment by raiomarco** [comment]
ohhh, my bad, it worked...

sorry for bothering with this :')

and thanks for helping me with this
