### ISSUE TITLE
`Ecto.Query.API.type` results in `FunctionClauseError`

### ISSUE THREAD

**Issue by florius0** [elixir-ecto/ecto#4533]
### Elixir version

Elixir 1.17.2

### Database and Version

PostgreSQL 15.8

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.19.0

### Current behavior

Consider this minimal reproduction:

```elixir
type = {:parameterized, Ecto.Enum,
 %{
   on_load: %{"action" => :action, "info" => :info},
   type: :string,
   on_cast: %{"action" => :action, "info" => :info},
   embed_as: :self,
   mappings: [info: "info", action: "action"],
   on_dump: %{info: "info", action: "action"}
 }}
 
# works as expected
from(q in MySchema) |> where(^dynamic(^dynamic([q], q |> field(^:field)) in [:action]))

# Results in
# ** (FunctionClauseError) no function clause matching in Macro.do_traverse_args/4

#     The following arguments were given to Macro.do_traverse_args/4:

#         # 1
#         %{
#           on_load: %{"action" => :action, "info" => :info},
#           type: :string,
#           on_cast: %{"action" => :action, "info" => :info},
#           embed_as: :self,
#           mappings: [info: "info", action: "action"],
#           on_dump: %{info: "info", action: "action"}
#         }

#         # 2
#         {[{:q, [line: 35], nil}], [], [], %{}, 0}

#         # 3
#         #Function<30.103791220/2 in Macro.postwalk/3>

#         # 4
#         #Function<1.9816866/2 in Ecto.Query.Builder.Dynamic.expand/3>

#     Attempted function clauses (showing 2 out of 2):

#         defp do_traverse_args(args, acc, _pre, _post) when is_atom(args)
#         defp do_traverse_args(args, acc, pre, post) when is_list(args)

#     (elixir 1.17.2) lib/macro.ex:632: Macro.do_traverse_args/4
#     (elixir 1.17.2) lib/macro.ex:604: Macro.do_traverse/4
#     (stdlib 5.2.3) lists.erl:1706: :lists.mapfoldl_1/3
#     (stdlib 5.2.3) lists.erl:1707: :lists.mapfoldl_1/3
#     (elixir 1.17.2) lib/macro.ex:604: Macro.do_traverse/4
#     (stdlib 5.2.3) lists.erl:1706: :lists.mapfoldl_1/3
#     (elixir 1.17.2) lib/macro.ex:604: Macro.do_traverse/4
#     (ecto 3.11.2) lib/ecto/query/builder/dynamic.ex:49: Ecto.Query.Builder.Dynamic.fully_expand/2
#     (ecto 3.11.2) lib/ecto/query/builder/filter.ex:133: Ecto.Query.Builder.Filter.filter!/7
#     iex:35: (file)

from(q in MySchema) |> where(^dynamic(^dynamic([q], q |> field(^:field) |> type(^type)) in [:action]))
```

PS

Neither using raw type value in an attribute (as in https://hexdocs.pm/ecto/Ecto.Query.API.html#type/2), neither `init`'ing the type changes the behaviour

### Expected behavior

`type` should be dynamic-compatible

**Comment by florius0** [comment]
Upon further investigation it appears that custom type handling is missing somewhere.

Doing this:

```elixir
type = case type do
  {:parameterized, module, params} -> module.type(params)
  type -> type
end
```

circumvents the issue.

I suppose the reason is that dynamic simply traverses AST before custom type handling occurs?

**Comment by josevalim** [comment]
This works for me in `main`:

```
import Ecto.Query
type = Ecto.ParameterizedType.init(Ecto.Enum, values: [:action, :info])

from(q in "foo")
|> where(^dynamic(^dynamic([q], q |> field(^:field) |> type(^type)) in [:action]))
```

**Comment by florius0** [comment]
I suppose it was fixed in #4480.

I'll try upgrading to latest version tomorrow.

**Comment by greg-rychlewski** [comment]
Hi @florius0 ,

I was wondering if you were able to confirm if that commit fixed your issue. Thanks

**Comment by florius0** [comment]
Yes, the new Ecto version indeed fixes it.
